Repository eclipse-kapua/kapua, pull requests merged in 2018-11, with the labels that each got.

#2173 Stop Endpoint Info fallback if there are Endpoints specified in scope
  service/endpoint/internal/src/main/java/org/eclipse/kapua/service/endpoint/internal/EndpointInfoServiceImpl.java
Labels: bug

#2191 Added JobStepDefinition filtering on add dialog
  console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/setting/ConsoleSettingKeys.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/server/GwtJobStepDefinitionServiceImpl.java
Labels: console-gwt, enhancement

#2203 Fix typo in the docker guide
  docs/developer-guide/en/running.md
  docs/developer-guide/en/sso.md
Labels: bug, documentation
