Repository eclipse-kapua/kapua, pull requests merged in 2019-08, with the labels that each got.

#2659 Upgraded protobuf-java version from 2.6.1 to 3.8.0 - CVE-2015-5237 - CWE-119
  client/gateway/features/karaf/src/main/feature/feature.xml
  client/gateway/profile/kura/src/main/protobuf/kurapayload.proto
  pom.xml
  qa/integration/src/test/protobuf/kurapayload.proto
  service/device/call/kura/pom.xml
  service/device/call/kura/src/main/protobuf/kurapayload.proto
  simulator-kura/pom.xml
  simulator-kura/src/main/protobuf/kurapayload.proto
Labels: Build and test, CQ approved

#2683 Added test scenarios for data store service
  qa/common/src/main/java/org/eclipse/kapua/qa/common/BasicSteps.java
  qa/common/src/main/java/org/eclipse/kapua/qa/common/TestBase.java
  qa/common/src/main/java/org/eclipse/kapua/qa/common/cucumber/CucMetric.java
  qa/integration/src/test/resources/features/datastore/Datastore.feature
  service/datastore/test-steps/src/main/java/org/eclipse/kapua/service/datastore/steps/DatastoreSteps.java
Labels: Test

#2688 Improved Quartz configuration
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/quartz/driver/QuartzTriggerDriver.java
  service/scheduler/quartz/src/main/resources/quartz.properties
Labels: bug

#2661 LoginInfo REST API
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Authentication.java
  rest-api/web/src/main/java/org/eclipse/kapua/app/api/web/JaxbContextResolver.java
  rest-api/web/src/main/resources/shiro.ini
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/AuthenticationService.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/token/AccessTokenFactory.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/token/LoginInfo.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/AuthenticationServiceShiroImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/token/shiro/AccessTokenFactoryImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/token/shiro/LoginInfoImpl.java
Labels: enhancement

#2691 Add useSsl and additional options to DB connection string - errata corrige
  commons/src/main/java/org/eclipse/kapua/commons/jpa/MariaDBJdbcConnectionUrlResolver.java
  commons/src/main/resources/kapua-environment-setting.properties
Labels: bug
