Repository eclipse-kapua/kapua, pull requests merged in 2019-07, with the labels that each got.

#2637 Improved implementation of KapuaException and KapuaRuntimeException
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/exception/RestApiRuntimeException.java
  service/api/src/main/java/org/eclipse/kapua/ExceptionMessageUtils.java
  service/api/src/main/java/org/eclipse/kapua/KapuaErrorCode.java
  service/api/src/main/java/org/eclipse/kapua/KapuaException.java
  service/api/src/main/java/org/eclipse/kapua/KapuaRuntimeException.java
  service/api/src/test/java/org/eclipse/kapua/KapuaExceptionTest.java
Labels: enhancement

#2638 Fixed javadoc generation
  service/api/src/main/java/org/eclipse/kapua/event/ServiceEvent.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/definition/quartz/TriggerDefinitionDAO.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/quartz/TriggerDAO.java
Labels: bug, build

#2621 Upgraded Paho version from 1.1.0 to 1.2.1
  pom.xml
Labels: Build and test, enhancement

#2643 Use .tgz files to build Docker Images
  assembly/api/pom.xml
  assembly/broker/pom.xml
  assembly/console/pom.xml
  assembly/events-broker/pom.xml
  assembly/jetty-base/pom.xml
  assembly/sql/pom.xml
Labels: build

#2649 Added Cucumber Testing Specific Information
  docs/developer-guide/en/images/kapua-reports-main-page.png
  docs/developer-guide/en/images/kapua-sample-test-report.png
  docs/developer-guide/en/qa.md
Labels: documentation, test

#2656 Set totalCount and limitExceeded in DataMessageJson.query result
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DataMessagesJson.java
Labels: bug

#2669 Remove scopeId null check on queries and counts
  commons/src/main/java/org/eclipse/kapua/commons/service/event/store/internal/EventStoreServiceImpl.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/queue/jbatch/QueuedJobExecutionServiceImpl.java
  service/device/management/job/internal/src/main/java/org/eclipse/kapua/service/device/management/job/internal/JobDeviceManagementOperationServiceImpl.java
  service/device/management/registry/internal/src/main/java/org/eclipse/kapua/service/device/management/registry/operation/internal/DeviceManagementOperationRegistryServiceImpl.java
  service/device/management/registry/internal/src/main/java/org/eclipse/kapua/service/device/management/registry/operation/notification/internal/ManagementOperationNotificationServiceImpl.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/common/DeviceValidation.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/connection/internal/DeviceConnectionServiceImpl.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/connection/option/internal/DeviceConnectionOptionServiceImpl.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/event/internal/DeviceEventServiceImpl.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/execution/internal/JobExecutionServiceImpl.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/internal/JobServiceImpl.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/step/internal/JobStepServiceImpl.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/targets/internal/JobTargetServiceImpl.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/quartz/TriggerServiceImpl.java
  service/security/certificate/internal/src/main/java/org/eclipse/kapua/service/certificate/internal/CertificateInfoServiceImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/shiro/CredentialServiceImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/token/shiro/AccessTokenServiceImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/access/shiro/AccessInfoServiceImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/access/shiro/AccessPermissionServiceImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/access/shiro/AccessRoleServiceImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/group/shiro/GroupServiceImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/role/shiro/RolePermissionServiceImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/role/shiro/RoleServiceImpl.java
  service/tag/internal/src/main/java/org/eclipse/kapua/service/tag/internal/TagServiceImpl.java
Labels: enhancement
