Repository eclipse-kapua/kapua, pull requests merged in 2019-06, with the labels that each got.

#2614 Fix job engine throw exceptions
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/JobEngineServiceJbatch.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/exception/JobEngineException.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/exception/JobResumingException.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/exception/KapuaJobEngineErrorCodes.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/exception/KapuaJobEngineException.java
Labels: bug

#2619 Removed device unique constraint on modem IMEI, IMSI, ICCID
  service/device/registry/internal/src/main/resources/liquibase/1.1.0/changelog-device-1.1.0.xml
  service/device/registry/internal/src/main/resources/liquibase/1.1.0/device-remove-modem-constraint.xml
Labels: enhancement

#2615 Upgraded Guava version from 19.0 to 27.1-jre - CVE-2018-10237 - CWE-119
  broker-core/src/main/java/org/eclipse/kapua/broker/core/listener/DeviceManagementNotificationMessageProcessor.java
  broker-core/src/main/readme.txt
  pom.xml
Labels: CQ approved, Security, enhancement

#2616 Upgraded H2 version from 1.4.192 to 1.4.199 - CVE-2018-10054 - CWE-94
  commons/src/test/java/org/eclipse/kapua/commons/liquibase/KapuaLiquibaseClientTest.java
  commons/src/test/resources/liquibase/liquibase.sql
  pom.xml
Labels: CQ approved, Security, enhancement

#2620 Upgraded Logback version from 1.1.8 to 1.2.3 - CVE-2017-5929 - CWE-502
  pom.xml
Labels: CQ approved, Security, enhancement

#2627 Upgraded Slf4j-api version from 25.0 to 26.0 - CVE-2018-8088
  pom.xml
  simulator-kura/pom.xml
Labels: CQ approved, Security, enhancement

#2617 Upgraded Jackson Databind version from 2.8.6 to 2.9.9 - CVE-2018-14718 - CWE-502
  pom.xml
Labels: CQ approved, Security, enhancement

#2618 Upgraded Qpid Jms Client version from 0.24.0 to 0.40.0 - CVE-2018-17187 - CWE-300
  assembly/broker/pom.xml
  pom.xml
Labels: CQ approved, Security, enhancement

#2632 Set kapua-guice dependency scope to test
  broker-core/pom.xml
  qa/common/pom.xml
  rest-api/core/pom.xml
  service/account/internal/pom.xml
  service/datastore/internal/pom.xml
  service/endpoint/internal/pom.xml
  service/job/internal/pom.xml
  service/scheduler/quartz/pom.xml
  service/security/shiro/pom.xml
  service/tag/internal/pom.xml
  service/user/internal/pom.xml
Labels: bug, build

#2633 Upgraded Guava version from 19.0 to 27.1-jre - CVE-2018-10237 - CWE-119 - errata corrige
  assembly/broker/descriptors/kapua-broker.xml
  assembly/broker/pom.xml
  pom.xml
Labels: CQ approved, Security, enhancement

#2626 Feature job delete forced
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/client/JobDeleteForcedDialog.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/client/JobGrid.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/client/JobGridToolbar.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/server/GwtJobServiceImpl.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/shared/model/permission/JobSessionPermission.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/shared/service/GwtJobService.java
  console/module/job/src/main/resources/org/eclipse/kapua/app/console/module/job/client/messages/ConsoleJobMessages.properties
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/JobEngineServiceJbatch.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/listener/KapuaJobListener.java
  service/job/api/src/main/java/org/eclipse/kapua/service/job/JobService.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/internal/JobServiceImpl.java
Labels: enhancement

#2634 Upgraded commons-collections version from 3.2.1 to 3.2.2 - CVE-2015-7501 - CWE-502
  pom.xml
Labels: CQ approved, Security, enhancement

#2635 Upgraded commons-beanutils version from 1.9.2 to 1.9.3 - CVE-2014-0114 - CWE-20
  pom.xml
Labels: CQ pending, Security, enhancement
