Repository eclipse-kapua/kapua, pull requests merged in 2019-09, with the labels that each got.

#2712 Upgrade SwaggerUI to 3.23.0
  .travis.yml
  assembly/api/descriptors/kapua-api-jetty.xml
  assembly/api/pom.xml
  assembly/api/resources/index.html
  assembly/api/resources/style.css
  deployment/docker/README.md
  deployment/minishift/README.md
  dev-tools/vagrant/README.md
  external/pom.xml
  external/swagger-ui-lib/pom.xml
  external/swagger-ui-lib/src/main/resources/backbone-min.js
  external/swagger-ui-lib/src/main/resources/handlebars-2.0.0.js
  external/swagger-ui-lib/src/main/resources/highlight.7.3.pack.js
  external/swagger-ui-lib/src/main/resources/jquery-1.8.0.min.js
  external/swagger-ui-lib/src/main/resources/jquery.ba-bbq.min.js
  external/swagger-ui-lib/src/main/resources/jquery.slideto.min.js
  external/swagger-ui-lib/src/main/resources/jquery.wiggle.min.js
  external/swagger-ui-lib/src/main/resources/jsoneditor.min.js
  external/swagger-ui-lib/src/main/resources/marked.js
  external/swagger-ui-lib/src/main/resources/underscore-min.js
  external/swagger-ui/pom.xml
  external/swagger-ui/src/main/resources/about.html
  external/swagger-ui/src/main/resources/css/print.css
  external/swagger-ui/src/main/resources/css/reset.css
  external/swagger-ui/src/main/resources/css/screen.css
  external/swagger-ui/src/main/resources/css/style.css
  external/swagger-ui/src/main/resources/css/typography.css
  external/swagger-ui/src/main/resources/fonts/DroidSans-Bold.ttf
  external/swagger-ui/src/main/resources/fonts/DroidSans.ttf
  external/swagger-ui/src/main/resources/images/collapse.gif
  external/swagger-ui/src/main/resources/images/expand.gif
  external/swagger-ui/src/main/resources/images/explorer_icons.png
  external/swagger-ui/src/main/resources/images/favicon-16x16.png
  external/swagger-ui/src/main/resources/images/favicon-32x32.png
  external/swagger-ui/src/main/resources/images/favicon.ico
  external/swagger-ui/src/main/resources/images/logo.png
  external/swagger-ui/src/main/resources/images/pet_store_api.png
  external/swagger-ui/src/main/resources/images/throbber.gif
  external/swagger-ui/src/main/resources/images/wordnik_api.png
  external/swagger-ui/src/main/resources/index.html
  external/swagger-ui/src/main/resources/lang/en.js
  external/swagger-ui/src/main/resources/lang/es.js
  external/swagger-ui/src/main/resources/lang/fr.js
  external/swagger-ui/src/main/resources/lang/it.js
  external/swagger-ui/src/main/resources/lang/ja.js
  external/swagger-ui/src/main/resources/lang/pl.js
  external/swagger-ui/src/main/resources/lang/pt.js
  external/swagger-ui/src/main/resources/lang/ru.js
  external/swagger-ui/src/main/resources/lang/tr.js
  external/swagger-ui/src/main/resources/lang/translator.js
  external/swagger-ui/src/main/resources/lang/zh-cn.js
  external/swagger-ui/src/main/resources/lib/swagger-oauth.js
  external/swagger-ui/src/main/resources/o2c.html
  external/swagger-ui/src/main/resources/swagger-ui.js
  pom.xml
  rest-api/web/pom.xml
  rest-api/web/src/main/webapp/doc/index.html
Labels: CQ approved, enhancement, rest-api

#2725 Fixed javadoc
  service/device/management/packages/internal/src/main/java/org/eclipse/kapua/service/device/management/packages/message/internal/PackageRequestPayload.java
Labels: bug, documentation

#2724 Fixed Trigger creation from child accounts
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/ServiceDAO.java
  service/scheduler/api/src/main/java/org/eclipse/kapua/service/scheduler/trigger/definition/TriggerDefinitionService.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/definition/quartz/TriggerDefinitionDAO.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/definition/quartz/TriggerDefinitionServiceImpl.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/quartz/TriggerServiceImpl.java
Labels: bug

#2721 Add message received timestamp header property
  broker-core/src/main/java/org/eclipse/kapua/broker/core/message/MessageConstants.java
  broker-core/src/main/java/org/eclipse/kapua/broker/core/plugin/KapuaSecurityBrokerFilter.java
Labels: enhancement
