Repository eclipse-kapua/kapua, pull requests merged in 2020-11, with the labels that each got.

#3132 Multi Factor Authentication user manual
  docs/user-manual/en/images/mfa_enable.png
  docs/user-manual/en/images/mfa_login.png
  docs/user-manual/en/images/mfa_qr_code.png
  docs/user-manual/en/images/mfa_user_view.png
  docs/user-manual/en/mfa.md
  docs/user-manual/en/summary.md
Labels: documentation

#3137 Fixes for Multi Factor Authentication
  console/core/src/main/java/org/eclipse/kapua/app/console/core/client/MfaLoginDialog.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/client/MfaManagementDialog.java
  console/module/api/src/main/resources/org/eclipse/kapua/app/console/module/api/client/messages/ConsoleMessages.properties
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/client/tabs/credentials/ForgetTrustMachineDialog.java
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/client/tabs/credentials/MfaManagementPanel.java
  console/module/authentication/src/main/resources/org/eclipse/kapua/app/console/module/authentication/client/messages/ConsoleCredentialMessages.properties
  docs/user-manual/en/Permissions.md
Labels: Bug, Console GWT, Enhancement

#3141 Credentials documentation
  docs/user-manual/en/credentials.md
  docs/user-manual/en/images/credential_service_settings.png
Labels: documentation

#3147 MFA QRCodeServlet removal
  assembly/broker/descriptors/kapua-broker.xml
  assembly/broker/pom.xml
  console/core/pom.xml
  console/core/src/main/java/org/eclipse/kapua/app/console/core/servlet/QRCodeServlet.java
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/client/tabs/credentials/MfaManagementPanel.java
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/shared/model/GwtMfaCredentialOptions.java
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/shared/util/KapuaGwtAuthenticationModelConverter.java
  console/pom.xml
  console/web/src/main/webapp/WEB-INF/web.xml
  pom.xml
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/MfaOption.java
  service/security/shiro/pom.xml
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/MfaOptionImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/MfaOptionServiceImpl.java
Labels: Enhancement

#3151 Missing zxing dependencies added to broker assembly
  assembly/broker/descriptors/kapua-broker.xml
  assembly/broker/pom.xml
  pom.xml
Labels: Bug
