Repository eclipse-kapua/kapua, pull requests merged in 2020-01, with the labels that each got.

#2817 Snapshot Download REST API
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceManagementSnapshots.java
  rest-api/resources/src/main/resources/openapi/deviceSnapshot/deviceSnapshot-scopeId-deviceId-snapshotId-_rollback.yaml
  rest-api/resources/src/main/resources/openapi/deviceSnapshot/deviceSnapshot-scopeId-deviceId-snapshotId.yaml
  rest-api/resources/src/main/resources/openapi/deviceSnapshot/deviceSnapshot.yaml
  rest-api/resources/src/main/resources/openapi/openapi.yaml
Labels: enhancement, rest-api

#2822 Upgraded Jackson Databind version from 2.9.9.1 to 2.10.1 - CWE-502
  pom.xml
Labels: CQ approved, Security, enhancement

#2821 Upgraded commons-beanutils version from 1.9.3 to 1.9.4 - CVE-2019-10086 - CWE-502
  pom.xml
Labels: CQ approved, Security, enhancement

#2830 Fix H2 URI in Dockerfile
  assembly/sql/docker/Dockerfile
  dev-tools/vagrant/baseBox/Vagrantfile
Labels: build

#2832 Total Count in Queries
  commons/src/main/java/org/eclipse/kapua/commons/model/query/AbstractKapuaQuery.java
  commons/src/main/java/org/eclipse/kapua/commons/model/query/KapuaListResultImpl.java
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/ServiceDAO.java
  console/module/account/src/main/java/org/eclipse/kapua/app/console/module/account/server/GwtAccountServiceImpl.java
  console/module/account/src/main/java/org/eclipse/kapua/app/console/module/account/shared/util/GwtKapuaAccountModelConverter.java
  console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/shared/model/query/GwtQuery.java
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/server/GwtCredentialServiceImpl.java
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/shared/util/GwtKapuaAuthenticationModelConverter.java
  console/module/authorization/src/main/java/org/eclipse/kapua/app/console/module/authorization/server/GwtAccessPermissionServiceImpl.java
  console/module/authorization/src/main/java/org/eclipse/kapua/app/console/module/authorization/server/GwtAccessRoleServiceImpl.java
  console/module/authorization/src/main/java/org/eclipse/kapua/app/console/module/authorization/server/GwtGroupServiceImpl.java
  console/module/authorization/src/main/java/org/eclipse/kapua/app/console/module/authorization/server/GwtRoleServiceImpl.java
  console/module/authorization/src/main/java/org/eclipse/kapua/app/console/module/authorization/shared/util/GwtKapuaAuthorizationModelConverter.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/server/GwtDeviceConnectionServiceImpl.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/server/GwtDeviceManagementOperationServiceImpl.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/server/GwtDeviceServiceImpl.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/shared/util/GwtKapuaDeviceModelConverter.java
  console/module/endpoint/src/main/java/org/eclipse/kapua/app/console/module/endpoint/server/GwtEndpointServiceImpl.java
  console/module/endpoint/src/main/java/org/eclipse/kapua/app/console/module/endpoint/shared/util/GwtKapuaEndpointModelConverter.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/server/GwtJobExecutionServiceImpl.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/server/GwtJobServiceImpl.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/server/GwtJobStepServiceImpl.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/server/GwtJobTargetServiceImpl.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/server/GwtTriggerServiceImpl.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/shared/util/GwtKapuaJobModelConverter.java
  console/module/tag/src/main/java/org/eclipse/kapua/app/console/module/tag/server/GwtTagServiceImpl.java
  console/module/tag/src/main/java/org/eclipse/kapua/app/console/module/tag/shared/util/GwtKapuaTagModelConverter.java
  console/module/user/src/main/java/org/eclipse/kapua/app/console/module/user/server/GwtUserServiceImpl.java
  console/module/user/src/main/java/org/eclipse/kapua/app/console/module/user/shared/util/GwtKapuaUserModelConverter.java
  rest-api/resources/src/main/resources/openapi/openapi.yaml
  service/api/src/main/java/org/eclipse/kapua/model/query/KapuaListResult.java
  service/api/src/main/java/org/eclipse/kapua/model/query/KapuaQuery.java
Labels: Console GWT, enhancement, rest-api

#2827 fix broker metrics names
  broker-core/src/main/java/org/eclipse/kapua/broker/core/converter/AbstractKapuaConverter.java
  broker-core/src/main/java/org/eclipse/kapua/broker/core/listener/DeviceManagementNotificationMessageProcessor.java
  broker-core/src/main/java/org/eclipse/kapua/broker/core/plugin/authentication/UserAuthenticationLogic.java
  broker-core/src/main/java/org/eclipse/kapua/broker/core/plugin/metric/LoginMetric.java
  commons/src/main/java/org/eclipse/kapua/commons/event/RaiseServiceEventInterceptor.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MessageStoreFacade.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MessageStoreServiceImpl.java
Labels: bug

#2831 Upgraded Jose4j version from 0.5.2 to 0.7.0 - CWE-200
  pom.xml
Labels: CQ approved, Security, enhancement

#2837 Upgraded commons-fileupload version from 1.3.2 to 1.4 - CVE-2016-1000031 - CWE-284
  pom.xml
Labels: CQ approved, Security, enhancement
