Repository eclipse-kapua/kapua, pull requests merged in 2020-08, with the labels that each got.

#2875 Initial support for MatchPredicates in Device REST API
  commons/src/main/java/org/eclipse/kapua/commons/model/query/predicate/AbstractMatchPredicate.java
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/ServiceDAO.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Devices.java
  rest-api/resources/src/main/resources/openapi/device/device-scopeId.yaml
  service/api/src/main/java/org/eclipse/kapua/model/query/predicate/AttributePredicate.java
  service/api/src/main/java/org/eclipse/kapua/model/query/predicate/MatchPredicate.java
  service/device/registry/api/src/main/java/org/eclipse/kapua/service/device/registry/DeviceAttributes.java
  service/device/registry/api/src/main/java/org/eclipse/kapua/service/device/registry/DeviceMatchPredicate.java
  service/device/registry/api/src/main/java/org/eclipse/kapua/service/device/registry/DeviceQuery.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/internal/DeviceQueryImpl.java
  service/device/registry/internal/src/main/resources/META-INF/persistence.xml
  service/device/registry/internal/src/main/resources/liquibase/1.2.0/changelog-device-1.2.0.xml
  service/device/registry/internal/src/main/resources/liquibase/1.3.0/changelog-device-1.3.0.xml
  service/device/registry/internal/src/main/resources/liquibase/1.3.0/device-match-indexes.xml
Labels: enhancement, rest-api

#3030 Eclipselink 2.7.7
  assembly/api/pom.xml
  assembly/broker/descriptors/kapua-broker.xml
  assembly/broker/pom.xml
  assembly/console/pom.xml
  commons/pom.xml
  commons/src/main/java/org/eclipse/persistence/logging/slf4j/LogCategory.java
  commons/src/main/java/org/eclipse/persistence/logging/slf4j/LogLevel.java
  commons/src/main/java/org/eclipse/persistence/logging/slf4j/SLF4JLogger.java
  commons/src/main/java/org/eclipse/persistence/logging/slf4j/package-info.java
  commons/src/test/java/org/eclipse/kapua/commons/util/xml/XmlUtilTest.java
  pom.xml
Labels: enhancement

#3042 Fix ide-page grammatical errors
  docs/developer-guide/en/ide.md
Labels: documentation

#3043 Fix running-page grammatical errors
  docs/developer-guide/en/running.md
Labels: documentation

#3045 Fix sso doc grammatical errors
  docs/developer-guide/en/sso.md
Labels: documentation

#3059 Fix simulator doc grammatical errors
  docs/user-manual/en/simulator.md
Labels: documentation

#3058 Fix permissions doc grammatical errors
  docs/user-manual/en/Permissions.md
Labels: documentation

#3050 Fix kura-kapua docs grammatical errors
  docs/kuraKapuaDocs.md
Labels: documentation

#3040 Restore Path annotation in DeviceManagementOperations REST APIs
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceManagementOperationNotifications.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceManagementOperations.java
Labels: Bug, rest-api
