Repository eclipse-kapua/kapua, pull requests merged in 2020-04, with the labels that each got.

#2925 Remove db password print while log level set to DEBUG
  commons/src/main/java/org/eclipse/kapua/commons/liquibase/KapuaLiquibaseClient.java
  console/web/src/main/java/org/eclipse/kapua/app/console/server/util/ConsoleListener.java
  rest-api/web/src/main/java/org/eclipse/kapua/app/api/web/RestApiListener.java
Labels: bug

#2926 Fixed notification processing update retry strategy
  service/device/management/registry/api/src/main/java/org/eclipse/kapua/service/device/management/registry/manager/DeviceManagementRegistryManagerService.java
Labels: bug

#2929 Added PackageDownloadRequest download restart option
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/packages/dialog/PackageInstallDialog.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/server/GwtDeviceManagementServiceImpl.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/shared/model/device/management/packages/GwtPackageInstallRequest.java
  console/module/device/src/main/resources/org/eclipse/kapua/app/console/module/device/client/messages/ConsoleDeviceMessages.properties
  service/device/call/kura/src/main/java/org/eclipse/kapua/service/device/call/kura/app/PackageMetrics.java
  service/device/management/packages/api/src/main/java/org/eclipse/kapua/service/device/management/packages/model/download/AdvancedPackageDownloadOptions.java
  service/device/management/packages/internal/src/main/java/org/eclipse/kapua/service/device/management/packages/internal/DevicePackageManagementServiceImpl.java
  service/device/management/packages/internal/src/main/java/org/eclipse/kapua/service/device/management/packages/message/internal/PackageAppProperties.java
  service/device/management/packages/internal/src/main/java/org/eclipse/kapua/service/device/management/packages/message/internal/PackageRequestPayload.java
  service/device/management/packages/internal/src/main/java/org/eclipse/kapua/service/device/management/packages/model/download/internal/AdvancedPackageDownloadOptionsImpl.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kapua/kura/TranslatorAppPackageKapuaKura.java
Labels: enhancement

#2924 fix event bus instance leak
  commons/src/main/java/org/eclipse/kapua/commons/event/ServiceInspector.java
  commons/src/main/java/org/eclipse/kapua/commons/event/jms/JMSServiceEventBus.java
  qa/common/src/main/java/org/eclipse/kapua/qa/common/utils/EmbeddedEventBroker.java
Labels: bug

#2932 Fixed javadoc
  service/device/management/packages/api/src/main/java/org/eclipse/kapua/service/device/management/packages/model/download/AdvancedPackageDownloadOptions.java
  service/device/management/packages/internal/src/main/java/org/eclipse/kapua/service/device/management/packages/message/internal/PackageRequestPayload.java
Labels: Bug, documentation

#2936 External ES mount
  deployment/docker/compose/extras/docker-compose.broker-debug.yml
  deployment/docker/compose/extras/docker-compose.es-storage-dir.yml
  deployment/docker/unix/docker-deploy.sh
  deployment/docker/unix/docker-logs.sh
  deployment/docker/unix/docker-undeploy.sh
  deployment/docker/win/docker-deploy.ps1
Labels: enhancement

#2937 Added JUnit tests for ValueTokenizer class
  commons/src/test/java/org/eclipse/kapua/commons/configuration/ValueTokenizerTest.java
Labels: Test

#2930 ServiceDAO findByField improvements
  commons/src/main/java/org/eclipse/kapua/commons/configuration/ServiceConfigDAO.java
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/ServiceDAO.java
  console/module/authorization/src/main/java/org/eclipse/kapua/app/console/module/authorization/server/GwtDomainRegistryServiceImpl.java
  service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountDAO.java
  service/device/management/job/internal/src/main/java/org/eclipse/kapua/service/device/management/job/scheduler/internal/JobDeviceManagementTriggerManagerServiceImpl.java
  service/job/api/src/main/java/org/eclipse/kapua/service/job/step/definition/JobStepDefinitionService.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/execution/internal/JobExecutionDAO.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/internal/JobDAO.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/step/definition/internal/JobStepDefinitionDAO.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/step/definition/internal/JobStepDefinitionServiceImpl.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/step/internal/JobStepDAO.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/targets/internal/JobTargetDAO.java
  service/job/test-steps/src/main/java/org/eclipse/kapua/service/job/steps/JobServiceSteps.java
  service/scheduler/api/src/main/java/org/eclipse/kapua/service/scheduler/trigger/definition/TriggerDefinitionService.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/definition/quartz/TriggerDefinitionDAO.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/definition/quartz/TriggerDefinitionServiceImpl.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/quartz/TriggerServiceImpl.java
  service/security/authorization/api/src/main/java/org/eclipse/kapua/service/authorization/domain/DomainRegistryService.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/token/shiro/AccessTokenDAO.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/domain/shiro/DomainDAO.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/domain/shiro/DomainRegistryServiceImpl.java
  service/security/test-steps/src/main/java/org/eclipse/kapua/service/authorization/steps/AuthorizationServiceSteps.java
  service/user/api/src/main/java/org/eclipse/kapua/service/user/UserAttributes.java
  service/user/internal/src/main/java/org/eclipse/kapua/service/user/internal/UserDAO.java
  service/user/test-steps/src/main/java/org/eclipse/kapua/service/user/steps/UserServiceSteps.java
Labels: enhancement

#2938 Add missing permissiong check on UserServiceImpl
  service/user/internal/src/main/java/org/eclipse/kapua/service/user/internal/UserServiceImpl.java
Labels: Bug

#2940 Added Junit Tests for PropertiesUtils
  commons/src/test/java/org/eclipse/kapua/commons/util/PropertiesUtilsTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/StringUtilTest.java
Labels: Test

#2943 Added JUnit tests for SystemUtils class
  commons/src/test/java/org/eclipse/kapua/commons/util/SystemUtilsTest.java
Labels: Test

#2944 Fixed test for KapuaDelayUtil class
  commons/src/test/java/org/eclipse/kapua/commons/util/KapuaDelayUtilTest.java
Labels: Test

#2946 Added Junit Tests for SemanticVersion
  commons/src/test/java/org/eclipse/kapua/commons/util/SemanticVersionTest.java
Labels: Test

#2941 Added unit tests for translator part1
  translator/pom.xml
  translator/test-steps/about.html
  translator/test-steps/pom.xml
  translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/ExampleTranslator.java
  translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
  translator/test/about.html
  translator/test/pom.xml
  translator/test/src/test/java/org/eclipse/kapua/translator/test/CucumberWithPropertiesForTranslator.java
  translator/test/src/test/java/org/eclipse/kapua/translator/test/RunTranslatorUnitTest.java
  translator/test/src/test/resources/features/TranslatorUnitTests.feature
Labels: Test

#2951 Disable auto scroll in timestamp refresh
  console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/client/ui/grid/KapuaTreeGrid.java
  console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/client/ui/grid/KapuaTreeGridView.java
  console/module/data/src/main/java/org/eclipse/kapua/app/console/module/data/client/TopicsTable.java
Labels: Console GWT, enhancement

#2953 Fix swagger-cli version
  assembly/api/pom.xml
Labels: Build and test, Dependencies

#2625 Upgraded Liquibase Core version to 3.6.3
  pom.xml
Labels: CQ approved, Liquibase, enhancement
