Repository eclipse-kapua/kapua, pull requests merged in 2020-05, with the labels that each got.

#2960 Fixed input parameters definition for device/packages/_download
  rest-api/resources/src/main/resources/openapi/devicePackage/devicePackage-scopeId-deviceId-_download.yaml
  rest-api/resources/src/main/resources/openapi/devicePackage/devicePackage.yaml
Labels: documentation, rest-api

#2961 Fixed Failing Cucumber Unit Tests
  service/job/test/pom.xml
  service/job/test/src/test/java/org/eclipse/kapua/service/job/test/CucumberWithPropertiesForJob.java
  service/scheduler/test/pom.xml
  service/scheduler/test/src/test/java/org/eclipse/kapua/service/scheduler/test/CucumberWithPropertiesForScheduler.java
  service/tag/test/pom.xml
  service/tag/test/src/test/java/org/eclipse/kapua/service/tag/test/CucumberWithPropertiesForTag.java
  service/user/test/pom.xml
  service/user/test/src/test/java/org/eclipse/kapua/service/user/test/CucumberWithPropertiesForUser.java
Labels: Test, enhancement

#2964 Remove duplicated dependencies on kapua-qa-integration
  qa/integration/pom.xml
Labels: enhancement

#2966 Fix ssoException in broker docker container
  assembly/broker/pom.xml
  broker/core/src/main/resources/shiro.ini
Labels: Bug

#2967 javadoc minor fixes
  commons/src/main/java/org/eclipse/kapua/commons/jpa/EntityManagerVoidCallback.java
  sso/api/src/main/java/org/eclipse/kapua/sso/SingleSignOnService.java
Labels: Bug, documentation

#2954 Prevent users to change settings on their account
  commons/src/main/java/org/eclipse/kapua/commons/configuration/AbstractKapuaConfigurableService.java
  service/account/test/src/test/resources/features/AccountService.feature
Labels: Bug

#2947 Restrictable Service Configurations
  commons/src/main/java/org/eclipse/kapua/commons/configuration/AbstractKapuaConfigurableResourceLimitedService.java
  commons/src/main/java/org/eclipse/kapua/commons/configuration/AbstractKapuaConfigurableService.java
  commons/src/main/java/org/eclipse/kapua/commons/configuration/KapuaConfigurationErrorCodes.java
  commons/src/main/java/org/eclipse/kapua/commons/configuration/metatype/EmptyTocd.java
  commons/src/main/java/org/eclipse/kapua/commons/configuration/metatype/TocdImpl.java
  commons/src/main/resources/kapua-configuration-service-error-messages.properties
  console/module/api/src/main/resources/org/eclipse/kapua/app/console/module/api/client/messages/ValidationMessages.properties
  service/api/src/main/java/org/eclipse/kapua/model/config/metatype/KapuaTocd.java
Labels: Waitfor/Test, enhancement

#2970 Fixed failed redirect with sso logout
  console/core/src/main/java/org/eclipse/kapua/app/console/core/client/KapuaCloudConsole.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/client/NorthView.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/client/util/TokenCleaner.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/server/GwtAuthorizationServiceImpl.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/server/GwtSettingsServiceImpl.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/servlet/SsoCallbackServlet.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/shared/model/authentication/GwtJwtIdToken.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/shared/service/GwtAuthorizationService.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/shared/service/GwtSettingsService.java
  console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/shared/model/session/GwtSession.java
  docs/developer-guide/en/sso.md
Labels: Bug, Console GWT

#2963 disabling datastore feature parameter
  assembly/broker/configurations/camel-routes.xml
  assembly/broker/configurations/camel.xml
  assembly/broker/entrypoint/run-broker
  assembly/console/docker/Dockerfile
  commons/src/main/java/org/eclipse/kapua/commons/configuration/AbstractKapuaConfigurableService.java
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/AbstractKapuaService.java
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/KapuaServiceDisabledException.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/server/GwtAuthorizationServiceImpl.java
  console/module/account/src/main/java/org/eclipse/kapua/app/console/module/account/server/GwtAccountServiceImpl.java
  console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/shared/model/session/GwtSession.java
  console/module/data/src/main/java/org/eclipse/kapua/app/console/module/data/client/DataViewDescriptor.java
  deployment/docker/compose/docker-compose.yml
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/exception/KapuaServiceDisabledExceptionMapper.java
  service/api/src/main/java/org/eclipse/kapua/KapuaErrorCodes.java
  service/api/src/main/resources/kapua-service-error-messages.properties
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ChannelInfoRegistryServiceImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ClientInfoRegistryServiceImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MessageStoreServiceImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MetricInfoRegistryServiceImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/setting/DatastoreSettingKey.java
Labels: enhancement

#2969 datastore driver - adding reconnect to datastore capabilities
  qa/integration/src/test/resources/kapua-datastore-rest-client-setting.properties
  service/datastore/client-api/src/main/java/org/eclipse/kapua/service/datastore/client/AbstractDatastoreClient.java
  service/datastore/client-api/src/main/java/org/eclipse/kapua/service/datastore/client/DatastoreClient.java
  service/datastore/client-rest/src/main/java/org/eclipse/kapua/service/datastore/client/rest/ClientSettingsKey.java
  service/datastore/client-rest/src/main/java/org/eclipse/kapua/service/datastore/client/rest/EsRestClientProvider.java
  service/datastore/client-rest/src/main/java/org/eclipse/kapua/service/datastore/client/rest/RestDatastoreClient.java
  service/datastore/client-rest/src/main/resources/kapua-datastore-rest-client-setting.properties
  service/datastore/client-transport/src/main/java/org/eclipse/kapua/service/datastore/client/transport/EsTransportClientProvider.java
  service/datastore/client-transport/src/main/java/org/eclipse/kapua/service/datastore/client/transport/TransportDatastoreClient.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MessageStoreFacade.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/client/DatastoreClientFactory.java
Labels: enhancement

#2974 Fixed javadoc
  service/datastore/client-rest/src/main/java/org/eclipse/kapua/service/datastore/client/rest/EsRestClientProvider.java
Labels: Bug, build, documentation

#2976 Added Junit Tests for ResourceUtils
  commons/src/test/java/org/eclipse/kapua/commons/util/ResourceUtilsTest.java
Labels: Test

#2977 Added JUnit tests for Commons package
  commons/src/main/java/org/eclipse/kapua/commons/util/KapuaFileUtils.java
  commons/src/test/java/org/eclipse/kapua/commons/util/ArgumentValidatorTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/CommonsValidationRegexTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/KapuaFileUtilsTest.java
Labels: Test

#2979 Added JUnit tests for Metatype package - part1
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/EmptyTocdTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/TadImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/TattributeImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/TdesignateImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/TiconImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/ToptionImplTest.java
Labels: Test

#2980 Added JUnit tests for Metatype package - part2
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/TmetadataImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/TobjectImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/TocdImplTest.java
Labels: Test

#2981 Sort order parameter for data messages request
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DataMessages.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DataMessagesJson.java
  rest-api/resources/src/main/resources/openapi/dataMessage/dataMessage-scopeId.yaml
  service/datastore/api/src/main/java/org/eclipse/kapua/service/datastore/model/query/SortDirection.java
Labels: enhancement

#2983 Remote shiro.ini from kapua-qa-common
  qa/common/src/main/resources/shiro.ini
  qa/integration/src/test/resources/shiro.ini
Labels: Test, enhancement

#2985 Minor fixes in README docs concerning sso
  assembly/README.md
  deployment/docker/README.md
  deployment/minishift/sso/README.md
  deployment/openshift/sso/README.md
Labels: documentation
