Repository eclipse-kapua/kapua, pull requests merged in 2020-07, with the labels that each got.

#3009 Removed unnecessary dependencies of netty-all
  assembly/broker/pom.xml
  broker/core/pom.xml
  commons/pom.xml
Labels: enhancement

#3011 Cache manager review the cache instantiation process
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/cache/KapuaCacheManager.java
Labels: Bug

#3010 Increased length limit for Device Configuration Tab TextField and TextArea
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/configuration/DeviceConfigPanel.java
Labels: Bug, Console GWT

#3004 Disable datastore for REST API
  assembly/api/docker/Dockerfile
Labels: Bug

#3019 Force EclipseLink JaxbContextFactory
  assembly/api/docker/Dockerfile
Labels: Bug

#3022 Use index to search for AccessTokens
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/token/AccessTokenAttributes.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/AuthenticationServiceShiroImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/AccessTokenAuthenticatingRealm.java
  service/security/shiro/src/main/resources/liquibase/1.3.0/atht-access_token-expires_index.xml
  service/security/shiro/src/main/resources/liquibase/1.3.0/changelog-authentication-1.3.0.xml
  service/security/shiro/src/main/resources/liquibase/changelog-authentication-master.xml
Labels: enhancement

#3026 Remove REST Error Pages and /test resource reference
  rest-api/web/src/main/resources/shiro.ini
  rest-api/web/src/main/webapp/WEB-INF/web.xml
  rest-api/web/src/main/webapp/errorPages/400.html
  rest-api/web/src/main/webapp/errorPages/401.html
  rest-api/web/src/main/webapp/errorPages/403.html
  rest-api/web/src/main/webapp/errorPages/404.html
  rest-api/web/src/main/webapp/errorPages/405.html
  rest-api/web/src/main/webapp/errorPages/500.html
  rest-api/web/src/main/webapp/errorPages/error.jsp
Labels: enhancement, rest-api

#3028 Fix Permission import on REST JaxbContext
  rest-api/web/src/main/java/org/eclipse/kapua/app/api/web/JaxbContextResolver.java
Labels: Bug, rest-api

#3027 Proposal for patching SonarQube rule 3032
  commons/src/main/java/org/eclipse/kapua/commons/jpa/ResourceSqlScriptExecutor.java
Labels: enhancement
