Repository eclipse-kapua/kapua, pull requests merged in 2020-12, with the labels that each got.

#3156 JobExecutionService should not be configurable
  qa/integration/src/test/resources/features/job/JobExecutionServiceI9n.feature
  service/job/api/src/main/java/org/eclipse/kapua/service/job/execution/JobExecutionService.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/execution/internal/JobExecutionServiceImpl.java
  service/job/test-steps/src/main/java/org/eclipse/kapua/service/job/steps/JobServiceSteps.java
Labels: Enhancement

#3157 Fix ES6 Migration Tool data index mapping name and Refresh before Reindex
  extras/es-migrator/src/main/java/org/eclipse/kapua/extras/esmigrator/Migrator.java
Labels: Bug

#3169 More services should not be configurable
  commons/src/test/java/org/eclipse/kapua/commons/model/misc/CollisionEntityService.java
  commons/src/test/java/org/eclipse/kapua/commons/model/misc/CollisionServiceImpl.java
  job-engine/api/src/main/java/org/eclipse/kapua/job/engine/queue/QueuedJobExecutionService.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/queue/jbatch/QueuedJobExecutionServiceImpl.java
  qa/integration/src/test/resources/features/job/JobStepServiceI9n.feature
  qa/integration/src/test/resources/features/job/JobTargetsServiceI9n.feature
  service/device/management/job/internal/src/main/java/org/eclipse/kapua/service/device/management/job/internal/JobDeviceManagementOperationServiceImpl.java
  service/endpoint/internal/src/main/java/org/eclipse/kapua/service/endpoint/internal/EndpointInfoServiceImpl.java
  service/job/api/src/main/java/org/eclipse/kapua/service/job/step/JobStepService.java
  service/job/api/src/main/java/org/eclipse/kapua/service/job/step/definition/JobStepDefinitionService.java
  service/job/api/src/main/java/org/eclipse/kapua/service/job/targets/JobTargetService.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/step/definition/internal/JobStepDefinitionServiceImpl.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/step/internal/JobStepServiceImpl.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/targets/internal/JobTargetServiceImpl.java
  service/job/test-steps/src/main/java/org/eclipse/kapua/service/job/steps/JobServiceSteps.java
  service/scheduler/api/src/main/java/org/eclipse/kapua/service/scheduler/trigger/TriggerService.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/quartz/TriggerServiceImpl.java
Labels: Enhancement

#3150 Added JUnit tests for client/gateway/spi module
  client/gateway/spi/pom.xml
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/DefaultApplicationTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/DefaultClientTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/DefaultDataTest.java
Labels: Test

#3175 QA trigger end date changed to avoid TriggerNeverFiresException
  qa/integration/src/test/resources/features/jobScheduling/TriggerServiceI9n.feature
Labels: Bug, Test

#3178 Added index on DeviceConnection table
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/connection/internal/DeviceConnectionServiceImpl.java
  service/device/registry/internal/src/main/resources/liquibase/1.4.0/changelog-device-1.4.0.xml
  service/device/registry/internal/src/main/resources/liquibase/1.4.0/device_connection-create_index_id.xml
  service/device/registry/internal/src/main/resources/liquibase/changelog-device-master.xml
Labels: Enhancement

#3184 Forced Netty3 version to 3.10.6.Final
  pom.xml
Labels: Dependencies
