Repository eclipse-kapua/kapua, pull requests merged in 2020-06, with the labels that each got.

#2998 Added options to keep staging repository in case of error
  pom.xml
Labels: build, enhancement

#2997 Added unit tests for ValueTokenizer class
  commons/src/test/java/org/eclipse/kapua/commons/configuration/ValueTokenizerTest.java
Labels: Test

#2996 Enabling property to disable the OpenID Connect logout
  console/core/src/main/java/org/eclipse/kapua/app/console/core/client/KapuaCloudConsole.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/client/NorthView.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/server/GwtSettingsServiceImpl.java
  console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/setting/ConsoleSettingKeys.java
  docs/developer-guide/en/sso.md
Labels: enhancement

#3000 Add Scope ID to isServiceEnabled() and isPropertyEnabled()
  commons/src/main/java/org/eclipse/kapua/commons/configuration/AbstractKapuaConfigurableService.java
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/AbstractKapuaService.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ChannelInfoRegistryServiceImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ClientInfoRegistryServiceImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MessageStoreServiceImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MetricInfoRegistryServiceImpl.java
Labels: enhancement

#3006 Bump netty4 version from 4.1.34.Final to 4.1.50.Final - CVE-2019-16869 - CWE-113
  commons/pom.xml
  pom.xml
Labels: CQ approved, Security
