Repository eclipse-kapua/kapua, pull requests merged in 2020-03, with the labels that each got.

#2861 Move Console MainViewDescriptors from src to resources
  console/module/about/src/main/resources/META-INF/services/org.eclipse.kapua.app.console.module.api.client.ui.view.descriptor.MainViewDescriptor
  console/module/account/src/main/resources/META-INF/services/org.eclipse.kapua.app.console.module.api.client.ui.view.descriptor.MainViewDescriptor
  console/module/authorization/src/main/resources/META-INF/services/org.eclipse.kapua.app.console.module.api.client.ui.view.descriptor.MainViewDescriptor
  console/module/data/src/main/resources/META-INF/services/org.eclipse.kapua.app.console.module.api.client.ui.view.descriptor.MainViewDescriptor
  console/module/device/src/main/resources/META-INF/services/org.eclipse.kapua.app.console.module.api.client.ui.view.descriptor.MainViewDescriptor
  console/module/endpoint/src/main/resources/META-INF/services/org.eclipse.kapua.app.console.module.api.client.ui.view.descriptor.MainViewDescriptor
  console/module/job/src/main/resources/META-INF/services/org.eclipse.kapua.app.console.module.api.client.ui.view.descriptor.MainViewDescriptor
  console/module/tag/src/main/resources/META-INF/services/org.eclipse.kapua.app.console.module.api.client.ui.view.descriptor.MainViewDescriptor
  console/module/user/src/main/resources/META-INF/services/org.eclipse.kapua.app.console.module.api.client.ui.view.descriptor.MainViewDescriptor
  console/module/welcome/src/main/resources/META-INF/services/org.eclipse.kapua.app.console.module.api.client.ui.view.descriptor.MainViewDescriptor
Labels: enhancement

#2877 Correctly map ParamException in REST API
  commons/src/main/java/org/eclipse/kapua/commons/util/KapuaExceptionUtils.java
  rest-api/core/pom.xml
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/exception/ParamExceptionMapper.java
  rest-api/pom.xml
  service/device/registry/api/src/main/java/org/eclipse/kapua/service/device/registry/connection/DeviceConnectionStatus.java
Labels: bug, rest-api

#2878 Add askTotalCount to Devices simpleQuery
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Devices.java
  rest-api/resources/src/main/resources/openapi/device/device-scopeId.yaml
  rest-api/resources/src/main/resources/openapi/openapi.yaml
Labels: enhancement, rest-api

#2882 Added tests for Tag service
  qa/integration/src/test/java/org/eclipse/kapua/integration/service/tag/RunTagServiceI9nTest.java
  qa/integration/src/test/resources/features/tag/TagService.feature
  qa/integration/src/test/resources/features/user/UserPermissionI9n.feature
  qa/integration/src/test/resources/features/user/UserRoleServiceI9n.feature
  service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
  service/tag/test-steps/src/main/java/org/eclipse/kapua/service/tag/steps/TagServiceSteps.java
  service/tag/test/src/test/resources/features/TagService.feature
Labels: Test

#2885 DeviceManagementOperationService.findByOperationId feature
  service/device/commons/src/main/java/org/eclipse/kapua/service/device/management/commons/AbstractDeviceManagementServiceImpl.java
  service/device/management/job/internal/src/main/java/org/eclipse/kapua/service/device/management/job/manager/internal/JobDeviceManagementOperationManagerServiceImpl.java
  service/device/management/registry/api/src/main/java/org/eclipse/kapua/service/device/management/registry/manager/DeviceManagementRegistryManagerService.java
  service/device/management/registry/api/src/main/java/org/eclipse/kapua/service/device/management/registry/operation/DeviceManagementOperationRegistryService.java
  service/device/management/registry/internal/src/main/java/org/eclipse/kapua/service/device/management/registry/operation/internal/DeviceManagementOperationRegistryServiceImpl.java
Labels: enhancement

#2883 Transport module improvements
  commons/src/main/java/org/eclipse/kapua/commons/model/id/IdGenerator.java
  commons/src/main/java/org/eclipse/kapua/commons/util/RandomUtils.java
  commons/src/test/java/org/eclipse/kapua/commons/model/KapuaEidTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/ArgumentValidatorTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/CryptoUtilTest.java
  qa/common/src/main/java/org/eclipse/kapua/qa/common/TestBase.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/service/datastoreJunit/AbstractMessageStoreServiceTest.java
  service/datastore/client-rest/src/main/java/org/eclipse/kapua/service/datastore/client/rest/RestDatastoreClient.java
  service/device/api/pom.xml
  service/device/api/src/main/java/org/eclipse/kapua/service/device/management/message/KapuaMethod.java
  service/device/call/api/pom.xml
  service/device/call/api/src/main/java/org/eclipse/kapua/service/device/call/DeviceCall.java
  service/device/call/kura/src/main/java/org/eclipse/kapua/service/device/call/kura/KuraDeviceCallImpl.java
  service/device/commons/src/main/java/org/eclipse/kapua/service/device/management/commons/AbstractDeviceManagementServiceImpl.java
  service/device/commons/src/main/java/org/eclipse/kapua/service/device/management/commons/call/DeviceCallExecutor.java
  service/device/management/packages/internal/src/main/java/org/eclipse/kapua/service/device/management/packages/internal/DevicePackageManagementServiceImpl.java
  service/device/management/registry/internal/src/main/java/org/eclipse/kapua/service/device/management/registry/operation/internal/DeviceManagementOperationCreatorImpl.java
  service/device/management/registry/internal/src/main/java/org/eclipse/kapua/service/device/management/registry/operation/internal/DeviceManagementOperationImpl.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/event/internal/DeviceEventCreatorImpl.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/event/internal/DeviceEventImpl.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kapua/kura/MethodDictionaryKapuaKura.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/MethodDictionaryKuraKapua.java
  transport/api/src/main/java/org/eclipse/kapua/transport/TransportClientFactory.java
  transport/api/src/main/java/org/eclipse/kapua/transport/TransportFacade.java
  transport/api/src/main/java/org/eclipse/kapua/transport/exception/TransportClientGetException.java
  transport/api/src/main/java/org/eclipse/kapua/transport/exception/TransportErrorCodes.java
  transport/api/src/main/java/org/eclipse/kapua/transport/utils/ClientIdGenerator.java
  transport/api/src/main/resources/transport-client-error-messages.properties
  transport/jms/pom.xml
  transport/jms/src/main/java/org/eclipse/kapua/transport/jms/setting/JmsClientSetting.java
  transport/jms/src/main/java/org/eclipse/kapua/transport/jms/setting/JmsClientSettingKeys.java
  transport/jms/src/main/java/org/eclipse/kapua/transport/message/jms/JmsMessage.java
  transport/jms/src/main/java/org/eclipse/kapua/transport/message/jms/JmsPayload.java
  transport/jms/src/main/java/org/eclipse/kapua/transport/message/jms/JmsTopic.java
  transport/jms/src/main/resources/jms-client-setting.properties
  transport/mqtt/pom.xml
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/message/mqtt/MqttMessage.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/message/mqtt/MqttPayload.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/message/mqtt/MqttTopic.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/MqttClient.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/MqttClientFactoryImpl.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/MqttFacade.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/MqttResponseCallback.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/exception/MqttClientAlreadyConnectedException.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/exception/MqttClientCallbackSetException.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/exception/MqttClientCleanException.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/exception/MqttClientConnectException.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/exception/MqttClientDisconnectException.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/exception/MqttClientErrorCodes.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/exception/MqttClientException.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/exception/MqttClientNotConnectedException.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/exception/MqttClientPublishException.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/exception/MqttClientSubscribeException.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/exception/MqttClientTerminateException.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/exception/MqttClientUnsubscribeException.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/pooling/MqttClientPool.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/pooling/PooledMqttClientFactory.java
  transport/mqtt/src/main/resources/mqtt-client-error-messages.properties
Labels: enhancement

#2879 Added tests for Device service
  qa/integration/src/test/resources/features/device/DeviceServiceI9n.feature
  qa/integration/src/test/resources/features/user/UserRoleServiceI9n.feature
  service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
Labels: Test

#2887 Updated docker-deploy.sh instructions on README
  README.md
Labels: documentation

#2808 Added Tests For Endpoint Service
  qa/integration/src/test/resources/features/endpoint/EndpointServiceI9n.feature
Labels: CQ approved, Test

#2809 Added tests for Group service
  qa/integration/src/test/java/org/eclipse/kapua/integration/service/authorization/RunAuthorizationServiceI9nTest.java
  qa/integration/src/test/resources/features/authorization/GroupService.feature
  qa/integration/src/test/resources/features/user/UserPermissionI9n.feature
  qa/integration/src/test/resources/features/user/UserRoleServiceI9n.feature
  service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
  service/security/test-steps/src/main/java/org/eclipse/kapua/service/authorization/steps/AuthorizationServiceSteps.java
Labels: CQ approved, Test

#2818 Added tests for Device service
  qa/integration/src/test/resources/features/device/DeviceServiceI9n.feature
Labels: CQ approved, Test

#2815 Added tests for Tag service
  qa/integration/src/test/resources/features/tag/TagService.feature
Labels: CQ approved, Test

#2864 Added Integration Tests For Accounts
  qa/integration/src/test/resources/features/account/AccountCredentialService.feature
  qa/integration/src/test/resources/features/account/AccountDeviceRegistryService.feature
  qa/integration/src/test/resources/features/account/AccountService.feature
  qa/integration/src/test/resources/features/account/AccountTagService.feature
Labels: Test

#2891 Sorting in Devices REST simpleQuery
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/ServiceDAO.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Devices.java
  rest-api/resources/src/main/resources/openapi/device/device-scopeId.yaml
  rest-api/resources/src/main/resources/openapi/openapi.yaml
  service/api/src/main/java/org/eclipse/kapua/model/query/SortOrder.java
Labels: enhancement, rest-api

#2890 Fixed javadoc
  transport/api/src/main/java/org/eclipse/kapua/transport/TransportClientFactory.java
  transport/api/src/main/java/org/eclipse/kapua/transport/exception/TransportClientGetException.java
  transport/api/src/main/java/org/eclipse/kapua/transport/exception/TransportException.java
Labels: bug

#2893 Add NPM scope to swagger-cli
  assembly/api/pom.xml
Labels: bug, dependencies

#2894 Fixed SemanticVersioning utility class and added jUnit test
  commons/src/main/java/org/eclipse/kapua/commons/util/SemanticVersion.java
  commons/src/test/java/org/eclipse/kapua/commons/util/SemanticVersionTest.java
Labels: bug

#2899 Relax Email validation RegEx for new domains
  commons/src/main/java/org/eclipse/kapua/commons/util/CommonsValidationRegex.java
  commons/src/test/java/org/eclipse/kapua/commons/util/ArgumentValidatorTest.java
  console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/client/util/validator/TextFieldValidator.java
  console/module/api/src/main/resources/org/eclipse/kapua/app/console/module/api/client/messages/ValidationMessages.properties
  qa/integration/src/test/resources/features/account/AccountService.feature
Labels: bug

#2900 Fixed exception messages missing the positional argument number
  service/device/management/job/api/src/main/resources/job-device-management-trigger-service-error-messages.properties
  service/scheduler/quartz/src/main/resources/quartz-trigger-driver-error-messages.properties
Labels: bug

#2902 Restored old method in KapuaLiquibaseClient
  commons/src/main/java/org/eclipse/kapua/commons/liquibase/KapuaLiquibaseClient.java
Labels: bug

#2854 Fix job engine performance on high load
  commons/src/main/java/org/eclipse/kapua/commons/jpa/EntityManager.java
  dev-tools/vagrant/Vagrantfile
  job-engine/api/src/main/java/org/eclipse/kapua/job/engine/queue/QueuedJobExecutionStatus.java
  job-engine/extra/remote/src/main/java/org/eclipse/kapua/job/engine/remote/JobEngineServiceRemote.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/JobEngineServiceJbatch.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/driver/JbatchDriver.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/listener/QueuedJobExecutionCheckTask.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/JPAPersistenceManagerImpl.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/JbatchEntityManagerFactory.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/KapuaJDBCPersistenceManagerImpl.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/AbstractJpaJbatchEntity.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaCheckpointData.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaCheckpointDataDAO.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaExecutionInstanceData.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaExecutionInstanceDataDAO.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaExecutionInstanceDataFields.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaJobInstanceData.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaJobInstanceDataDAO.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaJobStatus.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaJobStatusDAO.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaStepExecutionInstanceData.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaStepExecutionInstanceDataDAO.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaStepStatus.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaStepStatusDAO.java
  job-engine/jbatch/src/main/resources/META-INF/persistence.xml
  job-engine/jbatch/src/main/resources/META-INF/services/batch-services.properties
  job-engine/jbatch/src/main/resources/kapua-job-engine-setting.properties
  job-engine/jbatch/src/main/resources/liquibase/1.2.0/changelog-job-engine-1.2.0.xml
  job-engine/jbatch/src/main/resources/liquibase/1.2.0/checkpoint_data-add_column_jobinstanceid.xml
  job-engine/jbatch/src/main/resources/liquibase/1.2.0/job_engine_jbatch-rename_tables.xml
  service/device/management/job/internal/src/main/java/org/eclipse/kapua/service/device/management/job/manager/internal/JobDeviceManagementOperationManagerServiceImpl.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/quartz/driver/QuartzTriggerDriver.java
Labels: enhancement

#2908 Fix Javadoc
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceManagementRequestsJson.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/StreamsJson.java
Labels: documentation, rest-api

#2914 Fix Liquibase foreign keys definition for ON DETELE CASCADE
  extras/foreignkeys/src/main/resources/liquibase/1.2.0/account-foreignkey_delete_cascade.xml
  extras/foreignkeys/src/main/resources/liquibase/1.2.0/atht_access_token-foreignkey_delete_cascade.xml
  extras/foreignkeys/src/main/resources/liquibase/1.2.0/atht_credential-foreignkey_delete_cascade.xml
  extras/foreignkeys/src/main/resources/liquibase/1.2.0/athz_access_info-foreignkey_delete_cascade.xml
  extras/foreignkeys/src/main/resources/liquibase/1.2.0/athz_group-foreignkey_delete_cascade.xml
  extras/foreignkeys/src/main/resources/liquibase/1.2.0/athz_role-foreignkey_delete_cascade.xml
  extras/foreignkeys/src/main/resources/liquibase/1.2.0/changelog-foreignkeys-1.2.0.xml
  extras/foreignkeys/src/main/resources/liquibase/1.2.0/device-connection-foreignkey_delete_cascade.xml
  extras/foreignkeys/src/main/resources/liquibase/1.2.0/device-foreignkey_delete_cascade.xml
  extras/foreignkeys/src/main/resources/liquibase/1.2.0/device-tag-foreignkey_delete_cascade.xml
  extras/foreignkeys/src/main/resources/liquibase/1.2.0/job-foreignkey_delete_cascade.xml
  extras/foreignkeys/src/main/resources/liquibase/1.2.0/job_step_definition-foreignkey_delete_cascade.xml
  extras/foreignkeys/src/main/resources/liquibase/1.2.0/tag-foreignkey_delete_cascade.xml
  extras/foreignkeys/src/main/resources/liquibase/1.2.0/trigger-foreignkey_delete_cascade.xml
  extras/foreignkeys/src/main/resources/liquibase/1.2.0/user-foreignkey_delete_cascade.xml
  extras/foreignkeys/src/main/resources/liquibase/changelog-foreignkeys-master.post.xml
  service/scheduler/quartz/src/main/resources/liquibase/1.2.0/changelog-scheduler-1.2.0.xml
  service/scheduler/quartz/src/main/resources/liquibase/1.2.0/scheduler_engine_quartz-delete_cascade.xml
Labels: bug, liquibase

#2917 Fixed javadoc for JpaJobStatus
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaJobStatus.java
Labels: bug, documentation

#2919 Easier Broker Debug in Docker Compose
  deployment/docker/compose/docker-compose.broker-debug.yml
  deployment/docker/unix/docker-deploy.sh
  deployment/docker/win/docker-deploy.ps1
  deployment/docker/win/docker-undeploy.ps1
Labels: enhancement
