Repository eclipse-kapua/kapua, pull requests merged in 2021-11, with the labels that each got.

#3429 Fixed Rest API `doPrivileged` authentication trusted
  assembly/api/docker/Dockerfile
  commons/src/main/java/org/eclipse/kapua/commons/logging/LoggingMdcKeys.java
  commons/src/main/java/org/eclipse/kapua/commons/security/KapuaSecurityUtils.java
  job-engine/api/pom.xml
  job-engine/app/core/pom.xml
  job-engine/app/core/src/main/java/org/eclipse/kapua/job/engine/app/core/filter/RebuildSessionFilter.java
  job-engine/app/pom.xml
  job-engine/app/resources/pom.xml
  job-engine/app/web/pom.xml
  job-engine/app/web/src/main/resources/locator.xml
  job-engine/client/pom.xml
  job-engine/client/src/main/java/org/eclipse/kapua/job/engine/client/JobEngineFactoryClient.java
  job-engine/client/src/main/java/org/eclipse/kapua/job/engine/client/JobEngineServiceClient.java
  job-engine/client/src/main/java/org/eclipse/kapua/job/engine/client/JobStartOptionsClient.java
  job-engine/client/src/main/java/org/eclipse/kapua/job/engine/client/SessionInfoFilter.java
  job-engine/client/src/main/java/org/eclipse/kapua/job/engine/client/filter/SessionInfoFilter.java
  job-engine/client/src/main/java/org/eclipse/kapua/job/engine/client/filter/SessionInfoHttpHeaders.java
  job-engine/client/src/main/java/org/eclipse/kapua/job/engine/client/settings/JobEngineClientSetting.java
  job-engine/client/src/main/java/org/eclipse/kapua/job/engine/client/settings/JobEngineClientSettingKeys.java
  job-engine/commons/pom.xml
  job-engine/jbatch/pom.xml
  job-engine/pom.xml
  pom.xml
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/AuthenticationServiceShiroImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/AccessTokenAuthenticatingRealm.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/ApiKeyAuthenticatingRealm.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/JwtAuthenticatingRealm.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/KapuaAuthenticatingRealm.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/UserPassAuthenticatingRealm.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/session/ShiroSessionKeys.java
Labels: Bug, rest-api

#3438 Set console 'job.engine.client.auth.mode' to 'access_token'
  assembly/console/docker/Dockerfile
Labels: Enhancement

#3440 Added session AccessToken refreshing on the Console Web Filter
  console/core/src/main/java/org/eclipse/kapua/app/console/core/filter/KapuaWebFilter.java
  console/web/src/main/resources/shiro.ini
Labels: Enhancement, Console GWT

#3441 Datastore - move bindings to local module
  console/web/src/main/resources/locator.xml
  consumer/telemetry-app/src/main/resources/locator.xml
  qa/integration/src/test/resources/locator.xml
  rest-api/web/src/main/resources/locator.xml
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ChannelInfoFactoryImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ChannelInfoRegistryServiceImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ClientInfoFactoryImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ClientInfoRegistryServiceImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/DatastoreModule.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MessageStoreFactoryImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MessageStoreServiceImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MetricInfoFactoryImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MetricInfoRegistryServiceImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/model/query/predicate/DatastorePredicateFactoryImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/model/query/predicate/DatastoreQueryPredicateModule.java
Labels: Enhancement

#3451 Removed log line leftover from #3440
  console/core/src/main/java/org/eclipse/kapua/app/console/core/filter/KapuaWebFilter.java
Labels: Bug, Console GWT

#3452 Fix unit test build
  broker/core/src/main/java/org/eclipse/kapua/broker/core/plugin/authentication/AuthenticationLogic.java
  rest-api/web/pom.xml
Labels: Bug, Test

#3459 Support Eclipse Link target.database property
  commons/src/main/java/org/eclipse/kapua/commons/jpa/AbstractEntityManagerFactory.java
  commons/src/main/java/org/eclipse/kapua/commons/jpa/CommonsEntityManagerFactory.java
  commons/src/main/java/org/eclipse/kapua/commons/jpa/DataSource.java
  commons/src/main/java/org/eclipse/kapua/commons/setting/system/SystemSettingKey.java
  commons/src/main/resources/kapua-environment-setting.properties
  commons/src/test/java/org/eclipse/kapua/commons/model/misc/CollisionEntityManagerFactory.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/JobEngineEntityManagerFactory.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/JbatchEntityManagerFactory.java
  service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountEntityManagerFactory.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/DatastoreEntityManagerFactory.java
  service/device/management/job/internal/src/main/java/org/eclipse/kapua/service/device/management/job/internal/JobDeviceManagementOperationEntityManagerFactory.java
  service/device/management/registry/internal/src/main/java/org/eclipse/kapua/service/device/management/registry/operation/internal/DeviceManagementOperationEntityManagerFactory.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/DeviceServiceModule.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/connection/internal/DeviceConnectionServiceImpl.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/connection/option/internal/DeviceConnectionOptionServiceImpl.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/event/internal/DeviceEventServiceImpl.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/internal/DeviceEntityManagerFactory.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/internal/DeviceRegistryServiceImpl.java
  service/device/registry/test/src/test/java/org/eclipse/kapua/service/device/registry/test/DeviceRegistryLocatorConfiguration.java
  service/endpoint/internal/src/main/java/org/eclipse/kapua/service/endpoint/internal/EndpointEntityManagerFactory.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/internal/JobEntityManagerFactory.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/quartz/SchedulerEntityManagerFactory.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/MfaOptionEntityManagerFactory.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/MfaOptionServiceImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/ScratchCodeEntityManagerFactory.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/ScratchCodeServiceImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/AuthenticationEntityManagerFactory.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/token/shiro/AccessTokenEntityManagerFactory.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/token/shiro/AccessTokenServiceImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/shiro/AuthorizationEntityManagerFactory.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/MfaOptionEntityManagerFactoryTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/ScratchCodeEntityManagerFactoryTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/token/shiro/AccessTokenEntityManagerFactoryTest.java
  service/tag/internal/src/main/java/org/eclipse/kapua/service/tag/internal/TagEntityManagerFactory.java
  service/tag/test/src/test/java/org/eclipse/kapua/service/tag/test/TagLocatorConfiguration.java
  service/user/internal/src/main/java/org/eclipse/kapua/service/user/internal/UserEntityManagerFactory.java
Labels: Enhancement

#3461 Endpoint - move bindings to local module
  console/web/src/main/resources/locator.xml
  job-engine/app/web/src/main/resources/locator.xml
  qa/integration/src/test/resources/locator.xml
  rest-api/web/src/main/resources/locator.xml
  service/endpoint/internal/src/main/java/org/eclipse/kapua/service/endpoint/internal/EndpointInfoFactoryImpl.java
  service/endpoint/internal/src/main/java/org/eclipse/kapua/service/endpoint/internal/EndpointInfoServiceImpl.java
  service/endpoint/internal/src/main/java/org/eclipse/kapua/service/endpoint/internal/EndpointModule.java
Labels: Enhancement

#3458 Scheduler - move bindings to local module
  assembly/broker/configurations/locator.xml
  console/web/src/main/resources/locator.xml
  consumer/lifecycle-app/src/main/resources/locator.xml
  job-engine/app/web/src/main/resources/locator.xml
  qa/integration/src/test/resources/locator.xml
  rest-api/web/src/main/resources/locator.xml
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/definition/quartz/SchedulerTriggerDefinitionModule.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/definition/quartz/TriggerDefinitionFactoryImpl.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/definition/quartz/TriggerDefinitionServiceImpl.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/fired/quartz/FiredTriggerFactoryImpl.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/fired/quartz/FiredTriggerServiceImpl.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/fired/quartz/SchedulerTriggerFiredModule.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/quartz/SchedulerQuartzModule.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/quartz/TriggerFactoryImpl.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/quartz/TriggerServiceImpl.java
  service/scheduler/test/src/test/resources/locator.xml
Labels: Enhancement

#3466 Message - move bindings to local module
  assembly/broker/configurations/locator.xml
  broker/core/src/test/resources/locator.xml
  console/web/src/main/resources/locator.xml
  consumer/lifecycle-app/src/main/resources/locator.xml
  consumer/telemetry-app/src/main/resources/locator.xml
  job-engine/app/web/src/main/resources/locator.xml
  message/internal/src/main/java/org/eclipse/kapua/message/internal/KapuaMessageFactoryImpl.java
  message/internal/src/main/java/org/eclipse/kapua/message/internal/MessageModule.java
  message/internal/src/main/java/org/eclipse/kapua/message/internal/device/data/KapuaDataMessageFactoryImpl.java
  message/internal/src/main/java/org/eclipse/kapua/message/internal/device/data/MessageDataModule.java
  message/internal/src/main/java/org/eclipse/kapua/message/internal/device/lifecycle/KapuaLifecycleMessageFactoryImpl.java
  message/internal/src/main/java/org/eclipse/kapua/message/internal/device/lifecycle/MessageLifecycleModule.java
  message/internal/src/test/resources/locator.xml
  qa/integration/src/test/resources/locator.xml
  service/device/registry/test/src/test/resources/locator.xml
Labels: Enhancement

#3467 Improved GuiceLocator logging
  commons/src/main/java/org/eclipse/kapua/commons/core/AbstractKapuaModule.java
  commons/src/main/java/org/eclipse/kapua/commons/util/log/ConfigurationPrinter.java
  locator/guice/src/main/java/org/eclipse/kapua/locator/guice/GuiceLocatorImpl.java
  locator/guice/src/main/java/org/eclipse/kapua/locator/guice/LocatorConfig.java
  service/api/src/main/java/org/eclipse/kapua/locator/KapuaServiceLoader.java
Labels: Enhancement

#3468 Fixed TranslatorAppSnapshotKuraKapua to handle empty body
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/TranslatorAppSnapshotKuraKapua.java
Labels: Bug
