Repository eclipse-kapua/kapua, pull requests merged in 2021-08, with the labels that each got.

#3335 Do not increase lockout counter error when credentials are correct but no otp is provided
  qa/integration/src/test/resources/features/user/LockoutExpirationI9n.feature
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/UserPassAuthenticatingRealm.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/UserPassCredentialsMatcher.java
  service/user/test-steps/src/main/java/org/eclipse/kapua/service/user/steps/UserServiceSteps.java
Labels: Bug

#3355 HikariCP Database Connection Pooling
  assembly/broker/descriptors/kapua-broker.xml
  assembly/broker/pom.xml
  commons/pom.xml
  commons/src/main/java/org/eclipse/kapua/commons/jpa/AbstractEntityManagerFactory.java
  commons/src/main/java/org/eclipse/kapua/commons/jpa/DataSource.java
  commons/src/main/java/org/eclipse/kapua/commons/setting/system/SystemSettingKey.java
  commons/src/test/java/org/eclipse/kapua/commons/setting/system/SystemSettingKeyTest.java
  pom.xml
  service/security/shiro/pom.xml
Labels: Enhancement

#3361 Fixed configuration of job-engine
  job-engine/app/web/src/main/java/org/eclipse/kapua/job/engine/app/web/jaxb/JaxbContextResolver.java
Labels: Bug

#3360 Add askTotalCount to DeviceEvents REST API
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceEvents.java
  rest-api/resources/src/main/resources/openapi/deviceEvent/deviceEvent-scopeId-deviceId.yaml
Labels: Enhancement, rest-api

#3362 Fixed example of model DeviceKeystoreCertificateInfo
  rest-api/resources/src/main/resources/openapi/deviceKeystore/deviceKeystore.yaml
Labels: Bug, documentation

#3364 Hide Device Tabs if feature is not supported by device
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/assets/DeviceTabAssets.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/bundles/DeviceTabBundles.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/command/DeviceTabCommand.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/configuration/DeviceTabConfiguration.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/inventory/DeviceTabInventory.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/keystore/DeviceTabKeystore.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/packages/DeviceTabPackages.java
Labels: Enhancement, Console GWT

#3365 Fix MfaOption search when authenticating
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/UserPassAuthenticatingRealm.java
Labels: Bug, Security
