Repository eclipse-kapua/kapua, pull requests merged in 2021-04, with the labels that each got.

#3288 Fixed device-management-inventory-internal module package names
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/internal/DeviceInventoryAppProperties.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/internal/DeviceInventoryManagementFactoryImpl.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/internal/DeviceInventoryManagementServiceImpl.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/internal/exception/DeviceInventoryGetManagementException.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/internal/exception/InventoryManagementResponseErrorCodes.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/internal/exception/InventoryManagementResponseException.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/message/internal/InventoryRequestChannel.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/message/internal/InventoryRequestMessage.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/message/internal/InventoryRequestPayload.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/message/internal/InventoryResponseChannel.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/message/internal/InventoryResponseMessage.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/message/internal/InventoryResponsePayload.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/model/bundle/internal/DeviceInventoryBundleImpl.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/model/bundle/internal/DeviceInventoryBundlesImpl.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/model/inventory/internal/DeviceInventoryImpl.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/model/inventory/internal/DeviceInventoryItemImpl.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/model/packages/internal/DeviceInventoryPackageImpl.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/model/packages/internal/DeviceInventoryPackagesImpl.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/model/system/internal/DeviceInventorySystemPackageImpl.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/model/system/internal/DeviceInventorySystemPackagesImpl.java
Labels: Bug

#3292 Don't check for specific CORS Origin if session is not yet created
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/CORSResponseFilter.java
Labels: Bug, rest-api

#3294 Fixed CORS filtering fail causing print of stacktrace in HTTP Response
  job-engine/app/web/src/main/webapp/WEB-INF/web.xml
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/filter/CORSResponseFilter.java
  rest-api/web/src/main/webapp/WEB-INF/web.xml
Labels: Bug

#3293 Add Endpoint service dependency after new CORS filter
  job-engine/app/web/pom.xml
  job-engine/app/web/src/main/resources/locator.xml
Labels: Bug

#3297 Improve Upsert Failed Error Message in Elasticsearch REST Client
  service/commons/elasticsearch/client-rest/src/main/java/org/eclipse/kapua/service/elasticsearch/client/rest/RestElasticsearchClient.java
Labels: Enhancement

#3300 Issuer name added in MFA QR code image
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/MfaOptionServiceImpl.java
Labels: Enhancement

#3298 SSO - OIDC environment variables renaming
  assembly/README.md
  assembly/console/entrypoint/run-console
  deployment/docker/compose/docker-compose.yml
  deployment/docker/compose/sso/sso-docker-compose.yml
  docs/developer-guide/en/sso.md
Labels: Enhancement
