Repository eclipse-kapua/kapua, pull requests merged in 2021-09, with the labels that each got.

#3368 external consumers - move application code/configuration to a 3rd module
  assembly/consumer/lifecycle/descriptors/kapua-consumer-lifecycle.xml
  assembly/consumer/lifecycle/entrypoint/run-consumer-lifecycle
  assembly/consumer/lifecycle/pom.xml
  assembly/consumer/telemetry/descriptors/kapua-consumer-telemetry.xml
  assembly/consumer/telemetry/entrypoint/run-consumer-telemetry
  assembly/consumer/telemetry/pom.xml
  consumer/lifecycle-app/pom.xml
  consumer/lifecycle-app/src/main/java/org/eclipse/kapua/consumer/lifecycle/LifecycleApplication.java
  consumer/lifecycle-app/src/main/java/org/eclipse/kapua/consumer/lifecycle/LifecycleJAXBContextProvider.java
  consumer/lifecycle-app/src/main/java/org/eclipse/kapua/consumer/lifecycle/LifecycleRouteHealthIndicator.java
  consumer/lifecycle-app/src/main/resources/camel/camel.xml
  consumer/lifecycle-app/src/main/resources/locator.xml
  consumer/lifecycle-app/src/main/resources/logback.xml
  consumer/lifecycle-app/src/main/resources/shiro.ini
  consumer/lifecycle-app/src/main/resources/spring/application.properties
  consumer/lifecycle-app/src/main/resources/spring/applicationContext.xml
  consumer/pom.xml
  consumer/telemetry-app/pom.xml
  consumer/telemetry-app/src/main/java/org/eclipse/kapua/consumer/telemetry/TelemetryApplication.java
  consumer/telemetry-app/src/main/java/org/eclipse/kapua/consumer/telemetry/TelemetryJAXBContextProvider.java
  consumer/telemetry-app/src/main/java/org/eclipse/kapua/consumer/telemetry/TelemetryRouteHealthIndicator.java
  consumer/telemetry-app/src/main/resources/camel/camel.xml
  consumer/telemetry-app/src/main/resources/locator.xml
  consumer/telemetry-app/src/main/resources/logback.xml
  consumer/telemetry-app/src/main/resources/shiro.ini
  consumer/telemetry-app/src/main/resources/spring/application.properties
  consumer/telemetry-app/src/main/resources/spring/applicationContext.xml
  pom.xml
Labels: Enhancement

#3372 Fixed Keystore Keypair creation from console
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/shared/model/management/keystore/GwtDeviceKeystoreKeypair.java
Labels: Bug, Console GWT

#3374 Feature kapua list result get items enachements
  commons/src/main/java/org/eclipse/kapua/commons/model/query/KapuaListResultImpl.java
  commons/src/test/java/org/eclipse/kapua/commons/model/query/KapuaListResultImplTest.java
  service/api/src/main/java/org/eclipse/kapua/model/query/KapuaListResult.java
Labels: Enhancement

#3377 Implemented JobStepProperty.secret
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/client/steps/JobStepAddDialog.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/shared/model/GwtJobStepProperty.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/shared/util/KapuaGwtJobModelConverter.java
  rest-api/resources/src/main/resources/openapi/jobStepDefinition/jobStepDefinition.yaml
  service/job/api/src/main/java/org/eclipse/kapua/service/job/step/definition/JobStepProperty.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/step/definition/internal/JobStepPropertyImpl.java
  service/job/internal/src/main/resources/liquibase/1.6.0/changelog-job-1.6.0.xml
  service/job/internal/src/main/resources/liquibase/1.6.0/job_job_step_definition_properties-secret.xml
  service/job/internal/src/main/resources/liquibase/1.6.0/job_job_step_properties-secret.xml
  service/job/internal/src/main/resources/liquibase/changelog-job-master.xml
Labels: Enhancement

#3378 Fixed NPE on TriggerService.find when Trigger does not exist
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/quartz/TriggerServiceImpl.java
Labels: Bug

#3382 Job's errors messages now print the explanation
  job-engine/api/src/main/resources/job-engine-service-error-messages.properties
Labels: Bug
