Repository eclipse-kapua/kapua, pull requests merged in 2021-01, with the labels that each got.

#3191 Added indexes on jBatch tables to improve performances
  job-engine/jbatch/src/main/resources/liquibase/1.5.0/changelog-job-engine-1.5.0.xml
  job-engine/jbatch/src/main/resources/liquibase/1.5.0/job_engine_jbatch-performance_indexes.xml
  job-engine/jbatch/src/main/resources/liquibase/changelog-job-engine-master.xml
Labels: Enhancement

#3183 Cache exception handling improvement
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/cache/EntityCache.java
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/cache/NamedEntityCache.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/connection/internal/DeviceConnectionServiceImpl.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/internal/DeviceRegistryCache.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/access/shiro/AccessInfoCache.java
Labels: Enhancement

#3182 GitHub Actions CI
  .github/workflows/README.md
  .github/workflows/github-actions.yaml
  .travis.yml
  build-tools/src/main/toolchains/travis-ci.xml
  ci-output.sh
  qa/integration/src/test/java/org/eclipse/kapua/integration/service/user/RunUserPermissionI9nTest.java
Labels: Enhancement, Test

#3190 Added unit tests for Client Module
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/AbstractClientTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/util/BuffersTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/util/FuturesTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/util/MoreExecutorsTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/util/StringsTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/util/TransportAsyncTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/util/TransportProxyTest.java
Labels: Test

#3149 Added JUnit tests for client/gateway/mqtt package
  client/gateway/provider/fuse/pom.xml
  client/gateway/provider/fuse/src/test/java/org/eclipse/kapua/client/gateway/mqtt/fuse/FuseChannelTest.java
  client/gateway/provider/fuse/src/test/java/org/eclipse/kapua/client/gateway/mqtt/fuse/internal/CallbacksTest.java
  client/gateway/provider/mqtt/pom.xml
  client/gateway/provider/mqtt/src/test/java/org/eclipse/kapua/client/gateway/mqtt/AbstractMqttChannelTest.java
  client/gateway/provider/paho/pom.xml
  client/gateway/provider/paho/src/test/java/org/eclipse/kapua/client/gateway/mqtt/paho/internal/ListenersTest.java
Labels: Test

#3107 Added Junit tests for broker module
  broker/api/pom.xml
  broker/api/src/test/java/org/eclipse/kapua/broker/BrokerDomainTest.java
  broker/api/src/test/java/org/eclipse/kapua/broker/BrokerDomainsTest.java
  broker/core/pom.xml
  broker/core/src/test/java/org/eclipse/kapua/broker/core/message/CamelKapuaMessageTest.java
  broker/core/src/test/java/org/eclipse/kapua/broker/core/message/CamelUtilTest.java
  broker/core/src/test/java/org/eclipse/kapua/broker/core/message/MessageConstantsTest.java
  broker/core/src/test/java/org/eclipse/kapua/broker/core/message/system/DefaultSystemMessageCreatorTest.java
  broker/core/src/test/java/org/eclipse/kapua/broker/core/plugin/metric/ClientMetricTest.java
  broker/core/src/test/java/org/eclipse/kapua/broker/core/plugin/metric/LoginMetricTest.java
  broker/core/src/test/java/org/eclipse/kapua/broker/core/plugin/metric/PublishMetricTest.java
  broker/core/src/test/java/org/eclipse/kapua/broker/core/plugin/metric/SecurityMetricsTest.java
  broker/core/src/test/java/org/eclipse/kapua/broker/core/plugin/metric/SubscribeMetricTest.java
Labels: Test

#3197 Fixed Console Http Session Fixation security issue
  console/core/src/main/java/org/eclipse/kapua/app/console/core/server/GwtAuthorizationServiceImpl.java
  console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/server/util/KapuaExceptionHandler.java
Labels: Bug, Security

#3198 Bump slf4j-api dependency version from 1.7.26 to 1.7.30
  pom.xml
Labels: Dependencies

#3211 Fixed KapuaErrorHandlerServlet missing template mapping
  console/core/src/main/java/org/eclipse/kapua/app/console/core/servlet/FileServlet.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/servlet/KapuaErrorHandlerServlet.java
  console/web/pom.xml
Labels: Bug

#3210 Device management response stacktrace show option
  assembly/api/docker/Dockerfile
  assembly/console/entrypoint/run-console
  deployment/minishift/README.md
  deployment/openshift/README.md
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/exception/model/ThrowableInfo.java
  service/device/api/src/main/java/org/eclipse/kapua/service/device/management/message/response/KapuaResponsePayload.java
  service/device/commons/src/main/java/org/eclipse/kapua/service/device/management/commons/message/response/KapuaResponsePayloadImpl.java
  service/device/commons/src/main/java/org/eclipse/kapua/service/device/management/commons/setting/DeviceManagementSettingKey.java
  service/device/commons/src/main/resources/device-management-setting.properties
  service/device/management/asset/internal/src/main/java/org/eclipse/kapua/service/device/management/asset/message/internal/AssetRequestPayload.java
  service/device/management/asset/internal/src/main/java/org/eclipse/kapua/service/device/management/asset/message/internal/AssetResponseChannel.java
  service/device/management/asset/internal/src/main/java/org/eclipse/kapua/service/device/management/asset/message/internal/AssetResponsePayload.java
  service/device/management/bundle/internal/src/main/java/org/eclipse/kapua/service/device/management/bundle/internal/DeviceBundleManagementServiceImpl.java
  service/device/management/bundle/internal/src/main/java/org/eclipse/kapua/service/device/management/bundle/message/internal/BundleResponseChannel.java
  service/device/management/command/internal/src/main/java/org/eclipse/kapua/service/device/management/command/message/internal/CommandResponseChannel.java
  service/device/management/configuration/internal/src/main/java/org/eclipse/kapua/service/device/management/configuration/internal/DeviceConfigurationManagementServiceImpl.java
  service/device/management/configuration/internal/src/main/java/org/eclipse/kapua/service/device/management/configuration/message/internal/ConfigurationResponseChannel.java
  service/device/management/configuration/internal/src/main/java/org/eclipse/kapua/service/device/management/snapshot/internal/DeviceSnapshotManagementServiceImpl.java
  service/device/management/configuration/internal/src/main/java/org/eclipse/kapua/service/device/management/snapshot/message/internal/SnapshotResponseChannel.java
  service/device/management/packages/internal/src/main/java/org/eclipse/kapua/service/device/management/packages/internal/DevicePackageManagementServiceImpl.java
  service/device/management/packages/internal/src/main/java/org/eclipse/kapua/service/device/management/packages/message/internal/PackageResponseChannel.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/AbstractSimpleTranslatorResponseKuraKapua.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/MethodDictionaryKuraKapua.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/TranslatorAppAssetKuraKapua.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/TranslatorAppBundleKuraKapua.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/TranslatorAppCommandKuraKapua.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/TranslatorAppConfigurationKuraKapua.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/TranslatorAppPackageKuraKapua.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/TranslatorAppResponseKuraKapua.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/TranslatorAppSnapshotKuraKapua.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/TranslatorKuraKapuaUtils.java
Labels: Enhancement, Security

#3212 Added ConfigurationPrinterTest.class
  commons/src/test/java/org/eclipse/kapua/commons/util/log/ConfigurationPrinterTest.java
Labels: Test
