Repository eclipse-kapua/kapua, pull requests merged in 2021-03, with the labels that each got.

#3254 Added JUnit tests for rest-api/web module
  rest-api/web/pom.xml
  rest-api/web/src/test/java/org/eclipse/kapua/app/api/web/JaxbContextResolverTest.java
  rest-api/web/src/test/java/org/eclipse/kapua/app/api/web/RestApiJAXBContextProviderTest.java
  rest-api/web/src/test/java/org/eclipse/kapua/app/api/web/RestApiListenerTest.java
  rest-api/web/src/test/java/org/eclipse/kapua/app/api/web/RestApisApplicationTest.java
Labels: Test

#3253 Added JUnit tests for model/data package
  rest-api/core/pom.xml
  rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/model/data/JsonDatastoreMessageTest.java
  rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/model/data/JsonKapuaDataMessageTest.java
  rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/model/data/JsonMessageListResultTest.java
  rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/model/data/JsonMessageQueryTest.java
Labels: Test

#3271 Fixed Liquibase properties which where not compatible with MySQL
  commons/src/main/resources/liquibase/common-properties.xml
  service/account/internal/src/main/resources/liquibase/0.2.0/account-configuration.xml
  service/account/internal/src/main/resources/liquibase/common-properties.xml
  service/device/registry/internal/src/main/resources/liquibase/common-properties.xml
  service/endpoint/internal/src/main/resources/liquibase/common-properties.xml
  service/security/shiro/src/main/resources/liquibase/common-properties.xml
  service/tag/internal/src/main/resources/liquibase/common-properties.xml
  service/user/internal/src/main/resources/liquibase/common-properties.xml
Labels: Bug

#3267 Fixed declaration of showStacktrace in Console assembly run file
  assembly/console/entrypoint/run-console
Labels: Bug

#3260 Fixed OpenID Connect tokens for SSO
  assembly/README.md
  console/core/src/main/java/org/eclipse/kapua/app/console/core/servlet/SsoCallbackServlet.java
  deployment/docker/compose/docker-compose.yml
  deployment/docker/compose/sso/sso-docker-compose.yml
  plug-ins/sso/openid-connect/api/src/main/java/org/eclipse/kapua/plugin/sso/openid/JwtProcessor.java
  plug-ins/sso/openid-connect/api/src/main/java/org/eclipse/kapua/plugin/sso/openid/OpenIDService.java
  plug-ins/sso/openid-connect/api/src/main/java/org/eclipse/kapua/plugin/sso/openid/exception/OpenIDErrorCodes.java
  plug-ins/sso/openid-connect/api/src/main/java/org/eclipse/kapua/plugin/sso/openid/exception/OpenIDTokenException.java
  plug-ins/sso/openid-connect/provider/src/main/java/org/eclipse/kapua/plugin/sso/openid/provider/AbstractOpenIDService.java
  plug-ins/sso/openid-connect/provider/src/main/java/org/eclipse/kapua/plugin/sso/openid/provider/internal/DisabledLocator.java
  plug-ins/sso/openid-connect/provider/src/main/java/org/eclipse/kapua/plugin/sso/openid/provider/jwt/AbstractJwtProcessor.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/JwtCredentials.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/CredentialsFactoryImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/JwtCredentialsImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/JwtAuthenticatingRealm.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/JwtCredentialsMatcher.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/registration/RegistrationServiceImpl.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/shiro/CredentialsFactoryImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/shiro/JwtCredentialsTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/shiro/realm/JwtCredentialsMatcherTest.java
Labels: Bug

#3265 Expose AccountService.findChildrenRecursive on REST API
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Accounts.java
  rest-api/resources/src/main/resources/openapi/account/account-scopeId.yaml
  service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountServiceImpl.java
Labels: Enhancement, rest-api

#3276 Bumped version of guava from 27.1-jre to 30.1-jre - CVE-2020-8908 - CWE-200
  pom.xml
Labels: Dependencies, Security

#3277 Bumped version of commons-codec from 1.9 to 1.15 - CWE-200
  pom.xml
Labels: Dependencies, Security

#3275 Bumped version of Snake Yaml from 1.15 to 1.28 - CVE-2017-18640 - CWE-189
  pom.xml
Labels: CQ pending, Dependencies, Security

#3274 Upgraded Jackson dependencies version from 2.10.1 to 2.12.2 - CVE-2020-25649 - CWE-611
  pom.xml
Labels: CQ approved, Dependencies, Security

#3282 Fixed GenericRequestPayload translation
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceManagementRequestsJson.java
  service/device/api/src/main/java/org/eclipse/kapua/service/device/management/message/KapuaAppChannel.java
  service/device/api/src/main/java/org/eclipse/kapua/service/device/management/message/request/KapuaRequestChannel.java
  service/device/management/request/api/src/main/java/org/eclipse/kapua/service/device/management/request/message/request/GenericRequestChannel.java
  service/device/management/request/internal/src/main/java/org/eclipse/kapua/service/device/management/request/internal/message/request/GenericRequestChannelImpl.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/AbstractSimpleTranslatorResponseKuraKapua.java
Labels: Bug

#3283 Bumped version of Netty4 to 4.1.60.Final - CVE-2021-21290 - CWE-378
  pom.xml
Labels: Dependencies

#3273 [Feature] Device Birth Extended Properties
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/ServiceDAO.java
  console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/client/ui/tab/EntityDescriptionTabItem.java
  console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/shared/model/GwtGroupedNVPair.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/server/GwtDeviceServiceImpl.java
  message/api/src/main/java/org/eclipse/kapua/message/device/lifecycle/KapuaBirthPayload.java
  message/api/src/main/java/org/eclipse/kapua/message/device/lifecycle/KapuaBirthPayloadAttibutes.java
  message/internal/src/main/java/org/eclipse/kapua/message/internal/device/lifecycle/KapuaAppsPayloadImpl.java
  message/internal/src/main/java/org/eclipse/kapua/message/internal/device/lifecycle/KapuaBirthPayloadImpl.java
  message/internal/src/main/java/org/eclipse/kapua/message/internal/device/lifecycle/model/BirthExtendedProperties.java
  message/internal/src/main/java/org/eclipse/kapua/message/internal/device/lifecycle/model/BirthExtendedProperty.java
  message/internal/src/test/java/org/eclipse/kapua/message/internal/device/lifecycle/KapuaAppsMessageTest.java
  message/internal/src/test/java/org/eclipse/kapua/message/internal/device/lifecycle/KapuaBirthMessageTest.java
  service/device/call/kura/src/main/java/org/eclipse/kapua/service/device/call/message/kura/lifecycle/AbstractKuraAppsBirthPayload.java
  service/device/registry/api/src/main/java/org/eclipse/kapua/service/device/registry/Device.java
  service/device/registry/api/src/main/java/org/eclipse/kapua/service/device/registry/DeviceAttributes.java
  service/device/registry/api/src/main/java/org/eclipse/kapua/service/device/registry/DeviceCreator.java
  service/device/registry/api/src/main/java/org/eclipse/kapua/service/device/registry/DeviceExtendedProperty.java
  service/device/registry/api/src/main/java/org/eclipse/kapua/service/device/registry/DeviceFactory.java
  service/device/registry/api/src/main/java/org/eclipse/kapua/service/device/registry/DeviceXmlRegistry.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/internal/DeviceCreatorImpl.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/internal/DeviceDAO.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/internal/DeviceExtendedPropertyImpl.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/internal/DeviceFactoryImpl.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/internal/DeviceImpl.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/lifecycle/internal/DeviceLifeCycleServiceImpl.java
  service/device/registry/internal/src/main/resources/META-INF/persistence.xml
  service/device/registry/internal/src/main/resources/liquibase/1.5.0/changelog-device-1.5.0.xml
  service/device/registry/internal/src/main/resources/liquibase/1.5.0/device_properties.xml
  service/device/registry/internal/src/main/resources/liquibase/changelog-device-master.xml
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/TranslatorLifeAppsKuraKapua.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/TranslatorLifeBirthKuraKapua.java
Labels: Enhancement

#3284 Fixed logic that checks for job executions before editing JobStep
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/step/internal/JobStepServiceImpl.java
Labels: Bug

#3285 Fixed definition of `schdl_trigger_fired` with `ON DELETE CASCADE`
  service/scheduler/quartz/src/main/resources/liquibase/1.5.0/fired_trigger.xml
Labels: Bug
