Repository eclipse-kapua/kapua, pull requests merged in 2022-03, with the labels that each got.

#3519 Fix Swagger CLI openapi.yaml generation
  assembly/api/pom.xml
  rest-api/resources/src/main/resources/openapi/accessInfo/accessInfo.yaml
  rest-api/resources/src/main/resources/openapi/device/device.yaml
Labels: Bug

#3520 Sanitized Event Message field
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/events/DeviceTabEvents.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/events/EventMessageDetailsDialog.java
Labels: Bug, Console GWT

#3524 Added check for duplicate JobTarget and few more checks
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/JobTargets.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/targets/internal/JobTargetServiceImpl.java
Labels: Bug

#3528 Fixed docker logs command
  deployment/docker/unix/docker-logs.sh
Labels: Bug

#3521 Added missing Cross-Site Request Forgery token (XSRF) checks
  console/module/account/src/main/java/org/eclipse/kapua/app/console/module/account/client/cors/CorsAddDialog.java
  console/module/account/src/main/java/org/eclipse/kapua/app/console/module/account/client/cors/CorsDeleteDialog.java
  console/module/account/src/main/java/org/eclipse/kapua/app/console/module/account/client/cors/CorsEditDialog.java
  console/module/endpoint/src/main/java/org/eclipse/kapua/app/console/module/endpoint/client/EndpointAddDialog.java
  console/module/endpoint/src/main/java/org/eclipse/kapua/app/console/module/endpoint/client/EndpointDeleteDialog.java
  console/module/endpoint/src/main/java/org/eclipse/kapua/app/console/module/endpoint/client/EndpointEditDialog.java
  console/module/endpoint/src/main/java/org/eclipse/kapua/app/console/module/endpoint/server/GwtEndpointServiceImpl.java
  console/module/endpoint/src/main/java/org/eclipse/kapua/app/console/module/endpoint/shared/service/GwtEndpointService.java
Labels: Bug, Console GWT

#3527 Fixed fields validation bypass
  service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountServiceImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/shiro/CredentialServiceImpl.java
Labels: Bug

#3529 Fixed refresh of Deployment Packages subtab
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/inventory/DeviceTabInventoryTabDeploymentPackages.java
Labels: Bug, Console GWT

#3532 Added authentication check to getMinimumPswLength
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/server/GwtCredentialServiceImpl.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/AuthenticationService.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/AuthenticationServiceShiroImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/shiro/AuthorizationServiceImpl.java
Labels: Bug, Console GWT

#3531 Removed hasMfa method
  console/core/src/main/java/org/eclipse/kapua/app/console/core/client/LoginDialog.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/client/MfaLoginDialog.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/server/GwtAuthorizationServiceImpl.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/shared/service/GwtAuthorizationService.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/UserPassAuthenticatingRealm.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/UserPassCredentialsMatcher.java
Labels: Enhancement, Console GWT

#3535 Fixed Broker SERIALIZABLE_PACKAGES env definition
  assembly/broker/docker/Dockerfile
Labels: Bug

#3536 Set JAXB dependencies to fixed version
  message/internal/pom.xml
  pom.xml
Labels: Enhancement, Dependencies
