Repository eclipse-kapua/kapua, pull requests merged in 2022-11, with the labels that each got.

#3654 Replaced org.apache.sanselan:sanselan with org.apache.commons:commons-imaging - CVE-2018-17201 CVE-2018-17202
  console/module/account/pom.xml
  console/module/account/src/main/java/org/eclipse/kapua/app/console/module/account/server/GwtAccountServiceImpl.java
  console/module/device/pom.xml
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/server/GwtDeviceManagementServiceImpl.java
  console/pom.xml
  pom.xml
Labels: Dependencies

#3634 Further test refactorings in kapua - no semantic changes
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/access/shiro/AccessPermissionQueryImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/access/shiro/AccessRoleCacheFactoryTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/access/shiro/AccessRoleCreatorImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/access/shiro/AccessRoleFactoryImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/access/shiro/AccessRoleImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/access/shiro/AccessRoleQueryImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/domain/shiro/DomainCreatorImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/domain/shiro/DomainFactoryImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/domain/shiro/DomainImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/domain/shiro/DomainQueryImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/group/shiro/GroupCreatorImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/group/shiro/GroupFactoryImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/group/shiro/GroupImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/group/shiro/GroupQueryImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/role/shiro/RoleCacheFactoryTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/role/shiro/RoleCreatorImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/role/shiro/RoleFactoryImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/role/shiro/RoleImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/role/shiro/RolePermissionCacheFactoryTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/role/shiro/RolePermissionCreatorImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/role/shiro/RolePermissionQueryImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/role/shiro/RoleQueryImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/shiro/KapuaAuthorizingRealmTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/shiro/exception/InternalUserOnlyExceptionTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/shiro/exception/KapuaAuthorizationExceptionTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/shiro/exception/SelfManagedOnlyExceptionTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/shiro/exception/SubjectUnauthorizedExceptionTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/shiro/setting/KapuaAuthorizationSettingKeysTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/shiro/setting/KapuaAuthorizationSettingTest.java
  service/stream/api/src/test/java/org/eclipse/kapua/service/stream/StreamDomainTest.java
  service/stream/api/src/test/java/org/eclipse/kapua/service/stream/StreamDomainsTest.java
  transport/api/src/test/java/org/eclipse/kapua/transport/exception/TransportClientGetExceptionTest.java
  transport/api/src/test/java/org/eclipse/kapua/transport/exception/TransportExceptionTest.java
  transport/api/src/test/java/org/eclipse/kapua/transport/exception/TransportSendExceptionTest.java
  transport/api/src/test/java/org/eclipse/kapua/transport/exception/TransportTimeoutExceptionTest.java
  transport/api/src/test/java/org/eclipse/kapua/transport/utils/ClientIdGeneratorTest.java
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/message/mqtt/MqttMessageTest.java
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/message/mqtt/MqttPayloadTest.java
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/message/mqtt/MqttTopicTest.java
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/mqtt/MqttClientConnectionOptionsTest.java
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/mqtt/exception/MqttClientAlreadyConnectedExceptionTest.java
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/mqtt/exception/MqttClientCallbackSetExceptionTest.java
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/mqtt/exception/MqttClientCleanExceptionTest.java
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/mqtt/exception/MqttClientConnectExceptionTest.java
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/mqtt/exception/MqttClientDisconnectExceptionTest.java
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/mqtt/exception/MqttClientErrorCodesTest.java
Labels: Enhancement, Test

#3655 Refactored and improved MfaAuthenticatorImpl
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/mfa/MfaAuthenticator.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/mfa/MfaAuthenticatorImpl.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/shiro/mfa/MfaAuthenticatorImplTest.java
Labels: Bug, Test

#3656 Upgraded Spring Security from 5.7.4 to 5.7.5 - CVE-2022-31692
  pom.xml
Labels: Dependencies

#3657 Upgraded Apache Commons Compress from 1.18 to 1.22 - CVE-2021-35515 CVE-2021-35516 CVE-2021-35517 CVE-2021-36090
  pom.xml
Labels: Dependencies

#3660 Fixed Endpoint View permissions
  console/core/src/main/java/org/eclipse/kapua/app/console/core/client/NorthView.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/server/GwtAuthorizationServiceImpl.java
  console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/shared/model/session/GwtSession.java
  console/module/endpoint/src/main/java/org/eclipse/kapua/app/console/module/endpoint/client/EndpointViewDescriptor.java
Labels: Bug, Console GWT

#3661 speed-up CI process / removing duplicate execution of cucumber tests
  .github/workflows/kapua-ci.yaml
  qa/integration/src/test/java/org/eclipse/kapua/integration/service/account/RunAccountServiceI9nTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/service/datastore/RunDatastoreRestI9nTest.java
  qa/integration/src/test/resources/features/account/AccountDeviceRegistryService.feature
  qa/integration/src/test/resources/features/account/AccountGroupService.feature
  qa/integration/src/test/resources/features/account/AccountRoleService.feature
  qa/integration/src/test/resources/features/account/AccountServiceCreation.feature
  qa/integration/src/test/resources/features/account/AccountTagService.feature
  qa/integration/src/test/resources/features/account/AccountUserService.feature
  qa/integration/src/test/resources/features/jobScheduling/ExecuteOnDeviceConnectI9n.feature
  qa/integration/src/test/resources/features/jobScheduling/TriggerServiceI9n.feature
  service/device/registry/test/src/test/resources/features/DeviceRegistry.feature
Labels: Enhancement, Test

#3620 Prevent disabled device connection to the broker
  broker/core/src/main/java/org/eclipse/kapua/broker/core/plugin/KapuaSecurityBrokerFilter.java
  qa/integration/src/test/resources/features/device/DeviceServiceI9n.feature
  service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/BrokerSteps.java
Labels: Bug

#3663 Replacing `centos:7` with `rocky:8` as Docker base image
  assembly/java-base/docker/Dockerfile
  assembly/java-base/pom.xml
Labels: Enhancement, build
