Repository eclipse-kapua/kapua, pull requests merged in 2022-12, with the labels that each got.

#3669 KapuaId implementation use the same way to perform equals, hashCode and toString operations
  commons/src/main/java/org/eclipse/kapua/commons/model/id/KapuaEid.java
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/model/EntityId.java
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/model/ScopeId.java
  service/api/src/main/java/org/eclipse/kapua/model/id/KapuaId.java
  service/api/src/main/java/org/eclipse/kapua/model/id/KapuaIdImpl.java
Labels: Enhancement

#3670 Fixed AccountService improper segregation
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/ServiceDAO.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/server/GwtJobStepDefinitionServiceImpl.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/server/GwtJobStepServiceImpl.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/driver/JbatchDriver.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/AccessInfoDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/AccessPermissionDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/AccessRoleDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/AccessTokenDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/CredentialDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/DomainDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/EventStoreDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/GroupDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/MfaOptionDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/RoleDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/RolePermissionDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/ScratchCodeDAOTest.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/JobStepDefinitions.java
  service/account/api/src/main/java/org/eclipse/kapua/service/account/AccountService.java
  service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountServiceImpl.java
  service/account/test-steps/src/main/java/org/eclipse/kapua/service/account/steps/AccountServiceSteps.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/step/internal/JobStepServiceImpl.java
  service/job/test-steps/src/main/java/org/eclipse/kapua/service/job/steps/JobStepDefinitionServiceSteps.java
  service/job/test/src/test/resources/features/JobStepDefinitionService.feature
Labels: Bug

#3665 Correct handling of deeply nested attributes inside KapuaEntities
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/ServiceDAO.java
Labels: Bug

#3677 KapuaException throws NPE on null error code, but only if there is a message bundle
  rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/exception/RestApiRuntimeExceptionTest.java
  service/api/src/main/java/org/eclipse/kapua/ExceptionMessageUtils.java
  service/api/src/test/java/org/eclipse/kapua/ExceptionMessageUtilsTest.java
  service/api/src/test/java/org/eclipse/kapua/KapuaExceptionTest.java
  service/api/src/test/java/org/eclipse/kapua/KapuaIllegalArgumentExceptionTest.java
  service/api/src/test/java/org/eclipse/kapua/KapuaRuntimeExceptionTest.java
  service/api/src/test/java/org/eclipse/kapua/locator/KapuaLocatorExceptionTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/shiro/KapuaAuthenticationExceptionTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/shiro/exception/KapuaAuthorizationExceptionTest.java
Labels: Bug

#3682 Fix target `statusMessage` field not documented in Swagger UI example values
  rest-api/resources/src/main/resources/openapi/jobTarget/job-scopeId-jobId-targets-targetId.yaml
  rest-api/resources/src/main/resources/openapi/jobTarget/jobTarget.yaml
Labels: Bug, rest-api, Documentation

#3679 Refactoring: Move KapuaAuthorizationException to kapua-security-authorization-api
  broker/core/src/main/java/org/eclipse/kapua/broker/core/plugin/KapuaSecurityBrokerFilter.java
  console/core/src/main/java/org/eclipse/kapua/app/console/core/server/GwtAuthorizationServiceImpl.java
  console/module/account/src/main/java/org/eclipse/kapua/app/console/module/account/server/GwtAccountServiceImpl.java
  console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/server/util/KapuaExceptionHandler.java
  qa/integration/src/test/resources/features/account/AccountExpirationI9n.feature
  qa/integration/src/test/resources/features/authorization/AccessInfoService.feature
  qa/integration/src/test/resources/features/user/LockoutExpirationI9n.feature
  rest-api/core/pom.xml
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/exception/InternalUserOnlyExceptionMapper.java
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/exception/SelfManagedOnlyExceptionMapper.java
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/exception/mapper/KapuaAuthenticationExceptionMapper.java
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/exception/mapper/KapuaAuthorizationExceptionMapper.java
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/exception/mapper/SubjectUnauthorizedExceptionMapper.java
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/exception/model/InternalUserOnlyExceptionInfo.java
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/exception/model/MfaRequiredExceptionInfo.java
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/exception/model/SelfManagedOnlyExceptionInfo.java
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/exception/model/SubjectUnauthorizedExceptionInfo.java
  rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/exception/model/InternalUserOnlyExceptionInfoTest.java
  rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/exception/model/MfaRequiredExceptionInfoTest.java
  rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/exception/model/SelfManagedOnlyExceptionInfoTest.java
  rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/exception/model/SubjectUnauthorizedExceptionInfoTest.java
  service/api/src/main/resources/kapua-service-error-messages.properties
  service/api/src/test/java/org/eclipse/kapua/KapuaIllegalArgumentExceptionTest.java
  service/security/authentication/api/pom.xml
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/exception/AuthenticationErrorCodes.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/exception/DuplicatedPasswordCredentialException.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/exception/KapuaAuthenticationErrorCodes.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/exception/KapuaAuthenticationException.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/exception/PasswordLengthException.java
  service/security/authentication/api/src/main/resources/authentication-error-messages.properties
  service/security/authentication/api/src/test/java/org/eclipse/kapua/service/authentication/exception/KapuaAuthenticationExceptionTest.java
  service/security/authorization/api/pom.xml
  service/security/authorization/api/src/main/java/org/eclipse/kapua/service/authorization/exception/InternalUserOnlyException.java
  service/security/authorization/api/src/main/java/org/eclipse/kapua/service/authorization/exception/KapuaAuthorizationErrorCodes.java
  service/security/authorization/api/src/main/java/org/eclipse/kapua/service/authorization/exception/KapuaAuthorizationException.java
  service/security/authorization/api/src/main/java/org/eclipse/kapua/service/authorization/exception/SelfManagedOnlyException.java
  service/security/authorization/api/src/main/java/org/eclipse/kapua/service/authorization/exception/SubjectUnauthorizedException.java
  service/security/authorization/api/src/main/resources/authorization-error-messages.properties
  service/security/authorization/api/src/test/java/org/eclipse/kapua/service/authorization/exception/KapuaAuthorizationExceptionTest.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/MfaOptionServiceImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/AuthenticationServiceShiroImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/KapuaAuthenticationException.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/exceptions/AuthenticationRuntimeException.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/exceptions/JwtCertificateNotFoundException.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/utils/AuthenticationUtils.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/access/shiro/AccessInfoServiceImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/shiro/AuthorizationServiceImpl.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/shiro/KapuaAuthenticationExceptionTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/shiro/exceptions/AuthenticationRuntimeExceptionTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/shiro/exceptions/JwtCertificateNotFoundExceptionTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/shiro/exception/InternalUserOnlyExceptionTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/shiro/exception/KapuaAuthorizationExceptionTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/shiro/exception/SelfManagedOnlyExceptionTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authorization/shiro/exception/SubjectUnauthorizedExceptionTest.java
Labels: Enhancement
