Repository eclipse-kapua/kapua, pull requests merged in 2022-01, with the labels that each got.

#3486 Set log4j dependency version from 2.17.0 to 2.17.1 - CVE-2021-44832
  pom.xml
Labels: Dependencies

#3489 Bump version of Slf4j from 1.7.30 to 1.7.33
  pom.xml
Labels: Dependencies

#3490 Set Owasp Encoder dependency version to 1.2.3
  pom.xml
Labels: Dependencies

#3491 Bump Commons Io version from 2.4 to 2.11.0 - CVE-2021-29425
  pom.xml
Labels: Dependencies

#3492 Fixed translator tests syntax
  translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
Labels: Test

#3493 Fixed failing Scheduler tests
  service/scheduler/test/src/test/java/org/eclipse/kapua/service/scheduler/test/SchedulerLocatorConfiguration.java
Labels: Test

#3488 Bump shiro dependencies version from 1.5.3 to 1.8.0 - CVE-2020-13933 CVE-2021-41303
  console/web/src/main/resources/shiro.ini
  pom.xml
Labels: Dependencies

#3494 Add Scheduler and Translator tests in github action
  .github/workflows/github-actions.yaml
Labels: Test

#3496 Excluded c3p0 dependencies from Quartz scheduler
  pom.xml
Labels: Dependencies

#3495 Bump version of jetty dependencies 9.2.x and 9.4.x to latest patch version
  pom.xml
Labels: Dependencies

#3431 Certificate - move bindings to local module
  assembly/broker/configurations/locator.xml
  broker/core/src/test/resources/locator.xml
  console/web/src/main/resources/locator.xml
  consumer/lifecycle-app/src/main/resources/locator.xml
  consumer/telemetry-app/src/main/resources/locator.xml
  job-engine/app/web/src/main/resources/locator.xml
  qa/integration/src/test/resources/locator.xml
  rest-api/web/src/main/resources/locator.xml
  service/security/certificate/internal/src/main/java/org/eclipse/kapua/service/certificate/info/internal/CertificateInfoFactoryImpl.java
  service/security/certificate/internal/src/main/java/org/eclipse/kapua/service/certificate/info/internal/CertificateInfoModule.java
  service/security/certificate/internal/src/main/java/org/eclipse/kapua/service/certificate/info/internal/CertificateInfoServiceImpl.java
  service/security/certificate/internal/src/main/java/org/eclipse/kapua/service/certificate/internal/CertificateFactoryImpl.java
  service/security/certificate/internal/src/main/java/org/eclipse/kapua/service/certificate/internal/CertificateModule.java
  service/security/certificate/internal/src/main/java/org/eclipse/kapua/service/certificate/internal/CertificateServiceImpl.java
  service/security/test-steps/src/main/java/org/eclipse/kapua/service/authentication/steps/AuthenticationServiceSteps.java
Labels: Enhancement

#3471 ServiceDAO.query list support
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/ServiceDAO.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/shared/util/GwtKapuaDeviceModelConverter.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/server/GwtJobTargetServiceImpl.java
  job-engine/commons/src/main/java/org/eclipse/kapua/job/engine/commons/model/JobTargetSublist.java
  job-engine/commons/src/main/java/org/eclipse/kapua/job/engine/commons/operation/DefaultTargetReader.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/JobEngineServiceJbatch.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/listener/KapuaJobListener.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/JobExecutions.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Roles.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/AuthenticationServiceShiroImpl.java
Labels: Enhancement

#3498 Fixed message-broker container name when launched in debug mode
  deployment/docker/compose/extras/docker-compose.broker-debug.yml
Labels: Bug

#3501 FIxed original cause eaten in process on connect.
  service/device/management/job/internal/src/main/java/org/eclipse/kapua/service/device/management/job/scheduler/internal/JobDeviceManagementTriggerManagerServiceImpl.java
Labels: Bug
