Repository eclipse-kapua/kapua, pull requests merged in 2022-09, with the labels that each got.

#3597 Added SECURITY.md file
  SECURITY.md
Labels: Enhancement, Documentation

#3600 Added Eclipse Dash Tool step in Kapua CI GitHub workflow
  .github/workflows/github-actions.yaml
Labels: Enhancement, Dependencies

#3584 Set loglevel for Cache Configuration Printer
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/cache/KapuaCacheManager.java
Labels: Bug
