Repository eclipse-kapua/kapua, pull requests merged in 2022-10, with the labels that each got.

#3622 Upgrade GitAction actions versions 1.x
  .github/workflows/kapua-ci.yaml
Labels: Enhancement, build

#3607 Entirely show the new credential mask even with allowed special chars
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/client/tabs/credentials/CredentialAddDialog.java
Labels: Bug, Console GWT

#3558 Events broker update
  assembly/events-broker/configurations/artemis-roles.properties
  assembly/events-broker/configurations/artemis-users.properties
  assembly/events-broker/configurations/artemis.profile
  assembly/events-broker/configurations/bootstrap.xml
  assembly/events-broker/configurations/broker.xml
  assembly/events-broker/configurations/logging.properties
  assembly/events-broker/configurations/login.config
  assembly/events-broker/descriptors/kapua-events-broker.xml
  assembly/events-broker/docker/Dockerfile
  assembly/events-broker/entrypoint/run-artemis
  assembly/events-broker/entrypoint/run-event-broker
  assembly/events-broker/pom.xml
  pom.xml
Labels: Enhancement, Dependencies

#3626 Upgraded Shiro dependencies from 1.8.0 to 1.10.0 - CVE-2022-40664 CVE-2022-32532
  pom.xml
Labels: CQ approved, Dependencies

#3638 Exclude `jakarta.security.auth.message-api` dependency from Artemis dependencies
  assembly/events-broker/pom.xml
  broker/client/pom.xml
  broker/core/pom.xml
  consumer/commons/pom.xml
  consumer/telemetry/pom.xml
  pom.xml
  qa/common/pom.xml
  qa/integration/pom.xml
  qa/pom.xml
Labels: Dependencies

#3641 Refactored KapuaFileUtilsTest
  commons/src/test/java/org/eclipse/kapua/commons/util/KapuaFileUtilsTest.java
Labels: Enhancement, Test

#3636 Upgraded Spring dependencies from 5.3.8 to 5.3.23 - CVE-2021-22096 CVE-2022-22950 CVE-2022-22965 CVE-2022-22968 CVE-2022-22970 CVE-2022-22971
  pom.xml
Labels: CQ approved, Dependencies

#3635 Upgraded Netty dependencies from 4.1.60.Final to 4.1.84.Final - CVE-2021-21409 CVE-2021-37136 CVE-2021-37137 CVE-2021-43797 CVE-2022-24823
  assembly/broker/descriptors/kapua-broker.xml
  pom.xml
Labels: CQ approved, Dependencies

#3645 Upgraded Jackson dependencies from 2.13.1 to 2.13.4/2.13.4.2 - CVE-2020-36518 CVE-2022-42003 CVE-2022-42004
  pom.xml
Labels: CQ approved, Dependencies

#3646 Upgraded Snakeyaml dependency from 1.28 to 1.33 - CVE-2022-38752 CVE-2022-38751 CVE-2022-38750 CVE-2022-38749
  pom.xml
Labels: CQ approved, Dependencies

#3649 Upgraded JUnit dependency from 4.12 to 4.13.2 - CVE-2020-15250
  pom.xml
Labels: CQ approved, Dependencies

#3595 Disable the Swagger UI if needed
  deployment/docker/compose/docker-compose.yml
  deployment/docker/unix/docker-deploy.sh
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/filter/SwaggerUIFilter.java
  rest-api/web/src/main/webapp/WEB-INF/web.xml
Labels: Enhancement, rest-api

#3628 Test classes not longer extending Assert for broker tests
  broker/api/src/test/java/org/eclipse/kapua/broker/BrokerDomainTest.java
  broker/api/src/test/java/org/eclipse/kapua/broker/BrokerDomainsTest.java
  broker/client/src/test/java/org/eclipse/kapua/broker/client/protocol/ProtocolDescriptorTest.java
  client/gateway/api/src/test/java/org/eclipse/kapua/client/gateway/CredentialsTest.java
  client/gateway/api/src/test/java/org/eclipse/kapua/client/gateway/PayloadTest.java
  client/gateway/api/src/test/java/org/eclipse/kapua/client/gateway/TopicTest.java
  client/gateway/api/src/test/java/org/eclipse/kapua/client/gateway/TransmissionExceptionTest.java
  client/gateway/profile/kura/src/test/java/org/eclipse/kapua/client/gateway/kura/KuraBinaryPayloadCodecTest.java
  client/gateway/profile/kura/src/test/java/org/eclipse/kapua/client/gateway/kura/KuraBirthCertificateModuleTest.java
  client/gateway/profile/kura/src/test/java/org/eclipse/kapua/client/gateway/kura/KuraNamespaceTest.java
  client/gateway/profile/kura/src/test/java/org/eclipse/kapua/client/gateway/kura/internal/MetricsTest.java
  client/gateway/profile/kura/src/test/java/org/eclipse/kapua/client/gateway/profile/kura/KuraMqttProfileTest.java
  client/gateway/provider/fuse/src/test/java/org/eclipse/kapua/client/gateway/mqtt/fuse/FuseChannelTest.java
  client/gateway/provider/fuse/src/test/java/org/eclipse/kapua/client/gateway/mqtt/fuse/internal/CallbacksTest.java
  client/gateway/provider/mqtt/src/test/java/org/eclipse/kapua/client/gateway/mqtt/AbstractMqttChannelTest.java
  client/gateway/provider/paho/src/test/java/org/eclipse/kapua/client/gateway/mqtt/paho/internal/ListenersTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/AbstractClientTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/DefaultApplicationTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/DefaultClientTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/DefaultDataTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/util/BuffersTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/util/FuturesTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/util/MoreExecutorsTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/util/StringsTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/util/TransportAsyncTest.java
  client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/util/TransportProxyTest.java
Labels: Enhancement, Test

#3630 Commons - test fixes (style, not substance)
  commons/src/test/java/org/eclipse/kapua/commons/model/query/AbstractKapuaQueryTest.java
  commons/src/test/java/org/eclipse/kapua/commons/model/query/FieldSortCriteriaImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/model/query/predicate/AndPredicateImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/model/query/predicate/AttributePredicateImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/model/query/predicate/OrPredicateImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/service/event/store/internal/EventStoreFactoryImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/service/event/store/internal/EventStoreQueryImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/service/event/store/internal/EventStoreRecordCreatorImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/service/event/store/internal/EventStoreRecordImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/service/internal/cache/ComposedKeyTest.java
  commons/src/test/java/org/eclipse/kapua/commons/service/internal/cache/EntityCacheTest.java
  commons/src/test/java/org/eclipse/kapua/commons/service/internal/cache/KapuaCacheManagerTest.java
  commons/src/test/java/org/eclipse/kapua/commons/service/internal/cache/NamedEntityCacheTest.java
  commons/src/test/java/org/eclipse/kapua/commons/service/internal/cache/dummy/CacheManagerTest.java
  commons/src/test/java/org/eclipse/kapua/commons/service/internal/cache/dummy/CacheTest.java
  commons/src/test/java/org/eclipse/kapua/commons/service/internal/cache/dummy/CachingProviderTest.java
  commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
  commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractKapuaSettingTest.java
  commons/src/test/java/org/eclipse/kapua/commons/setting/EnvFriendlyConfigurationTest.java
  commons/src/test/java/org/eclipse/kapua/commons/setting/KapuaSettingErrorCodesTest.java
  commons/src/test/java/org/eclipse/kapua/commons/setting/KapuaSettingExceptionTest.java
  commons/src/test/java/org/eclipse/kapua/commons/setting/SimpleSettingKeyTest.java
  commons/src/test/java/org/eclipse/kapua/commons/setting/system/SystemSettingKeyTest.java
  commons/src/test/java/org/eclipse/kapua/commons/setting/system/SystemSettingTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/ArgumentValidatorTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/ClassUtilTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/CommonsValidationRegexTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/CryptoUtilTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/KapuaDateUtilsTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/KapuaDelayUtilTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/KapuaErrorCodesTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/KapuaExceptionUtilsTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/KapuaFileUtilsTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/PropertiesUtilsTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/ResourceUtilsTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/SemanticVersionTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/StringUtilTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/SystemUtilsTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/log/ConfigurationPrinterTest.java
  commons/src/test/java/org/eclipse/kapua/commons/util/xml/XmlNamespaceFilterTest.java
Labels: Enhancement, Test

#3647 Upgraded Logback dependencies from 1.2.3 to 1.2.11 - CVE-2021-42550
  pom.xml
  simulator-kura/pom.xml
Labels: CQ pending, Dependencies

#3642 Upgraded Spring Security from 5.5.1 to 5.7.4 in Kapua 2.x - CVE-2022-22976 CVE-2022-22978
  pom.xml
Labels: CQ approved, Dependencies

#3629 Commons - importing Assert instead of extending
  commons/src/test/java/org/eclipse/kapua/commons/about/AboutEntryTest.java
  commons/src/test/java/org/eclipse/kapua/commons/about/AboutScannerTest.java
  commons/src/test/java/org/eclipse/kapua/commons/cache/LocalCacheTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/KapuaConfigurableServiceSchemaUtilsTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/KapuaConfigurableServiceSchemaUtilsWithResourcesTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/ServiceComponentConfigurationImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/ServiceConfigImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/ServiceConfigQueryImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/ServiceConfigurationCreatorImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/ServiceConfigurationFactoryImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/ValueTokenizerTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/EmptyTocdTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/KapuaMetatypeFactoryImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/ObjectFactoryImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/PasswordTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/TadImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/TattributeImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/TdesignateImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/TiconImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/TmetadataImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/TobjectImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/TocdImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/ToptionImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/crypto/CryptoUtilTest.java
  commons/src/test/java/org/eclipse/kapua/commons/event/RaiseServiceEventInterceptorTest.java
  commons/src/test/java/org/eclipse/kapua/commons/event/ServiceEntryTest.java
  commons/src/test/java/org/eclipse/kapua/commons/event/ServiceEventClientConfigurationTest.java
  commons/src/test/java/org/eclipse/kapua/commons/event/ServiceEventModuleConfigurationTest.java
  commons/src/test/java/org/eclipse/kapua/commons/event/ServiceEventScopeTest.java
  commons/src/test/java/org/eclipse/kapua/commons/metric/MetricServiceFactoryTest.java
  commons/src/test/java/org/eclipse/kapua/commons/metric/MetricsServiceImplTest.java
  commons/src/test/java/org/eclipse/kapua/commons/model/AbstractKapuaEntityCreatorTest.java
  commons/src/test/java/org/eclipse/kapua/commons/model/AbstractKapuaEntityTest.java
  commons/src/test/java/org/eclipse/kapua/commons/model/AbstractKapuaNamedEntityCreatorTest.java
  commons/src/test/java/org/eclipse/kapua/commons/model/AbstractKapuaNamedEntityTest.java
  commons/src/test/java/org/eclipse/kapua/commons/model/AbstractKapuaUpdatableEntityCreatorTest.java
  commons/src/test/java/org/eclipse/kapua/commons/model/AbstractKapuaUpdatableEntityTest.java
  commons/src/test/java/org/eclipse/kapua/commons/model/id/KapuaEidConverterTest.java
  commons/src/test/java/org/eclipse/kapua/commons/model/id/KapuaEidTest.java
  commons/src/test/java/org/eclipse/kapua/commons/model/id/KapuaIdFactoryImplTest.java
Labels: Enhancement, Test

#3631 Messages - better testing syntax
  message/internal/src/test/java/org/eclipse/kapua/message/internal/KapuaChannelTest.java
  message/internal/src/test/java/org/eclipse/kapua/message/internal/KapuaDataMessageFactoryTest.java
  message/internal/src/test/java/org/eclipse/kapua/message/internal/KapuaMessageFactoryTest.java
  message/internal/src/test/java/org/eclipse/kapua/message/internal/KapuaMessageTest.java
  message/internal/src/test/java/org/eclipse/kapua/message/internal/KapuaPayloadTest.java
  message/internal/src/test/java/org/eclipse/kapua/message/internal/KapuaPositionTest.java
  message/internal/src/test/java/org/eclipse/kapua/message/internal/MessageExceptionTest.java
  message/internal/src/test/java/org/eclipse/kapua/message/internal/device/data/KapuaDeviceDataTest.java
  message/internal/src/test/java/org/eclipse/kapua/message/internal/device/lifecycle/KapuaAppsMessageTest.java
  message/internal/src/test/java/org/eclipse/kapua/message/internal/device/lifecycle/KapuaBirthMessageTest.java
  message/internal/src/test/java/org/eclipse/kapua/message/internal/device/lifecycle/KapuaDisconnectMessageTest.java
  message/internal/src/test/java/org/eclipse/kapua/message/internal/device/lifecycle/KapuaMissingMessageTest.java
  message/internal/src/test/java/org/eclipse/kapua/message/internal/xml/KapuaMetricTest.java
  message/internal/src/test/java/org/eclipse/kapua/message/internal/xml/KapuaMetricsMapAdapterTest.java
  qa/integration-steps/src/main/java/org/eclipse/kapua/qa/integration/steps/RestClientSteps.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/AccessInfoCreatorImplTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/AccessInfoDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/AccessPermissionDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/AccessPermissionImplTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/AccessRoleDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/AccessTokenAuthenticationRealmTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/AccessTokenCredentialsMatcherTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/AccessTokenDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/AdminAuthenticationLogicTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/ApiKeyAuthenticatingRealmTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/AuthenticationEntityManagerFactoryTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/AuthenticationLogicTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/AuthorizationEntityManagerFactoryTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/CredentialDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/DataStorageMessageProcessorTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/DefaultAuthenticatorTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/DeviceManagementNotificationMessageProcessorTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/DomainDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/EventStoreDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/EventStoreServiceImplTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/GroupDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/JsonServiceEventMarshalerTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/JwtAuthenticatingRealmTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/KapuaApplicationBrokerFilterTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/KapuaBrokerSecurityPluginTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/KapuaIdAdapterTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/KapuaLocatorTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/KapuaSecurityBrokerFilterTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/KapuaSessionCleanupFilterTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/KapuaTscalarAdapterTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/MetatypeXmlRegistryTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/MfaOptionDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/MqttClientTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/PermissionImplTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/RoleDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/RolePermissionDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/RolePermissionFactoryTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/RolePermissionImplTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/ScratchCodeDAOTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/UserAuthenticationLogicTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/UserPassAuthenticatingRealmTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/XmlServiceEventMarshalerTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/service/datastoreJunit/AbstractMessageStoreServiceTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/service/datastoreJunit/MessageStoreServiceSslTest.java
Labels: Enhancement, Test

#3652 Upgraded Httpcomponents to latest 4.x
  pom.xml
Labels: Dependencies

#3637 Upgraded Springboot dependencies from 2.5.2 to 2.5.14 in Kapua 2.x - CVE-2022-22965
  pom.xml
Labels: Dependencies

#3653 Upgraded Springboot dependencies from 2.5.2 to 2.5.14 in Kapua 2.x - CVE-2022-22965 - errata
  pom.xml
Labels: Dependencies

#3643 Upgraded Spring Security from 4.1.3.RELEASE to 4.2.20.RELEASE in Kapua 1.x - CVE-2018-1199 CVE-2020-5408
  pom.xml
Labels: Dependencies
