Repository eclipse-kapua/kapua, pull requests merged in 2023-09, with the labels that each got.

#3851 fix(jobEngine): Changed 'jbtc_job_status.obj' type to longblob to support changes made in eclipse/kapua#3828
  job-engine/jbatch/src/main/resources/liquibase/2.0.0/changelog-job-engine-2.0.0.xml
  job-engine/jbatch/src/main/resources/liquibase/2.0.0/job_engine_jbatch-job_status.xml
  job-engine/jbatch/src/main/resources/liquibase/changelog-job-engine-master.xml
Labels: Bug

#3853 Bump `shiro` version from `1.10.0` to `1.12.0` - `CVE-2023-34478`
  pom.xml
Labels: CQ approved, Dependencies

#3861 chng(job): Changeg max length for JobStepProperty.value from 100MB to 10MB
  service/job/internal/src/main/resources/job-service-settings.properties
Labels: Enhancement

#3860 Upgrade camel to 3.21
  assembly/consumer/pom.xml
  assembly/service/pom.xml
  consumer/lifecycle-app/pom.xml
  consumer/lifecycle/pom.xml
  consumer/pom.xml
  consumer/telemetry-app/pom.xml
  consumer/telemetry/pom.xml
  pom.xml
  qa/common/pom.xml
  qa/integration/pom.xml
  service/authentication-app/pom.xml
  service/authentication/pom.xml
  service/camel/pom.xml
Labels: Dependencies

#3862 amqp selector to improve subscription messages filtering
  broker/artemis/plugin/src/main/java/org/eclipse/kapua/broker/artemis/plugin/security/ServerPlugin.java
  consumer/lifecycle-app/src/main/resources/camel/camel.xml
  consumer/telemetry-app/src/main/resources/camel/camel.xml
  service/client/src/main/java/org/eclipse/kapua/service/client/message/MessageConstants.java
Labels: Enhancement

#3864 Bumped version of Apache Commons Fileupload from 1.4 to 1.5 - CVE-2023-24998
  pom.xml
Labels: Dependencies

#3866 dependency: bumped version of Apache Commons Compress from 1.22 to 1.24.0 - CVE-2023-42503
  pom.xml
Labels: Dependencies

#3867 dependency: bumped Eclipse Jetty version from 9.4.50.v20221201 to 9.4.52.v20230823 - CVE-2023-26049 CVE-2023-36479 CVE-2023-40167
  pom.xml
Labels: Dependencies

#3868 dependency: bumped Google Guava version from 30.1-jre to 32.1.2-jre - CVE-2020-8908 CVE-2023-2976
  pom.xml
Labels: Dependencies

#3869 dependency: bumped Snakeyaml from 1.33 to 2.2 - CVE-2022-1471
  pom.xml
Labels: Dependencies

#3865 FIX - Fixed some wrong written tests
  qa/integration/src/test/resources/features/account/AccountCredentialService.feature
  qa/integration/src/test/resources/features/broker/acl/BrokerACLI9n.feature
  qa/integration/src/test/resources/features/jobScheduling/TriggerServiceI9n.feature
  qa/integration/src/test/resources/features/user/UserPermissionI9n.feature
  qa/integration/src/test/resources/features/user/UserRoleServiceI9n.feature
  service/job/test/src/test/resources/features/JobService.feature
  service/tag/test/src/test/resources/features/TagService.feature
  translator/test/src/test/resources/features/TranslatorUnitTests.feature
Labels: Test

#3880 dependency: bumped Jackson dependencies from 2.13.4 to 2.15.2
  pom.xml
Labels: Dependencies
