Repository eclipse-kapua/kapua, pull requests merged in 2023-06, with the labels that each got.

#3790 FIX - fixed missing properties on device Event openAPI.yaml schema definition
  rest-api/resources/src/main/resources/openapi/deviceEvent/deviceEvent.yaml
Labels: Bug, Documentation

#3798 Fix OpenID configuration path
  plug-ins/sso/openid-connect/provider/src/main/java/org/eclipse/kapua/plugin/sso/openid/provider/OpenIDUtils.java
Labels: Bug

#3805 FIX - Added exception mapper for duplicate pass exception
  commons-rest/errors/src/main/java/org/eclipse/kapua/commons/rest/errors/KapuaDuplicatePasswordCredentialExceptionMapper.java
Labels: Bug, REST API
