Repository eclipse-kapua/kapua, pull requests merged in 2023-08, with the labels that each got.

#3836 fake commit
  message/api/src/main/java/org/eclipse/kapua/message/KapuaMessage.java
Labels: build

#3838 FIX- Introduce sonarCloud decoration on PRs
  .github/workflows/sonarCloud-scan.yaml
Labels: Bug, build

#3843 Feature - Bump OpenApi version from 3.0.2 to 3.0.3
  rest-api/resources/src/main/resources/openapi/openapi.yaml
Labels: Enhancement, REST API

#3844 Feature - Bump swagger-ui from 3.52.4 to 4.19.1
  pom.xml
Labels: CQ approved, Dependencies

#3852 fix(jobEngine): added missing mappings in JobEngine locator.xml for DeviceConnectionService and DeviceConnectionFactory
  job-engine/app/web/src/main/resources/locator.xml
Labels: Bug

#3848 Fix JobEngineException log messages
  job-engine/api/pom.xml
  job-engine/api/src/main/java/org/eclipse/kapua/job/engine/exception/CleanJobDataException.java
  job-engine/api/src/main/java/org/eclipse/kapua/job/engine/exception/JobEngineErrorCodes.java
  job-engine/api/src/main/java/org/eclipse/kapua/job/engine/exception/JobScopedEngineException.java
  job-engine/api/src/main/resources/job-engine-service-error-messages.properties
  job-engine/api/src/test/java/org/eclipse/kapua/job/engine/exception/JobEngineExceptionTest.java
  job-engine/api/src/test/java/org/eclipse/kapua/job/engine/exception/model/TestCodesJobEngineException.java
  job-engine/client/src/main/java/org/eclipse/kapua/job/engine/client/JobEngineServiceClient.java
Labels: Bug

#3855 feat(docker): set jvm 11 to reference latest version
  assembly/java-base/docker/Dockerfile
Labels: Bug

#3845 Feature - Bump swagger-ui from 4.19.1 to 5.3.1
  pom.xml
Labels: CQ approved, Dependencies

#3856 Set fixed version of `commons-configuration2` dependency to `2.9.0`
  pom.xml
Labels: Dependencies
