Repository eclipse-kapua/kapua, pull requests merged in 2023-07, with the labels that each got.

#3806 FIX - changed the logger properties for KapuaDuplicatePasswordCredentialExceptionMapper
  commons-rest/errors/src/main/java/org/eclipse/kapua/commons/rest/errors/KapuaDuplicatePasswordCredentialExceptionMapper.java
Labels: Bug

#3781 feat(jobs): Added JobStepProperty overrides on JobEngineStartOptions
  consumer/lifecycle-app/src/main/java/org/eclipse/kapua/consumer/lifecycle/LifecycleJAXBContextProvider.java
  job-engine/api/src/main/java/org/eclipse/kapua/job/engine/JobStartOptions.java
  job-engine/app/core/pom.xml
  job-engine/app/core/src/main/java/org/eclipse/kapua/job/engine/app/core/jackson/ObjectMapperProvider.java
  job-engine/app/core/src/main/java/org/eclipse/kapua/job/engine/app/core/jackson/mixin/JobStepPropertyMixin.java
  job-engine/app/web/src/main/java/org/eclipse/kapua/job/engine/app/web/jaxb/JaxbContextResolver.java
  job-engine/client/src/main/java/org/eclipse/kapua/job/engine/client/JobStartOptionsClient.java
  job-engine/commons/src/main/java/org/eclipse/kapua/job/engine/commons/model/JobStepPropertiesOverrides.java
  job-engine/commons/src/main/java/org/eclipse/kapua/job/engine/commons/wrappers/JobContextPropertyNames.java
  job-engine/commons/src/main/java/org/eclipse/kapua/job/engine/commons/wrappers/JobContextWrapper.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/JobStartOptionsImpl.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/driver/JbatchDriver.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/driver/utils/JobDefinitionBuildUtils.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/listener/KapuaJobListener.java
  qa/common/src/main/java/org/eclipse/kapua/qa/common/TestJAXBContextProvider.java
Labels: Enhancement

#3807 FIX - Added missing exception mapper for KapuapasswordLengthException
  commons-rest/errors/src/main/java/org/eclipse/kapua/commons/rest/errors/KapuaPasswordLengthExceptionMapper.java
Labels: Bug

#3809 feat(openapi): add versioning to openapi.yaml definition file
  rest-api/resources/src/main/resources/openapi/openapi.yaml
Labels: Enhancement, Documentation

#3792 fix(deployment): Added missing `--help` options and fixed usage print do `docker-deploy.sh`
  deployment/docker/unix/docker-deploy.sh
Labels: Bug

#3808 Fix - Inserted device package fields limits
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/packages/dialog/PackageInstallDialog.java
  service/device/management/packages/internal/src/main/java/org/eclipse/kapua/service/device/management/packages/internal/DevicePackageManagementServiceImpl.java
Labels: Bug

#3791 feat(deployment): Add options to enable JMX on containers
  assembly/api/docker/Dockerfile
  assembly/broker-artemis/configurations/artemis.profile
  assembly/console/docker/Dockerfile
  assembly/consumer/lifecycle/docker/Dockerfile
  assembly/consumer/lifecycle/entrypoint/run-consumer-lifecycle
  assembly/consumer/telemetry/docker/Dockerfile
  assembly/consumer/telemetry/entrypoint/run-consumer-telemetry
  assembly/job-engine/docker/Dockerfile
  assembly/service/authentication/entrypoint/run-service-authentication
  deployment/docker/README.md
  deployment/docker/compose/docker-compose.yml
  deployment/docker/compose/extras/docker-compose.broker-debug.yml
  deployment/docker/compose/extras/docker-compose.broker-jmx.yml
  deployment/docker/compose/extras/docker-compose.console-jmx.yml
  deployment/docker/compose/extras/docker-compose.consumer-lifecycle-debug.yml
  deployment/docker/compose/extras/docker-compose.consumer-lifecycle-jmx.yml
  deployment/docker/compose/extras/docker-compose.consumer-telemetry-debug.yml
  deployment/docker/compose/extras/docker-compose.consumer-telemetry-jmx.yml
  deployment/docker/compose/extras/docker-compose.job-engine-jmx.yml
  deployment/docker/compose/extras/docker-compose.rest-jmx.yml
  deployment/docker/compose/extras/docker-compose.service-authentication-debug.yml
  deployment/docker/compose/extras/docker-compose.service-authentication-jmx.yml
  deployment/docker/unix/docker-deploy.sh
  deployment/docker/win/docker-deploy.ps1
  qa/integration-steps/src/main/java/org/eclipse/kapua/qa/integration/steps/DockerSteps.java
Labels: Enhancement

#3812 Add maximum length to `configuration put` step definition
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/client/steps/JobStepAddDialog.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/step/internal/JobStepServiceImpl.java
Labels: Bug

#3820 Fix Jenkins Javadoc build to do bad Javadoc
  pom.xml
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/model/ByteArrayParam.java
Labels: Bug, build

#3814 FIX - Cleanup of readme file to fix badges
  README.md
Labels: Bug, Documentation

#3801 Feature provide compiled version of protobuf payload
  build-tools/src/main/resources/checkstyle/kapua.suppressions.xml
  client/gateway/profile/kura/pom.xml
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/KuraBinaryPayloadCodec.java
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/KuraBirthCertificateModule.java
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/internal/Metrics.java
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/proto/KuraPayloadProto.java
  client/gateway/profile/kura/src/test/java/org/eclipse/kapua/client/gateway/kura/internal/MetricsTest.java
  pom.xml
  qa/common/src/main/java/org/eclipse/kapua/qa/common/SimulatedDeviceApplication.java
  service/device/call/kura/pom.xml
  service/device/call/kura/src/main/java/org/eclipse/kapua/service/device/call/message/kura/proto/KuraPayloadProto.java
  service/device/call/kura/src/main/protobuf/kurapayload.proto
  service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/KuraDevice.java
  simulator-kura/pom.xml
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/app/Request.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/app/Sender.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/app/data/PeriodicGenerator.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/app/data/SimplePeriodicGenerator.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/payload/Metrics.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/proto/KuraPayloadProto.java
  simulator-kura/src/test/java/org/eclipse/kapua/kura/simulator/main/simulation/AppTest.java
Labels: CQ approved

#3821 Fix to https://github.com/eclipse/kapua/pull/3801
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/proto/KuraPayloadProto.java
  service/device/call/kura/src/main/java/org/eclipse/kapua/service/device/call/message/kura/proto/KuraPayloadProto.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/proto/KuraPayloadProto.java
Labels: Bug

#3827 Fixed handling of jobStepProperty null value when validating length
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/step/internal/JobStepServiceImpl.java
Labels: Bug

#3831 fix(docker): temporaneally set specific JVM 11 version to '11.0.19.07-4.el8' to fix start issue
  assembly/java-base/docker/Dockerfile
Labels: Bug

#3828 feat(job): Increased length of `JobStepProperty.propertyValue` field to allow up to 4GB
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/client/steps/JobStepAddDialog.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/server/GwtJobStepServiceImpl.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/shared/service/GwtJobStepService.java
  extras/encryption-migrator/src/main/java/org/eclipse/kapua/extras/migrator/encryption/job/JobStepMigratorServiceImpl.java
  service/job/api/src/main/java/org/eclipse/kapua/service/job/step/JobStepService.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/internal/settings/JobServiceSettingKeys.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/internal/settings/JobServiceSettings.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/step/internal/JobStepServiceImpl.java
  service/job/internal/src/main/resources/job-service-settings.properties
  service/job/internal/src/main/resources/liquibase/2.0.0/changelog-job-2.0.0.xml
  service/job/internal/src/main/resources/liquibase/2.0.0/job_job_step_properties-value_length.xml
  service/job/internal/src/main/resources/liquibase/changelog-job-master.xml
Labels: Enhancement

#3829 Fix - Fixed retrieval of metrics with same name and different types from Console GWT
  console/module/data/src/main/java/org/eclipse/kapua/app/console/module/data/server/GwtDataServiceImpl.java
  qa/integration/src/test/resources/features/datastore/Datastore.feature
  service/datastore/test-steps/src/main/java/org/eclipse/kapua/service/datastore/steps/DatastoreSteps.java
Labels: Bug, Console GWT

#3832 feat(openapi): Added OpenAPI mappings for deviceAssetStoreService DeviceApplicationSettings
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceManagementAssets.java
  rest-api/resources/src/main/resources/openapi/deviceAsset/deviceAsset-scopeId-deviceId-_settings.yaml
  rest-api/resources/src/main/resources/openapi/deviceAsset/deviceAsset.yaml
  rest-api/resources/src/main/resources/openapi/openapi.yaml
Labels: Enhancement, Documentation

#3762 [FEATURE] Inserted a way to automatically obtain rest API url endpoint with swagger
  rest-api/resources/src/main/resources/openapi/openapi.yaml
Labels: Enhancement, Documentation
