Repository eclipse-kapua/kapua, pull requests merged in 2023-12, with the labels that each got.

#3912 FIX - CI configiguration imrovements
  .github/workflows/kapua-ci.yaml
Labels: Bug, build

#3913 FIX - recently introduced junit tests poorly written
  pom.xml
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/shiro/realm/AccessTokenCredentialsHandlerTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/shiro/realm/ApiKeyCredentialsHandlerTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/shiro/realm/JwtCredentialsHandlerTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/shiro/realm/UserPassCredentialsHandlerTest.java
  service/tag/internal/pom.xml
  service/tag/internal/src/test/java/org/eclipse/kapua/service/tag/internal/TagServiceImplTest.java
Labels: Bug, Test

#3878 upgrade Artemis broker (telemetry and events) to 2.31.2
  assembly/broker-artemis/entrypoint/run-broker
  assembly/events-broker/entrypoint/run-event-broker
  pom.xml
  service/authentication/src/main/java/org/eclipse/kapua/service/authentication/authentication/AclCreator.java
Labels: CQ pending, Dependencies

#3919 FIX - LimitExceeded value on Data Metric/Message/Client/Channel GET APIs when more than 10k documents stored
  qa/integration/src/test/resources/features/datastore/Datastore.feature
  service/commons/elasticsearch/client-api/src/main/java/org/eclipse/kapua/service/elasticsearch/client/model/ResultList.java
  service/commons/elasticsearch/client-rest/src/main/java/org/eclipse/kapua/service/elasticsearch/client/rest/ElasticsearchKeywords.java
  service/commons/elasticsearch/client-rest/src/main/java/org/eclipse/kapua/service/elasticsearch/client/rest/RestElasticsearchClient.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/AbstractRegistryFacade.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ChannelInfoRegistryFacade.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ClientInfoRegistryFacade.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MessageStoreFacade.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MetricInfoRegistryFacade.java
  service/datastore/test-steps/src/main/java/org/eclipse/kapua/service/datastore/steps/DatastoreSteps.java
Labels: Bug, REST API

#3922 fix(route): remove unused route methods
  consumer/lifecycle/src/main/java/org/eclipse/kapua/consumer/lifecycle/listener/DeviceManagementNotificationMessageProcessor.java
  consumer/telemetry/src/main/java/org/eclipse/kapua/consumer/telemetry/listener/DataStorageMessageProcessor.java
Labels: Bug

#3923 Added loggin on components startup
  extras/encryption-migrator/src/main/java/org/eclipse/kapua/extras/migrator/encryption/Application.java
  extras/liquibase-unlocker/src/main/java/org/eclipse/kapua/extras/liquibaseUnlocker/Application.java
Labels: Enhancement

#3925 feat(deviceManagement): mapped missing `DeviceInventoryContainer.state` property
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/inventory/DeviceTabInventoryTabContainer.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/server/GwtDeviceInventoryManagementServiceImpl.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/shared/model/management/inventory/GwtInventoryContainer.java
  qa/integration/src/test/resources/mqtt/INVENTORY-V1_GET_inventory_containers_reply.json
  rest-api/resources/src/main/resources/openapi/deviceInventory/deviceInventory.yaml
  service/device/call/kura/src/main/java/org/eclipse/kapua/service/device/call/kura/model/inventory/containers/KuraInventoryContainer.java
  service/device/management/inventory/api/src/main/java/org/eclipse/kapua/service/device/management/inventory/model/container/DeviceInventoryContainer.java
  service/device/management/inventory/api/src/main/java/org/eclipse/kapua/service/device/management/inventory/model/container/DeviceInventoryContainerState.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/internal/DeviceInventoryManagementServiceImpl.java
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/model/container/internal/DeviceInventoryContainerImpl.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kapua/kura/inventory/TranslatorAppInventoryContainerExecKapuaKura.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kura/kapua/inventory/AbstractTranslatorAppInventoryKuraKapua.java
Labels: Enhancement

#3927 fix(deviceManagement): fixed validation of DeviceManagementBundle id validation
  rest-api/resources/src/main/resources/openapi/deviceInventory/deviceInventory.yaml
  service/device/management/inventory/internal/src/main/java/org/eclipse/kapua/service/device/management/inventory/internal/DeviceInventoryManagementServiceImpl.java
Labels: Bug

#3929 Fix DevicePackage OpenAPI documentation
  rest-api/resources/src/main/resources/openapi/devicePackage/devicePackage-scopeId-deviceId-_download.yaml
  rest-api/resources/src/main/resources/openapi/devicePackage/devicePackage-scopeId-deviceId-_uninstall.yaml
  rest-api/resources/src/main/resources/openapi/devicePackage/devicePackage.yaml
  rest-api/resources/src/main/resources/openapi/openapi.yaml
Labels: Bug

#3930 fix(openapi): added missing DeviceInventory schermas to root openapi.yaml
  rest-api/resources/src/main/resources/openapi/openapi.yaml
Labels: Bug
