Repository eclipse-kapua/kapua, pull requests merged in 2023-02, with the labels that each got.

#3709 Wrong example for endpoint PUT Rest API method
  rest-api/resources/src/main/resources/openapi/endpointInfo/endpointInfo-scopeId-endpointInfoId.yaml
Labels: rest-api, Documentation

#3697 Improve handling and checking of values in Birth Message
  qa/common/src/main/java/org/eclipse/kapua/qa/common/BasicSteps.java
  qa/common/src/main/java/org/eclipse/kapua/qa/common/TestBase.java
  qa/common/src/main/java/org/eclipse/kapua/qa/common/cucumber/CucDevice.java
  qa/common/src/main/java/org/eclipse/kapua/qa/common/cucumber/CucDeviceExtendedProperty.java
  qa/integration/src/test/resources/features/datastore/Datastore.feature
  qa/integration/src/test/resources/features/device/DeviceServiceI9n.feature
  service/datastore/test-steps/src/main/java/org/eclipse/kapua/service/datastore/steps/DatastoreSteps.java
  service/device/registry/api/src/main/java/org/eclipse/kapua/service/device/registry/KapuaDeviceRegistrySettingKeys.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/DeviceServiceModule.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/KapuaDeviceRegistrySettings.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/common/DeviceValidation.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/internal/DeviceExtendedPropertyImpl.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/internal/DeviceImpl.java
  service/device/registry/internal/src/main/resources/kapua-device-registry-setting.properties
  service/device/registry/internal/src/main/resources/liquibase/2.0.0/changelog-device-2.0.0.xml
  service/device/registry/internal/src/main/resources/liquibase/2.0.0/device-add-clob-ip-if-columns.xml
  service/device/registry/internal/src/main/resources/liquibase/changelog-device-master.xml
  service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/BrokerSteps.java
  service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
  service/job/test-steps/src/main/java/org/eclipse/kapua/service/job/steps/JobTargetServiceSteps.java
Labels: Bug

#3712 Return an ordered list of service configurations with REST API
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/ServiceConfigurations.java
Labels: Enhancement

#3714 Added support for askTotalCount on Roles-related endpoints
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/AccessPermissions.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/AccessRoles.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Roles.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/RolesPermissions.java
  rest-api/resources/src/main/resources/openapi/accessInfo/accessInfo-scopeId-accessInfoId-permissions.yaml
  rest-api/resources/src/main/resources/openapi/accessInfo/accessInfo-scopeId-accessInfoId-roles.yaml
  rest-api/resources/src/main/resources/openapi/role/role-scopeId.yaml
  rest-api/resources/src/main/resources/openapi/role/rolePermission-scopeId-roleId.yaml
Labels: Bug, REST API

#3715 Fix - updated swagger UI version
  pom.xml
Labels: CQ approved, Dependencies

#3722 Fix `MqttClient` exception messages
  transport/mqtt/pom.xml
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/exception/MqttClientConnectException.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/exception/MqttClientErrorCodes.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/exception/MqttClientException.java
  transport/mqtt/src/main/java/org/eclipse/kapua/transport/mqtt/exception/MqttClientPublishException.java
  transport/mqtt/src/main/resources/mqtt-client-error-messages.properties
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/mqtt/exception/MqttClientAlreadyConnectedExceptionTest.java
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/mqtt/exception/MqttClientCallbackSetExceptionTest.java
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/mqtt/exception/MqttClientCleanExceptionTest.java
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/mqtt/exception/MqttClientConnectExceptionTest.java
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/mqtt/exception/MqttClientDisconnectExceptionTest.java
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/mqtt/exception/MqttClientErrorCodesTest.java
  transport/mqtt/src/test/java/org/eclipse/kapua/transport/mqtt/test/mqtt/exception/MqttClientExceptionTest.java
Labels: Bug

#3724 Added NPE checking on JobEngineClient response error handling
  job-engine/client/src/main/java/org/eclipse/kapua/job/engine/client/JobEngineServiceClient.java
Labels: Bug

#3723 [ECED-1521] - Inserted time range filter on job execution rest endpoint
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/JobExecutions.java
  rest-api/resources/src/main/resources/openapi/jobExecution/job-scopeId-jobId-executions.yaml
Labels: Enhancement, REST API
