Repository eclipse-kapua/kapua, pull requests merged in 2023-10, with the labels that each got.

#3882 Specify how variables export should be done for SSL deployment
  deployment/docker/README.md
Labels: Enhancement, Documentation

#3879 Improve error message for batch job execution log
  job-engine/commons/src/main/java/org/eclipse/kapua/job/engine/commons/operation/AbstractDeviceTargetProcessor.java
  job-engine/commons/src/main/java/org/eclipse/kapua/job/engine/commons/operation/AbstractTargetProcessor.java
Labels: Enhancement

#3887 FIX - fixed logging for device command execution error when arguments are null
  service/device/management/command/internal/src/main/java/org/eclipse/kapua/service/device/management/command/internal/DeviceCommandManagementServiceImpl.java
Labels: Bug

#3888 Fixed Docker Compose SSL enablement
  assembly/jetty-base/entrypoint/run-jetty
  deployment/docker/README.md
  deployment/docker/compose/docker-compose.yml
  deployment/docker/compose/extras/docker-compose.broker-ssl.yml
  deployment/docker/compose/extras/docker-compose.console-ssl.yml
  deployment/docker/compose/extras/docker-compose.rest-ssl.yml
  deployment/docker/unix/configure-certificates.sh
  deployment/docker/unix/docker-common.sh
  deployment/docker/unix/docker-deploy.sh
Labels: Bug

#3891 FIX - Added missing findByExternalUsername method
  service/user/api/src/main/java/org/eclipse/kapua/service/user/UserRepository.java
  service/user/internal/src/main/java/org/eclipse/kapua/service/user/internal/UserCachedRepository.java
  service/user/internal/src/main/java/org/eclipse/kapua/service/user/internal/UserImplJpaRepository.java
  service/user/internal/src/main/java/org/eclipse/kapua/service/user/internal/UserServiceImpl.java
Labels: Bug

#3884 FIX - Foreign keys liquibase scripts correctly imported and executed
  assembly/api/descriptors/kapua-api-jetty.xml
  assembly/api/pom.xml
  assembly/console/descriptors/kapua-console-jetty.xml
  assembly/console/pom.xml
  assembly/job-engine/descriptors/kapua-job-engine-jetty.xml
  assembly/job-engine/pom.xml
  job-engine/app/web/pom.xml
  rest-api/web/pom.xml
Labels: Bug
