Repository eclipse-kapua/kapua, pull requests merged in 2023-01, with the labels that each got.

#3689 Fix - users that can modify expiration date of the account in which are defined
  qa/integration/src/test/resources/features/account/AccountExpirationI9n.feature
  service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountServiceImpl.java
Labels: Bug

#3685 Feature - Liquibase unlocker tool
  commons/src/main/java/org/eclipse/kapua/commons/liquibase/KapuaLiquibaseClient.java
  extras/liquibaseUnlocker/README.md
  extras/liquibaseUnlocker/pom.xml
  extras/liquibaseUnlocker/src/main/java/org/eclipse/kapua/extras/liquibaseUnlocker/Application.java
  extras/liquibaseUnlocker/src/main/resources/logback.xml
  extras/pom.xml
Labels: Enhancement

#3692 Bump Netty version from 4.1.84.Final to 4.1.87.final - CVE-2022-41881 CVE-2022-41915
  pom.xml
Labels: Dependencies

#3687 Upgraded Dependency Check plugin from 1.4.5 to 7.4.4- CVE-2018-12036
  .github/workflows/security-scan.yaml
  docs/developer-guide/en/building.md
  pom.xml
  src/main/dependency-checker/suppress.xml
Labels: Enhancement, build

#3694 fix - typo on directory & module name for the liquibase-unlocker tool
  extras/liquibase-unlocker/README.md
  extras/liquibase-unlocker/pom.xml
  extras/liquibase-unlocker/src/main/java/org/eclipse/kapua/extras/liquibaseUnlocker/Application.java
  extras/liquibase-unlocker/src/main/resources/logback.xml
  extras/pom.xml
Labels: Bug

#3695 Fix missing `jersey-hk2` dependency in `kapua-console-web` module
  console/web/pom.xml
  job-engine/app/web/pom.xml
  pom.xml
  rest-api/web/pom.xml
Labels: Bug

#3696 Bumped Jetty from 9.4.44.v20210927 to 9.4.50.v20221201 - CVE-2022-2047 CVE-2022-2048
  pom.xml
Labels: Dependencies

#3706 Centralized and optimized configurations of maven-shade-plugin
  assembly/consumer/lifecycle/descriptors/kapua-consumer-lifecycle.xml
  assembly/consumer/lifecycle/entrypoint/run-consumer-lifecycle
  assembly/consumer/telemetry/descriptors/kapua-consumer-telemetry.xml
  assembly/consumer/telemetry/entrypoint/run-consumer-telemetry
  consumer/lifecycle-app/pom.xml
  consumer/pom.xml
  consumer/telemetry-app/pom.xml
  extras/encryption-migrator/pom.xml
  extras/es-migrator/pom.xml
  extras/liquibase-unlocker/pom.xml
  pom.xml
  simulator-kura/pom.xml
Labels: Enhancement

#3699 Job execution log reports `target name` and `target short uuid`
  job-engine/api/src/main/resources/job-engine-service-error-messages.properties
  job-engine/commons/pom.xml
  job-engine/commons/src/main/java/org/eclipse/kapua/job/engine/commons/operation/AbstractDeviceTargetProcessor.java
  job-engine/commons/src/main/java/org/eclipse/kapua/job/engine/commons/operation/AbstractTargetProcessor.java
  job-engine/commons/src/main/java/org/eclipse/kapua/job/engine/commons/operation/DefaultTargetReader.java
  rest-api/resources/src/main/resources/openapi/jobExecution/jobExecution.yaml
  service/device/management/asset/job/src/main/java/org/eclipse/kapua/service/device/management/asset/job/DeviceAssetWriteTargetProcessor.java
  service/device/management/bundle/job/src/main/java/org/eclipse/kapua/service/device/management/bundle/job/DeviceBundleStartTargetProcessor.java
  service/device/management/bundle/job/src/main/java/org/eclipse/kapua/service/device/management/bundle/job/DeviceBundleStopTargetProcessor.java
  service/device/management/command/job/src/main/java/org/eclipse/kapua/service/device/management/command/job/DeviceCommandExecTargetProcessor.java
  service/device/management/configuration/job/src/main/java/org/eclipse/kapua/service/device/management/configuration/job/DeviceConfigurationPutTargetProcessor.java
  service/device/management/keystore/job/src/main/java/org/eclipse/kapua/service/device/management/keystore/job/DeviceKeystoreCertificateCreateTargetProcessor.java
  service/device/management/keystore/job/src/main/java/org/eclipse/kapua/service/device/management/keystore/job/DeviceKeystoreItemDeleteTargetProcessor.java
  service/device/management/keystore/job/src/main/java/org/eclipse/kapua/service/device/management/keystore/job/DeviceKeystoreKeypairCreateTargetProcessor.java
  service/device/management/packages/job/src/main/java/org/eclipse/kapua/service/device/management/packages/job/AbstractDevicePackageTargetProcessor.java
  service/device/management/packages/job/src/main/java/org/eclipse/kapua/service/device/management/packages/job/DevicePackageDownloadTargetProcessor.java
  service/device/management/packages/job/src/main/java/org/eclipse/kapua/service/device/management/packages/job/DevicePackageUninstallTargetProcessor.java
  service/job/test-steps/src/main/java/org/eclipse/kapua/service/job/steps/model/TestJobStepProcessor.java
Labels: Enhancement
