Repository eclipse-kapua/kapua, pull requests merged in 2023-05, with the labels that each got.

#3766 [FIX] update in openAPI documentation to reach consistency with responseCode field
  rest-api/resources/src/main/resources/openapi/device/device.yaml
  rest-api/resources/src/main/resources/openapi/deviceEvent/deviceEvent.yaml
  rest-api/resources/src/main/resources/openapi/deviceRequest/deviceRequest.yaml
Labels: Bug, Documentation

#3767 FIX - Reached consistency with enums on openApi doc files
  rest-api/resources/src/main/resources/openapi/authentication/authentication-user.yaml
  rest-api/resources/src/main/resources/openapi/device/device.yaml
  rest-api/resources/src/main/resources/openapi/deviceEvent/deviceEvent.yaml
  rest-api/resources/src/main/resources/openapi/deviceOperation/deviceOperation.yaml
  rest-api/resources/src/main/resources/openapi/deviceRequest/deviceRequest.yaml
  rest-api/resources/src/main/resources/openapi/jobTriggerFired/job-scopeId-jobId-triggers-triggerId-fired-_count.yaml
  rest-api/resources/src/main/resources/openapi/openapi.yaml
Labels: Bug, Documentation

#3774 Print job execution log timestamps in ISO 8601 UTC format
  job-engine/commons/src/main/java/org/eclipse/kapua/job/engine/commons/logger/JobLogger.java
Labels: Enhancement

#3776 Mount `Credential` API resources also under `User` resource path
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/UserCredentialFiltered.java
  rest-api/resources/src/main/resources/openapi/openapi.yaml
  rest-api/resources/src/main/resources/openapi/userCredentialsFiltered/credential-scopeId-_count.yaml
  rest-api/resources/src/main/resources/openapi/userCredentialsFiltered/credential-scopeId.yaml
  rest-api/web/src/main/resources/shiro.ini
Labels: Enhancement

#3772 FIX - EndpointInfoService bugged count method
  qa/integration/src/test/resources/features/endpoint/EndpointServiceI9n.feature
  service/endpoint/internal/src/main/java/org/eclipse/kapua/service/endpoint/internal/EndpointInfoServiceImpl.java
  service/endpoint/test-steps/src/main/java/org/eclipse/kapua/service/endpoint/steps/EndpointServiceSteps.java
Labels: Bug

#3779 Fix - changed IMAGE_VERSION env. variable default value
  deployment/commons/sso/keycloak/build
  deployment/docker/unix/docker-common.sh
  deployment/docker/unix/docker-deploy.sh
  deployment/minishift/minishift-importer.sh
  deployment/minishift/minishift-pull-images.sh
  deployment/minishift/sso/keycloak-importer
  deployment/openshift/openshift-deploy.sh
Labels: Bug

#3782 fix(console): Fixed DeviceSessionPermission reference in kapua-console-module-data module
  console/module/data/pom.xml
  console/module/data/src/main/java/org/eclipse/kapua/app/console/module/data/client/DataView.java
  console/module/data/src/main/java/org/eclipse/kapua/app/console/module/data/shared/model/permission/DeviceSessionPermission.java
Labels: Bug, Console GWT

#3783 fix(git): Added missing JEnv .java-version in .gitignore
  .gitignore
Labels: Bug, build

#3784 FIX - removed timestamp from the tag of docker images built
  assembly/pom.xml
Labels: Bug, build
