Repository eclipse-kapua/kapua, pull requests merged in 2023-11, with the labels that each got.

#3895 Bump `jetty` version from `9.4.52.v20230823` to `9.4.53.v20231009` - `CVE-2023-36478`
  pom.xml
Labels: Dependencies

#3893 Fix typos in run test documentation
  RunTests.md
Labels: Documentation

#3894 FIX - Keycloak server execution failing at startup
  assembly/README.md
  deployment/commons/sso/keycloak/entrypoint/run-keycloak
  deployment/docker/compose/docker-compose.yml
  deployment/docker/compose/sso/docker-compose.console-sso.yml
  deployment/docker/compose/sso/docker-compose.keycloak.yml
  deployment/docker/unix/docker-deploy.sh
  deployment/docker/unix/sso/docker-common-sso.sh
  deployment/docker/unix/sso/docker-sso-config.sh
  docs/developer-guide/en/sso.md
Labels: Bug

#3896 fix login counter
  broker/artemis/plugin/src/main/java/org/eclipse/kapua/broker/artemis/plugin/security/SecurityPlugin.java
  client/security/src/main/java/org/eclipse/kapua/client/security/context/SessionContext.java
  service/authentication/src/main/java/org/eclipse/kapua/service/authentication/authentication/DefaultAuthenticator.java
Labels: Bug

#3898 fix: cve2023-46604
  pom.xml
Labels: CQ approved, Dependencies

#3897 chng(deviceConnection): moved DeviceConnectionServiceConfigurationManager into dedicated module
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/DeviceConnectionServiceConfigurationModule.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/DeviceRegistryModule.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/connection/internal/DeviceConnectionServiceConfigurationManager.java
  service/device/registry/internal/src/main/resources/META-INF/metatypes/org.eclipse.kapua.service.device.registry.connection.DeviceConnectionService.xml
Labels: Enhancement

#3903 Fix `broker` crash on `1.5.x` due to missing dependency
  assembly/broker/descriptors/kapua-broker.xml
  assembly/broker/pom.xml
Labels: Bug

#3901 Fix `broker` crash on `1.6.x` due to missing dependency
  assembly/broker/descriptors/kapua-broker.xml
  assembly/broker/pom.xml
Labels: Bug

#3902 Fix `broker` crash on `1.7.x` due to missing dependency
  assembly/broker/descriptors/kapua-broker.xml
  assembly/broker/pom.xml
Labels: Bug

#3904 Provide compiled version of protobuf payload on `1.5.x` branch
  build-tools/src/main/resources/checkstyle/kapua.suppressions.xml
  client/gateway/profile/kura/pom.xml
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/KuraBinaryPayloadCodec.java
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/KuraBirthCertificateModule.java
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/internal/Metrics.java
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/proto/KuraPayloadProto.java
  client/gateway/profile/kura/src/test/java/org/eclipse/kapua/client/gateway/kura/internal/MetricsTest.java
  pom.xml
  qa/common/src/main/java/org/eclipse/kapua/qa/common/SimulatedDeviceApplication.java
  service/device/call/kura/pom.xml
  service/device/call/kura/src/main/java/org/eclipse/kapua/service/device/call/message/kura/proto/KuraPayloadProto.java
  service/device/call/kura/src/main/protobuf/kurapayload.proto
  service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/KuraDevice.java
  simulator-kura/pom.xml
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/app/Request.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/app/Sender.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/app/data/PeriodicGenerator.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/app/data/SimplePeriodicGenerator.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/payload/Metrics.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/proto/KuraPayloadProto.java
  simulator-kura/src/test/java/org/eclipse/kapua/kura/simulator/main/simulation/AppTest.java
Labels: Enhancement, CQ approved

#3905 Provide compiled version of protobuf payload on `1.6.x` branch
  build-tools/src/main/resources/checkstyle/kapua.suppressions.xml
  client/gateway/profile/kura/pom.xml
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/KuraBinaryPayloadCodec.java
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/KuraBirthCertificateModule.java
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/internal/Metrics.java
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/proto/KuraPayloadProto.java
  client/gateway/profile/kura/src/test/java/org/eclipse/kapua/client/gateway/kura/internal/MetricsTest.java
  pom.xml
  qa/common/src/main/java/org/eclipse/kapua/qa/common/SimulatedDeviceApplication.java
  service/device/call/kura/pom.xml
  service/device/call/kura/src/main/java/org/eclipse/kapua/service/device/call/message/kura/proto/KuraPayloadProto.java
  service/device/call/kura/src/main/protobuf/kurapayload.proto
  service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/KuraDevice.java
  simulator-kura/pom.xml
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/app/Request.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/app/Sender.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/app/data/PeriodicGenerator.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/app/data/SimplePeriodicGenerator.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/payload/Metrics.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/proto/KuraPayloadProto.java
  simulator-kura/src/test/java/org/eclipse/kapua/kura/simulator/main/simulation/AppTest.java
Labels: Enhancement, CQ approved

#3906 Provide compiled version of protobuf payload on `1.7.x` branch
  build-tools/src/main/resources/checkstyle/kapua.suppressions.xml
  client/gateway/profile/kura/pom.xml
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/KuraBinaryPayloadCodec.java
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/KuraBirthCertificateModule.java
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/internal/Metrics.java
  client/gateway/profile/kura/src/main/java/org/eclipse/kapua/client/gateway/kura/proto/KuraPayloadProto.java
  client/gateway/profile/kura/src/test/java/org/eclipse/kapua/client/gateway/kura/internal/MetricsTest.java
  pom.xml
  qa/common/src/main/java/org/eclipse/kapua/qa/common/SimulatedDeviceApplication.java
  service/device/call/kura/pom.xml
  service/device/call/kura/src/main/java/org/eclipse/kapua/service/device/call/message/kura/proto/KuraPayloadProto.java
  service/device/call/kura/src/main/protobuf/kurapayload.proto
  service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/KuraDevice.java
  simulator-kura/pom.xml
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/app/Request.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/app/Sender.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/app/data/PeriodicGenerator.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/app/data/SimplePeriodicGenerator.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/payload/Metrics.java
  simulator-kura/src/main/java/org/eclipse/kapua/kura/simulator/proto/KuraPayloadProto.java
  simulator-kura/src/test/java/org/eclipse/kapua/kura/simulator/main/simulation/AppTest.java
Labels: Enhancement, CQ approved

#3899 fix(openapi): fixes SetResult documentation
  rest-api/resources/src/main/resources/openapi/deviceConnection/deviceConnection.yaml
  rest-api/resources/src/main/resources/openapi/openapi.yaml
Labels: Bug

#3907 FIX - scopeID definition in openapi file
  rest-api/resources/src/main/resources/openapi/openapi.yaml
Labels: Bug, Documentation
