Repository eclipse-kapua/kapua, pull requests merged in 2023-04, with the labels that each got.

#3757 Improved CredentialService.getMinimumPasswordLength to handle also ANY as scopeId
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/shiro/CredentialServiceImpl.java
Labels: Enhancement

#3758 FIX - mods. to asset store service taking into account service disabled
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/assets/DeviceAssetsValues.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/server/GwtDeviceAssetServiceImpl.java
  consumer/telemetry/src/main/java/org/eclipse/kapua/consumer/telemetry/listener/DataStorageMessageProcessor.java
  service/device/management/asset-store/dummy/src/main/java/org/eclipse/kapua/service/device/management/asset/store/dummy/DeviceAssetStoreServiceDummy.java
Labels: Bug

#3761 FIX - mods. to DeviceTab classes to correctly handle background tabs
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/assets/DeviceAssetsValues.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/assets/DeviceTabAssets.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/bundles/DeviceTabBundles.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/command/DeviceTabCommand.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/configuration/DeviceConfigComponents.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/configuration/DeviceTabConfiguration.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/inventory/DeviceTabInventory.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/keystore/DeviceTabKeystore.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/packages/DeviceTabPackages.java
Labels: Bug, Console GWT
