Repository eclipse-kapua/kapua, pull requests merged in 2024-08, with the labels that each got.

#4091 :sparkles: [Docker] Migrated to Docker Compose V2
  deployment/docker/unix/docker-deploy.sh
  deployment/docker/unix/docker-logs.sh
  deployment/docker/unix/docker-undeploy.sh
  deployment/docker/win/docker-deploy.ps1
  deployment/docker/win/docker-logs.ps1
  deployment/docker/win/docker-undeploy.ps1
Labels: Enhancement

#4093 ✨ [REST API] Implement sorting functionality in `/{scopeId}/roles` API
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/EndpointInfos.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Roles.java
  rest-api/resources/src/main/resources/openapi/role/role-scopeId.yaml
Labels: Bug, Enhancement

#4094 ✨ [REST API] Implement sorting functionality in `/{scopeId}/groups` API
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Groups.java
  rest-api/resources/src/main/resources/openapi/group/group-scopeId.yaml
Labels: Enhancement

#4095 ✨ [REST API] Implement sorting functionality in `/{scopeId}/credentials` API
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Credentials.java
  rest-api/resources/src/main/resources/openapi/credential/credential-scopeId.yaml
Labels: Enhancement

#4099 :feat: add account to message header
  broker/artemis/plugin/src/main/java/org/eclipse/kapua/broker/artemis/plugin/security/ServerPlugin.java
  service/client/src/main/java/org/eclipse/kapua/service/client/message/MessageConstants.java
Labels: Enhancement

#4098 FIX: 500 Internal Error is shown trying to call /{scopeId}/users/{userId}/credentials/password/_reset endpoint
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/shiro/CredentialImpl.java
Labels: Bug

#4096 FIX - deleteAllIndexes & refreshAllIndexes methods re-factoring
  service/commons/elasticsearch/client-api/src/main/java/org/eclipse/kapua/service/elasticsearch/client/ElasticsearchClient.java
  service/commons/elasticsearch/client-api/src/main/java/org/eclipse/kapua/service/elasticsearch/client/ElasticsearchRepository.java
  service/commons/elasticsearch/client-rest/src/main/java/org/eclipse/kapua/service/elasticsearch/client/rest/ElasticsearchResourcePaths.java
  service/commons/elasticsearch/client-rest/src/main/java/org/eclipse/kapua/service/elasticsearch/client/rest/RestElasticsearchClient.java
  service/commons/storable/api/src/main/java/org/eclipse/kapua/service/storable/repository/StorableRepository.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ChannelInfoElasticsearchRepository.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ClientInfoElasticsearchRepository.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MessageElasticsearchRepository.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MetricInfoRepositoryImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/mediator/DatastoreUtils.java
Labels: Bug, Test

#4101 ✨ [REST API] FEATURE: Implemented askTotalCount in API '/{scopeId}/credentials'
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Credentials.java
  rest-api/resources/src/main/resources/openapi/credential/credential-scopeId.yaml
Labels: Enhancement
