Repository eclipse-kapua/kapua, pull requests merged in 2024-03, with the labels that each got.

#3983 Fix issue with job execution filtering in REST API for start date
  qa/integration/src/test/resources/features/job/JobExecutionServiceI9n.feature
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/JobExecutions.java
  service/job/test-steps/src/main/java/org/eclipse/kapua/service/job/steps/JobExecutionServiceSteps.java
Labels: Bug

#3984 :fix: Making sure the event listeners are unique
  broker/artemis/plugin/src/main/java/org/eclipse/kapua/broker/artemis/AppModule.java
  commons/src/main/java/org/eclipse/kapua/commons/event/RaiseServiceEventInterceptor.java
  commons/src/main/java/org/eclipse/kapua/commons/event/ServiceEventTransactionalModule.java
  commons/src/main/java/org/eclipse/kapua/commons/event/ServiceInspector.java
  commons/src/main/java/org/eclipse/kapua/commons/event/jms/JMSServiceEventBus.java
  commons/src/main/resources/kapua-environment-setting.properties
  console/web/src/main/java/org/eclipse/kapua/app/console/AppModule.java
  consumer/lifecycle-app/src/main/java/org/eclipse/kapua/consumer/lifecycle/AppModule.java
  consumer/telemetry-app/src/main/java/org/eclipse/kapua/consumer/telemetry/AppModule.java
  job-engine/app/web/src/main/java/org/eclipse/kapua/job/engine/app/web/AppModule.java
  locator/guice/src/main/java/org/eclipse/kapua/locator/guice/KapuaModule.java
  message/internal/src/test/java/org/eclipse/kapua/message/internal/TestModule.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/misc/TestConfigModule.java
  qa/integration/src/test/resources/kapua-environment-setting.properties
  rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/model/TestModule.java
  rest-api/web/src/main/java/org/eclipse/kapua/app/api/web/AppModule.java
  service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountModule.java
  service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountServiceModule.java
  service/account/internal/src/test/java/org/eclipse/kapua/service/account/xml/TestConfigModule.java
  service/authentication-app/src/main/java/org/eclipse/kapua/service/authentication/AppModule.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/connection/listener/internal/DeviceConnectionEventListenerModule.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/connection/listener/internal/DeviceConnectionEventListenerServiceModule.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/DeviceRegistryModule.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/DeviceServiceModule.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/AuthenticationModule.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/AuthenticationServiceModule.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/shiro/AuthorizationModule.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/shiro/AuthorizationServiceModule.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/TestModule.java
  service/user/internal/src/main/java/org/eclipse/kapua/service/user/internal/UserModule.java
  service/user/internal/src/main/java/org/eclipse/kapua/service/user/internal/UserServiceModule.java
Labels: Bug

#3970 Removing download of NPM and Swagger CLI for each build
  .github/actions/runTestsTaggedAs/action.yaml
  .github/workflows/kapua-ci.yaml
  README.md
  assembly/api/pom.xml
Labels: Enhancement

#3985 Add OpenAPI schema and description for `JobStep` object
  rest-api/resources/src/main/resources/openapi/jobStep/jobStep.yaml
Labels: Bug, Documentation

#3989 :bug: (commons): fixes resolution of CertificateQuery forwardable entities when scopeId is `null`
  service/commons/utils/internal/src/main/java/org/eclipse/kapua/service/utils/internal/KapuaEntityQueryUtilImpl.java
Labels: Bug

#3971 ! :sparkles: Kapua's initializing methods mechanism
  commons/src/main/java/org/eclipse/kapua/commons/CommonsModule.java
  commons/src/main/java/org/eclipse/kapua/commons/liquibase/DatabaseCheckUpdate.java
  commons/src/main/java/org/eclipse/kapua/commons/populators/DataPopulator.java
  commons/src/main/java/org/eclipse/kapua/commons/populators/DataPopulatorRunner.java
  console/web/src/main/java/org/eclipse/kapua/app/console/AppModule.java
  console/web/src/main/java/org/eclipse/kapua/app/console/server/util/ConsoleListener.java
  consumer/lifecycle-app/src/main/java/org/eclipse/kapua/consumer/lifecycle/AppModule.java
  consumer/lifecycle-app/src/main/java/org/eclipse/kapua/consumer/lifecycle/LifecycleApplication.java
  consumer/telemetry-app/src/main/java/org/eclipse/kapua/consumer/telemetry/AppModule.java
  consumer/telemetry-app/src/main/java/org/eclipse/kapua/consumer/telemetry/TelemetryApplication.java
  job-engine/app/web/src/main/java/org/eclipse/kapua/job/engine/app/web/AppModule.java
  job-engine/app/web/src/main/java/org/eclipse/kapua/job/engine/app/web/JobEngineApplication.java
  job-engine/app/web/src/main/java/org/eclipse/kapua/job/engine/app/web/jaxb/JaxbContextResolver.java
  job-engine/app/web/src/main/java/org/eclipse/kapua/job/engine/app/web/jaxb/JobEngineJAXBContextProvider.java
  locator/guice/src/main/java/org/eclipse/kapua/locator/guice/GuiceLocatorImpl.java
  rest-api/web/src/main/java/org/eclipse/kapua/app/api/web/AppModule.java
  rest-api/web/src/main/java/org/eclipse/kapua/app/api/web/JaxbContextResolver.java
  rest-api/web/src/main/java/org/eclipse/kapua/app/api/web/RestApiJAXBContextProvider.java
  rest-api/web/src/main/java/org/eclipse/kapua/app/api/web/RestApisApplication.java
  rest-api/web/src/test/java/org/eclipse/kapua/app/api/web/RestApiJAXBContextProviderTest.java
  service/api/src/main/java/org/eclipse/kapua/locator/KapuaLocator.java
  service/api/src/main/java/org/eclipse/kapua/locator/initializers/KapuaInitializingMethod.java
  service/authentication-app/src/main/java/org/eclipse/kapua/service/authentication/AppModule.java
  service/authentication-app/src/main/java/org/eclipse/kapua/service/authentication/AuthenticationApplication.java
  service/camel/src/main/java/org/eclipse/kapua/service/camel/setting/ServiceSetting.java
  service/camel/src/main/java/org/eclipse/kapua/service/camel/setting/ServiceSettingKey.java
  service/camel/src/main/java/org/eclipse/kapua/service/camel/xml/ServiceJAXBContextLoader.java
  service/camel/src/main/java/org/eclipse/kapua/service/camel/xml/ServiceJAXBContextLoaderProvider.java
  service/camel/src/main/resources/kapua-service-camel-setting.properties
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/registration/RegistrationServiceImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/domain/shiro/DomainsAligner.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/shiro/AuthorizationModule.java
Labels: Enhancement, CQ approved

#3987 FEATURE - Added "match term" parameter for jobs
  qa/integration/src/test/resources/features/job/JobServiceI9n.feature
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Jobs.java
  rest-api/resources/src/main/resources/openapi/job/job-scopeId.yaml
  service/job/api/src/main/java/org/eclipse/kapua/service/job/JobMatchPredicate.java
  service/job/api/src/main/java/org/eclipse/kapua/service/job/JobQuery.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/internal/JobMatchPredicateImpl.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/internal/JobQueryImpl.java
  service/job/test-steps/src/main/java/org/eclipse/kapua/service/job/steps/JobServiceSteps.java
Labels: Enhancement

#3990 :bug: KapuaLocator cleanup on failed startup
  service/api/src/main/java/org/eclipse/kapua/locator/KapuaLocator.java
Labels: Bug

#3988 :recycle: deprecating the user of scopeId in current user profile rest apis
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/UserCredentials.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/UserProfiles.java
  rest-api/resources/src/main/resources/openapi/openapi.yaml
  rest-api/resources/src/main/resources/openapi/userProfile/userProfile-scopeId.yaml
  rest-api/resources/src/main/resources/openapi/userProfile/userProfile.yaml
  rest-api/web/src/main/resources/shiro.ini
Labels: Enhancement

#3959 Feature - Access Token fetch improval
  .github/workflows/kapua-ci.yaml
  assembly/api/docker/Dockerfile
  commons-rest/errors/src/main/java/org/eclipse/kapua/commons/rest/errors/KapuaAuthenticationExceptionMapper.java
  commons-rest/filters/src/main/java/org/eclipse/kapua/commons/rest/filters/CORSResponseFilter.java
  deployment/docker/compose/docker-compose.yml
  deployment/docker/compose/extras/docker-compose.api-dev.yml
  deployment/docker/unix/docker-deploy.sh
  qa/common/src/main/java/org/eclipse/kapua/qa/common/BasicSteps.java
  qa/common/src/main/java/org/eclipse/kapua/qa/common/TestJAXBContextProvider.java
  qa/integration-steps/src/main/java/org/eclipse/kapua/qa/integration/steps/DockerSteps.java
  qa/integration-steps/src/main/java/org/eclipse/kapua/qa/integration/steps/RestClientSteps.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/rest/RunRestAuthTest.java
  qa/integration/src/test/resources/features/rest/authentication/RestAuth.feature
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/auth/KapuaTokenAuthenticationFilter.java
  rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/auth/KapuaTokenAuthenticationFilterTest.java
  service/api/src/main/java/org/eclipse/kapua/KapuaErrorCodes.java
  service/api/src/main/resources/kapua-service-error-messages.properties
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/AuthenticationService.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/token/AccessToken.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/token/AccessTokenAttributes.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/token/AccessTokenCreator.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/token/AccessTokenFactory.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/token/AccessTokenRepository.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/token/AccessTokenXmlRegistry.java
  service/security/authentication/api/src/main/resources/authentication-error-messages.properties
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/AuthenticationServiceShiroImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/exceptions/ExpiredAccessTokenException.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/exceptions/InvalidatedAccessTokenException.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/exceptions/MalformedAccessTokenException.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/AccessTokenAuthenticatingRealm.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/AccessTokenCredentialsMatcher.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/SessionAuthenticationInfo.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/token/shiro/AccessTokenCreatorImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/token/shiro/AccessTokenFactoryImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/token/shiro/AccessTokenImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/token/shiro/AccessTokenImplJpaRepository.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/token/shiro/AccessTokenServiceImpl.java
  service/security/shiro/src/main/resources/liquibase/2.0.0/atht-newTokenIdentifier.xml
  service/security/shiro/src/main/resources/liquibase/changelog-authentication-master.xml
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/shiro/realm/SessionAuthenticationInfoTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/token/shiro/AccessTokenFactoryImplTest.java
  service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/token/shiro/AccessTokenImplTest.java
Labels: Enhancement

#3991 :bug: (Jobs) fixed JobStep.jobStepDefinitionId not being editable
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/step/internal/JobStepImpl.java
Labels: Bug

#3994 FIX - Added missing @XmlJavaTypeAdapter on some fields of JobExecution
  service/job/api/src/main/java/org/eclipse/kapua/service/job/execution/JobExecution.java
Labels: Bug

#3995 Fix OpenAPI schema for `StepProperties` of a `Job`
  rest-api/resources/src/main/resources/openapi/jobStep/jobStep.yaml
Labels: Bug

#3997 :bug: (commons): fixes resolution of forwardable queries on forwardable entities when predicates are null
  service/commons/utils/internal/src/main/java/org/eclipse/kapua/service/utils/internal/KapuaEntityQueryUtilImpl.java
Labels: Bug

#3993 Fix account rest apis
  commons-rest/errors/src/main/java/org/eclipse/kapua/commons/rest/errors/KapuaIllegalAccessExceptionMapper.java
  commons/pom.xml
  commons/src/main/java/org/eclipse/kapua/commons/CommonsModule.java
  commons/src/main/java/org/eclipse/kapua/commons/model/mappers/KapuaBaseMapper.java
  pom.xml
  qa/integration/src/test/resources/features/account/AccountExpirationI9n.feature
  qa/integration/src/test/resources/features/user/UserRoleServiceI9n.feature
  rest-api/resources/pom.xml
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Account.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Accounts.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/CurrentAccount.java
  rest-api/resources/src/main/resources/openapi/account/account-scopeId-accountId.yaml
  rest-api/resources/src/main/resources/openapi/account/account.yaml
  rest-api/resources/src/main/resources/openapi/accounts/accounts-accountId.yaml
  rest-api/resources/src/main/resources/openapi/accounts/accounts-scopeId-_count.yaml
  rest-api/resources/src/main/resources/openapi/accounts/accounts-scopeId-_query.yaml
  rest-api/resources/src/main/resources/openapi/accounts/accounts-scopeId.yaml
  rest-api/resources/src/main/resources/openapi/accounts/accounts.yaml
  rest-api/resources/src/main/resources/openapi/openapi.yaml
  rest-api/web/src/main/java/org/eclipse/kapua/app/api/web/RestApiJAXBContextProvider.java
  rest-api/web/src/main/resources/shiro.ini
  service/account/api/src/main/java/org/eclipse/kapua/service/account/AccountService.java
  service/account/api/src/main/java/org/eclipse/kapua/service/account/AccountUpdateRequest.java
  service/account/api/src/main/java/org/eclipse/kapua/service/account/CurrentAccountUpdateRequest.java
  service/account/internal/pom.xml
  service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountMapper.java
  service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountModule.java
  service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountServiceImpl.java
  service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/exception/KapuaAccountException.java
  service/account/test-steps/src/main/java/org/eclipse/kapua/service/account/steps/AccountServiceSteps.java
  service/account/test/src/test/java/org/eclipse/kapua/service/account/test/AccountLocatorConfiguration.java
  service/account/test/src/test/resources/features/AccountService.feature
  service/api/src/main/java/org/eclipse/kapua/model/KapuaNamedEntityUpdateRequest.java
  service/api/src/main/java/org/eclipse/kapua/model/KapuaUpdatableEntityUpdateRequest.java
Labels: Enhancement, CQ approved

#4002 FEATURE - Added the "status" query parameter for api endpoint "/{scopeId}/jobs/{jobId}/targets"
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/JobTargets.java
  rest-api/resources/src/main/resources/openapi/jobTarget/job-scopeId-jobId-targets.yaml
  rest-api/resources/src/main/resources/openapi/jobTarget/jobTarget.yaml
Labels: Enhancement

#4003 FIX - Refactored datastoreUtils with the inclusion of a abstract class on top of it
  service/commons/elasticsearch/client-api/src/main/java/org/eclipse/kapua/service/elasticsearch/client/AbstractStoreUtils.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/mediator/DatastoreUtils.java
  service/datastore/test-steps/src/main/java/org/eclipse/kapua/service/datastore/steps/DatastoreSteps.java
  service/datastore/test/src/test/java/org/eclipse/kapua/service/datastore/test/junit/DatastoreUtilsIndexCalculatorTest.java
Labels: Enhancement

#4004 Fix for Trigger Edit Duplicate Name Issue
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/quartz/TriggerServiceImpl.java
Labels: Bug
