Repository eclipse-kapua/kapua, pull requests merged in 2024-04, with the labels that each got.

#4007 :fix: add publish counter for internal messages
  broker/artemis/plugin/src/main/java/org/eclipse/kapua/broker/artemis/plugin/security/SecurityPlugin.java
  broker/artemis/plugin/src/main/java/org/eclipse/kapua/broker/artemis/plugin/security/ServerPlugin.java
  broker/artemis/plugin/src/main/java/org/eclipse/kapua/broker/artemis/plugin/security/metric/PublishMetric.java
Labels: Bug

#4006 :fix: job execution stop always returns 202, regardless of it running…
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/JobEngine.java
  rest-api/resources/src/main/resources/openapi/jobEngine/jobEngine-scopeId-jobId-executionId.yaml
  rest-api/resources/src/main/resources/openapi/jobEngine/jobEngine-scopeId-jobId.yaml
Labels: Bug

#4009 :bug: [OpenAPI] Fix OpenAPI definitions for Account and User MFA resources
  rest-api/resources/src/main/resources/openapi/account/account.yaml
  rest-api/resources/src/main/resources/openapi/accounts/accounts.yaml
  rest-api/resources/src/main/resources/openapi/openapi.yaml
  rest-api/resources/src/main/resources/openapi/userMfa/userMfa.yaml
Labels: Bug

#4010 FIX - Added tests for CORS filtering logic
  .github/workflows/kapua-ci.yaml
  assembly/api/docker/Dockerfile
  deployment/docker/compose/docker-compose.yml
  qa/common/src/main/resources/sql/all_delete.sql
  qa/integration-steps/src/main/java/org/eclipse/kapua/qa/integration/steps/DockerSteps.java
  qa/integration-steps/src/main/java/org/eclipse/kapua/qa/integration/steps/RestClientSteps.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/rest/RunRestCorsFilterTest.java
  qa/integration/src/test/resources/features/rest/authentication/RestAuth.feature
  qa/integration/src/test/resources/features/rest/cors/RestCORSFilter.feature
Labels: Enhancement, Test

#4013 :bug: random uuid in event client id resulted in multiple instances o…
  commons/src/main/java/org/eclipse/kapua/commons/event/ServiceEventTransactionalModule.java
  commons/src/main/java/org/eclipse/kapua/commons/model/AbstractKapuaEntity.java
  service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountImpl.java
  service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountServiceModule.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/connection/listener/internal/DeviceConnectionEventListenerServiceModule.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/DeviceServiceModule.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/AuthenticationServiceModule.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/shiro/AuthorizationServiceModule.java
  service/user/internal/src/main/java/org/eclipse/kapua/service/user/internal/UserServiceModule.java
Labels: Bug

#4012 :fix: add auto reconnect to service client
  broker/artemis/plugin/src/main/java/org/eclipse/kapua/broker/artemis/plugin/security/SecurityPlugin.java
  client/security/src/main/java/org/eclipse/kapua/client/security/ServiceClientMessagingImpl.java
  client/security/src/main/java/org/eclipse/kapua/client/security/amqpclient/Client.java
  client/security/src/main/java/org/eclipse/kapua/client/security/amqpclient/ConnectionStatus.java
  client/security/src/main/java/org/eclipse/kapua/client/security/amqpclient/JMSExceptionListner.java
  commons/src/main/java/org/eclipse/kapua/commons/event/jms/JMSServiceEventBus.java
Labels: Bug

#4015 :sparkles: added matchterm option parameter to accounts query
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Accounts.java
  rest-api/resources/src/main/resources/openapi/accounts/accounts-scopeId.yaml
Labels: Enhancement

#4014 :sparkles: added askTotalCount parameter to accounts query
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Accounts.java
  rest-api/resources/src/main/resources/openapi/accounts/accounts-scopeId.yaml
Labels: Enhancement

#4018 :fix: (metrics) add publish and subscribe time (metrics ot linked to the code)
  broker/artemis/plugin/src/main/java/org/eclipse/kapua/broker/artemis/plugin/security/ServerPlugin.java
Labels: Bug

#4020 :fix: count suffix for metrics names
  commons/src/main/java/org/eclipse/kapua/commons/metric/MetricsServiceImpl.java
Labels: Bug

#4019 :bug: jpa does not know how to handle kapuaids, was ending up comparing eids with bigintegers and failing.
  commons/src/main/java/org/eclipse/kapua/commons/jpa/KapuaEntityJpaRepository.java
Labels: Bug
