Repository eclipse-kapua/kapua, pull requests merged in 2024-07, with the labels that each got.

#4054 FIX - Remove unused code for embedded services and related feature files
  qa/common/src/main/java/org/eclipse/kapua/qa/common/utils/EmbeddedEventBroker.java
  qa/common/src/main/java/org/eclipse/kapua/qa/common/utils/EmbeddedJetty.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/rest/RunRestUserTest.java
  qa/integration/src/test/resources/features/rest/user/RestUser.feature
Labels: Bug, Test

#4064 :bug: [REST API] Fix `ServiceConfigurations` to return `KapuaIllegalArgument` instead of `204`
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/ServiceConfigurations.java
Labels: Bug

#4069 Fix add input validation to `KapuaConfigurableServiceBase`
  commons/src/main/java/org/eclipse/kapua/commons/configuration/KapuaConfigurableServiceBase.java
Labels: Bug

#4074 :bug: [Docker] Fixed mirrors for CentOS 7
  assembly/java-base/docker/Dockerfile
Labels: Bug

#4075 🔧 [Datastore] Datastore caches individually configurable
  commons/src/main/java/org/eclipse/kapua/commons/cache/CacheConfig.java
  commons/src/main/java/org/eclipse/kapua/commons/cache/ExpiryPolicy.java
  commons/src/main/java/org/eclipse/kapua/commons/cache/LocalCache.java
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/cache/KapuaCacheManager.java
  commons/src/main/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSetting.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/DatastoreCacheManager.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/setting/DatastoreSettings.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/setting/DatastoreSettingsKey.java
  service/datastore/internal/src/main/resources/kapua-datastore-settings.properties
Labels: Enhancement

#4076 🔧 [Datastore] Datastore caches individually configurable
  commons/src/main/java/org/eclipse/kapua/commons/cache/CacheConfig.java
  commons/src/main/java/org/eclipse/kapua/commons/cache/ExpiryPolicy.java
  commons/src/main/java/org/eclipse/kapua/commons/cache/LocalCache.java
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/cache/CacheManagerProvider.java
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/cache/KapuaCacheManager.java
  commons/src/main/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSetting.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/DatastoreCacheManager.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/setting/DatastoreSettings.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/setting/DatastoreSettingsKey.java
  service/datastore/internal/src/main/resources/kapua-datastore-settings.properties
Labels: Enhancement

#4077 :bug: Current account update was not checking for not null organisation name and email
  service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountMapper.java
  service/account/internal/src/main/java/org/eclipse/kapua/service/account/internal/AccountServiceImpl.java
Labels: Bug

#4067 :fix: set hikari configuration pool to fixed size (more performant)
  commons/src/main/java/org/eclipse/kapua/commons/jpa/DataSource.java
Labels: Enhancement

#4078 ✨ [REST API] Added "askTotalCount" parameter for tags api
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Tags.java
  rest-api/resources/src/main/resources/openapi/tag/tag-scopeId.yaml
Labels: Enhancement

#4082 🐛 [Open API] FIX - Removed base64 format on dataChannel API docoumentation
  rest-api/resources/src/main/resources/openapi/dataChannel/dataChannel.yaml
Labels: Bug

#4085 :bug: [Console GWT] Fixed Credential Edit dialog does not letting update the selected Credential
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/client/tabs/credentials/CredentialEditDialog.java
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/server/GwtCredentialServiceImpl.java
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/shared/util/GwtKapuaAuthenticationModelConverter.java
Labels: Bug, Console GWT

#4086 :lipstick: [Console GWT] Added lockout policy fields in Credential grid
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/client/tabs/credentials/CredentialGrid.java
Labels: Enhancement, Console GWT

#4084 🐛 [Open API] FIX - API doc. on "GET /{scopeId}/devices" request section
  rest-api/resources/src/main/resources/openapi/device/device-scopeId.yaml
Labels: Bug, REST API

#4083 🐛 Resolved JWT Certificate Issue Preventing REST API Logins for Accounts
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/AuthenticationServiceShiroImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/AccessTokenAuthenticatingRealm.java
Labels: Bug

#4088 🐛 [Authentication] Restrict editing of credential critical properties to admin
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/shiro/CredentialServiceImpl.java
Labels: Bug

#4090 ✨ [REST API] Implement sorting functionality in `/{scopeId}/endpointInfos` API
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/EndpointInfos.java
  rest-api/resources/src/main/resources/openapi/endpointInfo/endpointInfo-scopeId.yaml
Labels: Enhancement
