Repository eclipse-kapua/kapua, pull requests merged in 2024-09, with the labels that each got.

#4089 FIX - SSL configuration on Elasticsearch clients
  assembly/consumer/telemetry/docker/Dockerfile
  qa/common/src/main/java/org/eclipse/kapua/qa/common/BasicSteps.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/service/datastoreJunit/MessageStoreServiceSslTest.java
  qa/integration/src/test/resources/kapua-datastore-elasticsearch-client-settings.properties
  service/commons/elasticsearch/client-api/src/main/java/org/eclipse/kapua/service/elasticsearch/client/configuration/ElasticsearchClientSslConfiguration.java
  service/commons/elasticsearch/client-rest/src/main/java/org/eclipse/kapua/service/elasticsearch/client/rest/RestElasticsearchClientProvider.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/client/DatastoreElasticsearchClientConfiguration.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/setting/DatastoreElasticsearchClientSettingsKey.java
  service/datastore/internal/src/main/resources/kapua-datastore-elasticsearch-client-settings.properties
  service/datastore/test/src/test/resources/kapua-datastore-rest-client-setting.properties
  service/datastore/test/src/test/resources/kapua-datastore-transport-client-setting.properties
Labels: Bug

#4102 ✨ [Jobs] Add username/password in PackageDownloadRequest example for `Package Download/Install` step
  service/device/management/packages/job/src/main/resources/liquibase/2.0.0/changelog-packages-job-2.0.0.post.xml
  service/device/management/packages/job/src/main/resources/liquibase/2.0.0/packages_job_step_definition_property_update_example_field.xml
  service/device/management/packages/job/src/main/resources/liquibase/changelog-packages-job-master.xml
Labels: Enhancement

#4104 🐛 [Authentication] Return `MfaRequiredException` when `trustKey` is not valid
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/MfaOptionServiceImpl.java
Labels: Bug

#4105 :sparkles: [Rest API] Added setting to filter JobStepDefinitions returned with GET request
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/settings/KapuaApiCoreSettingKeys.java
  rest-api/core/src/main/resources/kapua-api-core-settings.properties
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/JobStepDefinitions.java
Labels: Enhancement

#4107 :bug: [CI] Added missing installation of Node JS and swagger required to build the project for Owasp Dependency Check
  .github/workflows/security-scan.yaml
Labels: Bug, build

#4108 :fix: introduce KapuaSessionCustomizer
  commons/src/main/java/org/eclipse/kapua/commons/jpa/AbstractEntityManagerFactory.java
  commons/src/main/java/org/eclipse/kapua/commons/jpa/KapuaSessionCustomizer.java
Labels: Enhancement

#4106 FIX - marshalling/unmarshalling Password[] and KuraPassword[] types
  commons/src/main/java/org/eclipse/kapua/commons/configuration/metatype/PasswordPropertyAdapter.java
  service/api/src/test/java/org/eclipse/kapua/model/xml/adapters/XmlPropertiesAdapterTest.java
  service/device/call/kura/src/main/java/org/eclipse/kapua/service/device/call/kura/model/configuration/xml/KuraPasswordPropertyAdapter.java
Labels: Bug

#4110 :bug: [Broker] Added missing Eclipse Link ASM dependency
  assembly/broker/descriptors/kapua-broker.xml
  assembly/broker/pom.xml
  pom.xml
Labels: Bug
