Repository eclipse-kapua/kapua, pull requests merged in 2024-12, with the labels that each got.

#4149 :bug: [Job] Fixed JobStepDefinitionProperty.description for Bundle Start and Bundle Stop
  service/device/management/bundle/job/src/main/java/org/eclipse/kapua/service/device/management/bundle/job/definition/DeviceBundleStartJobStepDefinition.java
  service/device/management/bundle/job/src/main/java/org/eclipse/kapua/service/device/management/bundle/job/definition/DeviceBundleStopJobStepDefinition.java
Labels: Bug

#4150 :sparkles: [Job Engine] Added JobDataCleanupJobEndCallback to delete JobInstanceData after JobExecution has ended
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/overrides/callback/JobDataCleanupJobEndCallback.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/overrides/callback/KapuaJobEndCallbackManagerImpl.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/JPAPersistenceManagerImpl.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaJobInstanceData.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaJobInstanceDataRepository.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaJobInstanceDataRepositoryImpl.java
  job-engine/jbatch/src/main/resources/META-INF/services/batch-services.properties
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceStopOnlineDeviceI9n.feature
Labels: Enhancement

#4153 :bug: [Build] Fixed compilerArgs definition for Maven Compiler Plugin of Mapstruct args
  commons/pom.xml
  service/account/internal/pom.xml
Labels: Bug, build

#4152 :white_check_mark: [Job Engine] Decrease max time to completion for Job Engine tests
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceKeystoreStepDefinitionsI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceRestartOnlineDeviceI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceRestartOnlineDeviceSecondPartI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceStartOnlineDeviceI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceStopOnlineDeviceI9n.feature
Labels: Test

#4155 :fire: [Build] Removed Sonar analysis GitHub Actions - CWE-94
  .github/workflows/prNumberUploader.yaml
  .github/workflows/sonarCloud-scan.yaml
Labels: build

#4156 :white_check_mark: [CI] Added Sonar analysis
  .github/workflows/sonarCloud-scan.yaml
  commons/pom.xml
  pom.xml
  service/account/internal/pom.xml
  simulator-kura/pom.xml
Labels: Code

#4157 :bug: [CI] Fixed Sonar 'project.key' and 'organization' entries
  pom.xml
Labels: Bug, build

#4154 🐛 [REST API] Respond with `403` when max allowed limit for entities is exceeded
  commons-rest/errors/src/main/java/org/eclipse/kapua/commons/rest/errors/KapuaMaxNumberOfItemsReachedExceptionMapper.java
  commons-rest/model/src/main/java/org/eclipse/kapua/commons/rest/model/errors/MaxNumberOfItemsReachedExceptionInfo.java
  qa/common/src/main/java/org/eclipse/kapua/qa/common/BasicSteps.java
  qa/integration/src/test/resources/features/account/AccountDeviceRegistryService.feature
  qa/integration/src/test/resources/features/account/AccountGroupService.feature
  qa/integration/src/test/resources/features/account/AccountJobService.feature
  qa/integration/src/test/resources/features/account/AccountRoleService.feature
  qa/integration/src/test/resources/features/account/AccountServiceCreation.feature
  qa/integration/src/test/resources/features/account/AccountTagService.feature
  qa/integration/src/test/resources/features/account/AccountUserService.feature
Labels: Bug, REST API

#4158 :white_check_mark: [Job] Improved test execution times for Job / JobEngine tests
  qa/common/src/main/java/org/eclipse/kapua/qa/common/utils/InitShiro.java
  qa/integration-steps/src/main/java/org/eclipse/kapua/qa/integration/steps/DockerSteps.java
  qa/integration/src/test/resources/features/job/JobExecutionServiceI9n.feature
  qa/integration/src/test/resources/features/job/JobServiceI9n.feature
  qa/integration/src/test/resources/features/job/JobTargetsServiceI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceKeystoreStepDefinitionsI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceRestartOfflineDeviceI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceRestartOnlineDeviceI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceRestartOnlineDeviceSecondPartI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceStartOfflineDeviceI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceStartOnlineDeviceI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceStopOnlineDeviceI9n.feature
  qa/integration/src/test/resources/features/jobScheduling/ExecuteOnDeviceConnectI9n.feature
  qa/integration/src/test/resources/features/jobScheduling/TriggerServiceI9n.feature
Labels: Console GWT, Test

#4130 ✨ Data store queries now allow for multiple client ids
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DataChannels.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DataClients.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DataMessages.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DataMessagesJson.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DataMetrics.java
  rest-api/resources/src/main/resources/openapi/dataChannel/dataChannel-scopeId.yaml
  rest-api/resources/src/main/resources/openapi/dataClient/dataClient-scopeId.yaml
  rest-api/resources/src/main/resources/openapi/dataMessage/dataMessage-scopeId.yaml
  rest-api/resources/src/main/resources/openapi/dataMetric/dataMetric-scopeId.yaml
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MetricInfoRegistryFacadeImpl.java
Labels: Enhancement
