Repository eclipse-kapua/kapua, pull requests merged in 2024-10, with the labels that each got.

#4109 FIX - Reporting missing "property.type" XML/JSON property
  service/api/src/main/java/org/eclipse/kapua/model/xml/adapters/XmlPropertiesAdapter.java
  service/api/src/test/java/org/eclipse/kapua/model/xml/adapters/XmlPropertiesAdapterTest.java
  service/api/src/test/java/org/eclipse/kapua/service/config/ServiceXmlConfigPropertiesAdapterTest.java
Labels: Bug

#4111 🐛 [REST API] Correct response schema for GET `data/messages/{datastoreMessageId}` to return `dataMessage`
  rest-api/resources/src/main/resources/openapi/dataMessage/dataMessage-scopeId-datastoreMessageId.yaml
Labels: Bug, Documentation

#4113 :sparkles: [Core] Extended allowed chars in KapuaEntity.name
  commons/src/main/java/org/eclipse/kapua/commons/util/ArgumentValidator.java
  commons/src/main/java/org/eclipse/kapua/commons/util/CommonsValidationRegex.java
  commons/src/test/java/org/eclipse/kapua/commons/util/ArgumentValidatorTest.java
  console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/client/util/validator/TextFieldValidator.java
  console/module/authorization/src/main/java/org/eclipse/kapua/app/console/module/authorization/client/group/GroupAddDialog.java
  console/module/authorization/src/main/java/org/eclipse/kapua/app/console/module/authorization/client/role/dialog/RoleAddDialog.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/client/JobAddDialog.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/client/schedule/JobScheduleAddDialog.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/client/steps/JobStepAddDialog.java
  console/module/tag/src/main/java/org/eclipse/kapua/app/console/module/tag/client/TagAddDialog.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/internal/JobServiceImpl.java
  service/security/test/src/test/resources/features/GroupServiceUnitTests.feature
Labels: Enhancement

#4116 :memo: [Release Notes] Added UPGRADE_NOTES.md file
  UPGRADE_NOTES.md
Labels: Enhancement, Documentation

#4115 ✨ [MFA] Added new 'hasTrustMe' attribute
  UPGRADE_NOTES.md
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/client/tabs/credentials/MfaManagementPanel.java
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/shared/model/GwtMfaCredentialOptions.java
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/shared/util/KapuaGwtAuthenticationModelConverter.java
  extras/encryption-migrator/src/main/java/org/eclipse/kapua/extras/migrator/encryption/authentication/MfaOptionMigrator.java
  rest-api/resources/src/main/resources/openapi/userMfa/userMfa.yaml
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/MfaOption.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/MfaOptionAttributes.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/MfaOptionCreator.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/MfaOptionFactory.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/MfaOptionListResult.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/MfaOptionRepository.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/MfaOptionService.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/MfaOptionXmlRegistry.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/ScratchCode.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/ScratchCodeFactory.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/ScratchCodeListResult.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/ScratchCodeRepository.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/ScratchCodeService.java
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/ScratchCodeXmlRegistry.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/MfaOptionImpl.java
  service/security/shiro/src/main/resources/liquibase/2.1.0/atht-mfa_option-has_trust_me.xml
  service/security/shiro/src/main/resources/liquibase/2.1.0/changelog-authentication-2.1.0.xml
  service/security/shiro/src/main/resources/liquibase/changelog-authentication-master.xml
Labels: Enhancement

#4100 FIX: Logs of broken jms connection to event-broker on an integration test
  qa/integration-steps/src/main/java/org/eclipse/kapua/qa/integration/steps/DockerSteps.java
  qa/integration/src/test/resources/features/broker/DeviceBrokerI9n.feature
Labels: Bug

#4119 ✨ [Rest API] Add `sortDir`, `sortParam` and `askTotalCount` functionality to `/{scopeId}/devices/{deviceId}/operations/{operationId}/notifications` API
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceManagementOperationNotifications.java
  rest-api/resources/src/main/resources/openapi/deviceNotification/deviceNotification-scopeId-deviceId-operationId.yaml
Labels: Enhancement

#4120 ⚡ [REST API] Restore possibility to update a service configuration property with a "default" value
  service/api/src/main/java/org/eclipse/kapua/model/xml/adapters/XmlPropertiesAdapter.java
Labels: Bug

#4117 :zap: [REST API] Block execution on XML/JSON parsing errors and report 400 error code
  .github/workflows/kapua-ci.yaml
  commons-rest/errors/src/main/java/org/eclipse/kapua/commons/rest/errors/EclipseLinkExceptionMapper.java
  qa/integration-steps/src/main/java/org/eclipse/kapua/qa/integration/steps/RestClientSteps.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/rest/RunRestParsingRequestTest.java
  qa/integration/src/test/resources/features/rest/parsingRequests/RestParsingRequestsContents.feature
  rest-api/web/src/main/java/org/eclipse/kapua/app/api/web/MoxyJsonFeatureCustomJsonProvider.java
  rest-api/web/src/main/java/org/eclipse/kapua/app/api/web/RestApisApplication.java
  service/api/src/main/java/org/eclipse/kapua/model/xml/adapters/XmlPropertiesAdapter.java
  service/api/src/test/java/org/eclipse/kapua/model/xml/adapters/XmlPropertiesAdapterTest.java
Labels: Bug

#4121 ✨ [REST-API] Add support to query operations by `status` in `GET /{scopeId}/devices/{deviceId}/operations`
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceManagementOperations.java
  rest-api/resources/src/main/resources/openapi/deviceOperation/deviceOperation-scopeId-deviceId.yaml
  rest-api/resources/src/main/resources/openapi/deviceOperation/deviceOperation.yaml
Labels: Enhancement

#4126 :memo: [Open API] Documented the allowSelfEdit field for serviceConfigurations
  rest-api/resources/src/main/resources/openapi/serviceConfiguration/serviceConfiguration.yaml
Labels: Documentation

#4124 ✨ Capability to search operations by their appId in API 'GET /{scopeId}/devices/{deviceId}/operations'
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceManagementOperations.java
  rest-api/resources/src/main/resources/openapi/deviceOperation/deviceOperation-scopeId-deviceId.yaml
Labels: Enhancement

#4122 📝 [Documentation] Update Kura documentation links in READMEs
  docs/kuraKapuaDocs.md
Labels: Documentation
