Repository eclipse-kapua/kapua, pull requests merged in 2024-05, with the labels that each got.

#4027 :arrow_up: [CI] Updated GitHub Actions for test coverage reports from Codecov Bash Uploader to codecov-action v4
  .github/actions/runTestsTaggedAs/action.yaml
  .github/workflows/kapua-ci.yaml
Labels: Bug

#4028 :arrow_up: [CI] Update GitHub Actions components
  .github/actions/runTestsTaggedAs/action.yaml
  .github/workflows/kapua-ci.yaml
  .github/workflows/security-scan.yaml
  .github/workflows/sonarCloud-scan.yaml
Labels: Enhancement

#4030 :bug: [CI] fixed providing of CODECOV_TOKEN to CI steps
  .github/workflows/kapua-ci.yaml
Labels: Bug

#4029 FIX - limitExceeded and pagination not working in users by role API 'GET /{scopeId}/roles/{roleId}/users'
  console/module/user/src/main/java/org/eclipse/kapua/app/console/module/user/server/GwtUserServiceImpl.java
  qa/integration/src/test/resources/features/user/UserRoleServiceI9n.feature
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Roles.java
  service/security/authorization/api/src/main/java/org/eclipse/kapua/service/authorization/role/RoleService.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/role/shiro/RoleServiceImpl.java
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authorization/shiro/AuthorizationModule.java
  service/security/test-steps/src/main/java/org/eclipse/kapua/service/authorization/steps/AuthorizationServiceSteps.java
  service/security/test/src/test/java/org/eclipse/kapua/service/security/test/SecurityLocatorConfiguration.java
Labels: Bug

#4032 FIX - Problem of wrong serialization of ComposedKey fields on the cache
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/cache/ComposedKey.java
  commons/src/main/java/org/eclipse/kapua/commons/service/internal/cache/EntityCache.java
Labels: Bug

#4033 FEATURE: Added new field for User matchTerm
  rest-api/resources/src/main/resources/openapi/user/user-scopeId.yaml
  service/user/internal/src/main/java/org/eclipse/kapua/service/user/internal/UserMatchPredicateImpl.java
Labels: Enhancement

#4035 :bug: [Job] Fixed serialization of JobStepDefinition.stepProperties via REST API
  service/job/api/src/main/java/org/eclipse/kapua/service/job/step/definition/JobStepDefinition.java
  service/job/api/src/main/java/org/eclipse/kapua/service/job/step/definition/JobStepDefinitionRecord.java
  service/job/internal/src/main/java/org/eclipse/kapua/service/job/step/definition/internal/JobStepDefinitionImpl.java
Labels: Bug

#4036 ⬆️ Bump `logback` from `1.2.11` to `1.2.13` - `CVE-2023-6481`
  pom.xml
Labels: Dependencies

#4037 ⬆️ Bump `commons-configuration2` from `2.9.0` to `2.10.1` - `CVE-2024-29131`
  pom.xml
Labels: Dependencies

#4038 Remove unnecessary localization logic
  console/web/src/main/webapp/console.jsp
Labels: Bug, Console GWT

#4039 :bug: [Core] Added missing error message for KapuaEntityUniquenessException
  service/api/src/main/java/org/eclipse/kapua/KapuaEntityUniquenessException.java
  service/api/src/main/resources/kapua-service-error-messages.properties
  service/api/src/test/java/org/eclipse/kapua/KapuaEntityUniquenessExceptionTest.java
  service/api/src/test/java/org/eclipse/kapua/KapuaIllegalArgumentExceptionTest.java
Labels: Bug

#4023 :fix: service events remove durable subscriptions
  commons/src/main/java/org/eclipse/kapua/commons/event/jms/JMSServiceEventBus.java
Labels: Bug

#4041 🐛 [REST API] Fixed returnNotNullEntity correctly handle null KapuaEntities
  commons-rest/errors/src/main/java/org/eclipse/kapua/commons/rest/errors/WebApplicationExceptionMapper.java
  rest-api/core/src/main/java/org/eclipse/kapua/app/api/core/resources/AbstractKapuaResource.java
  rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/resources/AbstractKapuaResourceTest.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/AccessInfos.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/AccessPermissions.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/AccessRoles.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Account.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Credentials.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceConnectionOptions.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceConnections.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceEvents.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceManagementOperationNotifications.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceManagementOperations.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Devices.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Domains.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/EndpointInfos.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Groups.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/JobExecutions.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/JobTargets.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/JobTriggers.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Jobs.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Roles.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/RolesPermissions.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Tags.java
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Users.java
Labels: Bug

#4043 :recycle: ProtocolDescriptionProvider instantied via DI
  assembly/broker-artemis/descriptors/kapua-broker-artemis.xml
  consumer/lifecycle-app/src/main/java/org/eclipse/kapua/consumer/lifecycle/SpringBridge.java
  consumer/lifecycle-app/src/main/resources/spring/applicationContext.xml
  consumer/lifecycle/src/main/java/org/eclipse/kapua/consumer/lifecycle/converter/DeviceManagementNotificationConverter.java
  consumer/lifecycle/src/main/java/org/eclipse/kapua/consumer/lifecycle/converter/KapuaLifeCycleConverter.java
  consumer/telemetry-app/src/main/java/org/eclipse/kapua/consumer/telemetry/SpringBridge.java
  consumer/telemetry-app/src/main/resources/spring/applicationContext.xml
  consumer/telemetry/src/main/java/org/eclipse/kapua/consumer/telemetry/converter/KapuaDataConverter.java
  service/authentication-app/src/main/java/org/eclipse/kapua/service/authentication/SpringBridge.java
  service/authentication-app/src/main/resources/spring/applicationContext.xml
  service/authentication/src/main/java/org/eclipse/kapua/service/authentication/AuthenticationServiceConverter.java
  service/camel/src/main/java/org/eclipse/kapua/service/camel/converter/AbstractKapuaConverter.java
  service/client/src/main/java/org/eclipse/kapua/service/client/protocol/CachingProtocolDescriptorProvider.java
  service/client/src/main/java/org/eclipse/kapua/service/client/protocol/DefaultProtocolDescriptionProvider.java
  service/client/src/main/java/org/eclipse/kapua/service/client/protocol/ProtocolDescriptorModule.java
  service/client/src/main/java/org/eclipse/kapua/service/client/protocol/ProtocolDescriptorProviders.java
  service/client/src/main/java/org/eclipse/kapua/service/client/setting/ServiceClientSetting.java
  service/client/src/test/java/org/eclipse/kapua/broker/client/protocol/DefaultProtocolDescriptorProviderTest.java
  service/client/src/test/java/org/eclipse/kapua/broker/client/protocol/ProtocolDescriptorProvidersTest.java
  service/client/src/test/java/org/eclipse/kapua/broker/client/protocol/ProtocolDescriptorTest.java
Labels: Enhancement

#4044 :fix: when mapping between strings, consider empty strings as null
  commons/src/main/java/org/eclipse/kapua/commons/model/mappers/KapuaBaseMapper.java
Labels: Bug

#4047 :bug: [REST API] Fixed DeviceNotConnectedException mapped HTTP error code to be 400
  commons-rest/errors/src/main/java/org/eclipse/kapua/commons/rest/errors/DeviceNotConnectedExceptionMapper.java
  commons-rest/model/src/main/java/org/eclipse/kapua/commons/rest/model/errors/DeviceNotConnectedExceptionInfo.java
Labels: Bug, REST API

#4045 FIX - Refactored code related to TypeDescriptor Class
  service/commons/elasticsearch/client-api/src/main/java/org/eclipse/kapua/service/elasticsearch/client/ElasticsearchClient.java
  service/commons/elasticsearch/client-api/src/main/java/org/eclipse/kapua/service/elasticsearch/client/ElasticsearchRepository.java
  service/commons/elasticsearch/client-api/src/main/java/org/eclipse/kapua/service/elasticsearch/client/model/InsertRequest.java
  service/commons/elasticsearch/client-api/src/main/java/org/eclipse/kapua/service/elasticsearch/client/model/InsertResponse.java
  service/commons/elasticsearch/client-api/src/main/java/org/eclipse/kapua/service/elasticsearch/client/model/Request.java
  service/commons/elasticsearch/client-api/src/main/java/org/eclipse/kapua/service/elasticsearch/client/model/Response.java
  service/commons/elasticsearch/client-api/src/main/java/org/eclipse/kapua/service/elasticsearch/client/model/TypeDescriptor.java
  service/commons/elasticsearch/client-api/src/main/java/org/eclipse/kapua/service/elasticsearch/client/model/UpdateRequest.java
  service/commons/elasticsearch/client-api/src/main/java/org/eclipse/kapua/service/elasticsearch/client/model/UpdateResponse.java
  service/commons/elasticsearch/client-rest/src/main/java/org/eclipse/kapua/service/elasticsearch/client/rest/ElasticsearchResourcePaths.java
  service/commons/elasticsearch/client-rest/src/main/java/org/eclipse/kapua/service/elasticsearch/client/rest/RestElasticsearchClient.java
  service/commons/storable/api/src/main/java/org/eclipse/kapua/service/storable/model/query/predicate/IdsPredicate.java
  service/commons/storable/api/src/main/java/org/eclipse/kapua/service/storable/model/query/predicate/StorablePredicateFactory.java
  service/commons/storable/internal/src/main/java/org/eclipse/kapua/service/storable/model/query/predicate/IdsPredicateImpl.java
  service/commons/storable/internal/src/main/java/org/eclipse/kapua/service/storable/model/query/predicate/StorablePredicateFactoryImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ChannelInfoElasticsearchRepository.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ChannelInfoRegistryFacadeImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ClientInfoElasticsearchRepository.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/DatastoreElasticSearchRepositoryBase.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MessageElasticsearchRepository.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MetricInfoRegistryFacadeImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MetricInfoRepositoryImpl.java
Labels: Bug
