Repository eclipse-kapua/kapua, pull requests merged in 2024-01, with the labels that each got.

#3937 fix(javadoc): fixed javadoc after #3924
  service/device/registry/api/src/main/java/org/eclipse/kapua/service/device/registry/connection/DeviceConnectionService.java
Labels: Bug

#3935 Fix device snapshot handling in XML format
  service/api/src/main/java/org/eclipse/kapua/service/config/ServiceConfiguration.java
  service/device/management/configuration/api/src/main/java/org/eclipse/kapua/service/device/management/configuration/DeviceConfiguration.java
Labels: Bug

#3926 FIX - introduced new changeset to update databasechangelog
  commons/src/main/resources/liquibase/2.0.0/databasechangelog_fields_update.xml
  commons/src/main/resources/liquibase/changelog-databasechangelog-fields-update-master.pre.xml
Labels: Bug

#3934 feat(deployment): added Elasticsearch HQ deployment when --dev option is used
  deployment/docker/README.md
  deployment/docker/compose/extras/docker-compose.es-dev.yml
  deployment/docker/kapua-webBrowserH2Settings.png
  deployment/docker/unix/docker-deploy.sh
  deployment/docker/unix/docker-logs.sh
  deployment/docker/unix/docker-undeploy.sh
  deployment/docker/win/docker-deploy.ps1
Labels: Enhancement

#3942 FIX - Restored support on XML content option on openApi doc for device configurations
  rest-api/resources/src/main/resources/openapi/deviceConfiguration/deviceConfiguration-scopeId-deviceId-componentId.yaml
  rest-api/resources/src/main/resources/openapi/deviceConfiguration/deviceConfiguration-scopeId-deviceId.yaml
Labels: Bug, Documentation

#3941 FIX - Restored support on XML content option on openApi doc for device snapshots
  rest-api/resources/src/main/resources/openapi/deviceSnapshot/deviceSnapshot-scopeId-deviceId-snapshotId.yaml
  rest-api/resources/src/main/resources/openapi/deviceSnapshot/deviceSnapshot-scopeId-deviceId.yaml
Labels: Bug, Documentation

#3948 Fix error while retrieving MFA option from REST API
  qa/integration/src/test/java/org/eclipse/kapua/integration/service/user/RunUserMfaUnitTest.java
  qa/integration/src/test/resources/features/user/LockoutExpirationI9n.feature
  qa/integration/src/test/resources/features/user/UserMfaUnitTests.feature
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/MfaOptionImplJpaRepository.java
  service/user/test-steps/src/main/java/org/eclipse/kapua/service/user/steps/UserServiceSteps.java
Labels: Bug

#3947 fix(console): fixed error reporting for DeviceAssetChannel
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/assets/DeviceAssetsPanel.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/assets/DeviceAssetsValues.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/server/GwtDeviceAssetServiceImpl.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/shared/model/management/assets/GwtDeviceAssetChannel.java
Labels: Bug, Console GWT

#3944 Fix/device event deadlock
  commons/src/main/java/org/eclipse/kapua/commons/jpa/JpaTxContext.java
  commons/src/main/java/org/eclipse/kapua/commons/jpa/KapuaEntityJpaRepository.java
  service/api/src/main/java/org/eclipse/kapua/storage/TxManagerImpl.java
  service/device/registry/api/src/main/java/org/eclipse/kapua/service/device/registry/DeviceRepository.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/event/internal/DeviceEventServiceImpl.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/internal/CachingDeviceRepository.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/internal/DeviceImplJpaRepository.java
  service/device/registry/internal/src/main/resources/META-INF/persistence.xml
Labels: Bug

#3943 FIX - Jaxb configuration changed to serialize EntityUniquenessExceptionInfo
  rest-api/web/src/main/java/org/eclipse/kapua/app/api/web/JaxbContextResolver.java
Labels: Bug

#3953 Include `clientId` field in Device update REST API example
  rest-api/resources/src/main/resources/openapi/device/device-scopeId-deviceId.yaml
Labels: Bug, Documentation

#3952 :fix: avoid returning incorrect password within error message
  qa/integration/src/test/resources/features/authentication/UserCredentialServiceUnitTests.feature
  service/api/src/main/resources/kapua-service-error-messages.properties
  service/security/authentication/api/src/main/java/org/eclipse/kapua/service/authentication/exception/KapuaAuthenticationErrorCodes.java
  service/security/authentication/api/src/main/resources/authentication-error-messages.properties
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/user/shiro/UserCredentialsServiceImpl.java
Labels: Bug

#3949 Fix OpenAPI Device Management Asset documentation
  rest-api/resources/src/main/resources/openapi/deviceAsset/deviceAsset-scopeId-deviceId-_read.yaml
  rest-api/resources/src/main/resources/openapi/deviceAsset/deviceAsset-scopeId-deviceId-_write.yaml
  rest-api/resources/src/main/resources/openapi/deviceAsset/deviceAsset-scopeId-deviceId.yaml
  rest-api/resources/src/main/resources/openapi/deviceAsset/deviceAsset.yaml
  rest-api/resources/src/main/resources/openapi/openapi.yaml
Labels: Bug, Documentation

#3951 Add tags to device on create operation
  qa/integration/src/test/java/org/eclipse/kapua/integration/service/device/RunDeviceI9nTest.java
  qa/integration/src/test/resources/features/tag/TagI9n.feature
  rest-api/resources/src/main/resources/openapi/device/device.yaml
  service/device/registry/api/src/main/java/org/eclipse/kapua/service/device/registry/Device.java
  service/device/registry/api/src/main/java/org/eclipse/kapua/service/device/registry/DeviceCreator.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/internal/DeviceCreatorImpl.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/internal/DeviceRegistryServiceImpl.java
  service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
Labels: Enhancement
