Repository eclipse-kapua/kapua, pull requests merged in 2025-05, with the labels that each got.

#4227 ⬆️ Bump`netty` from `4.1.114.Final` to `4.1.118.Final` - CVE-2024-8184 CVE-2024-22201 CVE-2022-2048 CVE-2024-9823
  pom.xml
Labels: Dependencies

#4228 ⬆️ Bump`jetty` from `9.4.53.v20231009` to `9.4.57.v20241219` - CVE-2024-8184 CVE-2024-22201 CVE-2022-2048 CVE-2024-9823
  pom.xml
Labels: Dependencies

#4229 ⬆️ Bump`commons-compress` from `1.24.0` to `1.27.1`
  pom.xml
Labels: Dependencies

#4232 :fix: message receivedOn field to epoc in millis (as it was for 1.6.x)
  broker/artemis/plugin/src/main/java/org/eclipse/kapua/broker/artemis/plugin/security/ServerPlugin.java
Labels: Bug

#4231 ⬆️ [Dependencies] Bump`shiro` from `1.12.0` to `1.13.0` - CVE-2023-46749
  pom.xml
Labels: CQ approved, Dependencies

#4235 :bug: [Job Engine] Added missing XmlRootElement annotations on JobEngine Client model classes
  commons-rest/model/src/main/java/org/eclipse/kapua/commons/rest/model/IsJobRunningMultipleResponse.java
  commons-rest/model/src/main/java/org/eclipse/kapua/commons/rest/model/IsJobRunningResponse.java
  commons-rest/model/src/main/java/org/eclipse/kapua/commons/rest/model/MultipleJobIdRequest.java
Labels: Bug

#4236 :bug: [Streams] Added missing resolution of the Device from the given clientId
  service/stream/internal/src/main/java/org/eclipse/kapua/service/stream/internal/StreamServiceImpl.java
Labels: Bug

#4238 :bug: [Datastore] Fixed parsing of MessageStore ServiceConfig
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/mediator/MessageStoreConfiguration.java
Labels: Bug

#4239 :fire: [SSO] Removed unwanted leftover code from previous changes
  plug-ins/sso/openid-connect/provider/src/main/java/org/eclipse/kapua/plugin/sso/openid/provider/AbstractOpenIDService.java
Labels: Bug

#4241 ✨ [REST API] Added SSO provider configuration and dependencies to REST API
  assembly/api/entrypoint/run-api
  deployment/docker/compose/sso/docker-compose.rest-api-sso.yml
  deployment/docker/unix/docker-deploy.sh
  deployment/docker/unix/sso/docker-sso-config.sh
  deployment/docker/unix/sso/rest-api/Dockerfile
  rest-api/core/pom.xml
Labels: Enhancement
