Repository eclipse-kapua/kapua, pull requests merged in 2025-06, with the labels that each got.

#4243 ⬆️ [Dependencies] Bump `xstream` from `1.4.20` to `1.4.21` - CVE-2024-47072
  pom.xml
Labels: Dependencies

#4250 :bug: [Console GWT] Fixed not efficient User.id to User.name resolution
  console/module/account/src/main/java/org/eclipse/kapua/app/console/module/account/server/GwtAccountServiceImpl.java
  console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/server/util/UserCreatedByModifiedByUtils.java
  console/module/authentication/src/main/java/org/eclipse/kapua/app/console/module/authentication/server/GwtCredentialServiceImpl.java
  console/module/authorization/src/main/java/org/eclipse/kapua/app/console/module/authorization/server/GwtGroupServiceImpl.java
  console/module/authorization/src/main/java/org/eclipse/kapua/app/console/module/authorization/server/GwtRoleServiceImpl.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/connection/ConnectionEditDialog.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/server/GwtDeviceConnectionServiceImpl.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/shared/model/connection/GwtDeviceConnectionOption.java
  console/module/endpoint/src/main/java/org/eclipse/kapua/app/console/module/endpoint/server/GwtEndpointServiceImpl.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/server/GwtJobServiceImpl.java
  console/module/user/src/main/java/org/eclipse/kapua/app/console/module/user/server/GwtUserServiceImpl.java
  service/user/api/src/main/java/org/eclipse/kapua/service/user/UserRepository.java
  service/user/api/src/main/java/org/eclipse/kapua/service/user/UserService.java
  service/user/internal/src/main/java/org/eclipse/kapua/service/user/internal/UserCachedRepository.java
  service/user/internal/src/main/java/org/eclipse/kapua/service/user/internal/UserImplJpaRepository.java
  service/user/internal/src/main/java/org/eclipse/kapua/service/user/internal/UserServiceImpl.java
Labels: Bug

#4251 ✨ [Elasticsearch] Improved performance of the Elasticsearch client when counting the number of entries
  console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/shared/util/KapuaGwtCommonsModelConverter.java
  console/module/data/src/main/java/org/eclipse/kapua/app/console/module/data/server/GwtDataServiceImpl.java
  console/module/data/src/main/java/org/eclipse/kapua/app/console/module/data/servlet/DataExporterServlet.java
  console/module/data/src/main/java/org/eclipse/kapua/app/console/module/data/shared/util/KapuaGwtDataModelConverter.java
  qa/integration/src/test/resources/features/datastore/Datastore.feature
  service/commons/elasticsearch/client-api/src/main/java/org/eclipse/kapua/service/elasticsearch/client/exception/ClientErrorCodes.java
  service/commons/elasticsearch/client-api/src/main/java/org/eclipse/kapua/service/elasticsearch/client/exception/ClientLimitsExceededException.java
  service/commons/elasticsearch/client-api/src/main/resources/elasticsearch-client-error-messages.properties
  service/commons/elasticsearch/client-rest/src/main/java/org/eclipse/kapua/service/elasticsearch/client/rest/ElasticsearchKeywords.java
  service/commons/elasticsearch/client-rest/src/main/java/org/eclipse/kapua/service/elasticsearch/client/rest/ElasticsearchResourcePaths.java
  service/commons/elasticsearch/client-rest/src/main/java/org/eclipse/kapua/service/elasticsearch/client/rest/QueryConverterImpl.java
  service/commons/elasticsearch/client-rest/src/main/java/org/eclipse/kapua/service/elasticsearch/client/rest/RestElasticsearchClient.java
  service/commons/storable/internal/src/main/java/org/eclipse/kapua/service/storable/model/query/AbstractStorableQuery.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ChannelInfoRegistryFacadeImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/ClientInfoRegistryFacadeImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/DatastoreModule.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MessageStoreFacadeImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/MetricInfoRegistryFacadeImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/model/query/ChannelInfoQueryImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/model/query/ClientInfoQueryImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/model/query/MessageQueryImpl.java
  service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/model/query/MetricInfoQueryImpl.java
Labels: Enhancement
