Repository eclipse-kapua/kapua, pull requests merged in 2025-01, with the labels that each got.

#4168 :memo: [Release Notes] Updated Release Note document with missing changes
  UPGRADE_NOTES.md
Labels: Documentation

#4169 [Release Notes] Updated Release Note document with missing changes
  UPGRADE_NOTES.md
Labels: Documentation

#4171 :bug: [Scheduler] Fixed update of TriggerDefinitionProperty.propertyType and definitions
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/definition/quartz/CronJobTriggerDefinition.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/definition/quartz/IntervalJobTriggerDefinition.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/definition/quartz/TriggerDefinitionAligner.java
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/definition/quartz/TriggerPropertyImpl.java
Labels: Bug

#4173 :bug: [Scheduler] Fixed returned exception when an invalid cron expression is provided
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/quartz/driver/QuartzTriggerDriver.java
  service/scheduler/test/src/test/resources/features/SchedulerService.feature
Labels: Bug

#4174 :bug: [Scheduler] Fixed description of 'cron' paramerter of Cron Trigger Definition
  service/scheduler/quartz/src/main/java/org/eclipse/kapua/service/scheduler/trigger/definition/quartz/CronJobTriggerDefinition.java
Labels: Bug

#4175 :bug: [Job Engine] Fixed NPE when checking running status for Job
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/JPAPersistenceManagerImpl.java
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/persistence/jpa/JpaExecutionInstanceDataRepositoryImpl.java
Labels: Bug

#4176 :bug: [Core] Fixed handling of null KapuaSession on prePersist and preUpdate operation in KapuaEntity
  commons/src/main/java/org/eclipse/kapua/commons/model/AbstractKapuaEntity.java
  commons/src/main/java/org/eclipse/kapua/commons/model/AbstractKapuaUpdatableEntity.java
Labels: Bug

#4164 :recycle: [Test] Added new set of test cases to test JobEngine Device Management Target Processors
  .github/workflows/kapua-ci.yaml
  qa/integration-steps/src/main/java/org/eclipse/kapua/qa/integration/steps/DockerSteps.java
  qa/integration-steps/src/main/java/org/eclipse/kapua/qa/integration/steps/utils/TestReadinessHttpConnection.java
  qa/integration-steps/src/main/java/org/eclipse/kapua/qa/integration/steps/utils/TestReadinessMqttBrokerConnection.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/service/jobEngine/RunJobEngineServiceI9nTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/service/jobEngine/RunJobEngineServiceOfflineDeviceI9nTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/service/jobEngine/RunJobEngineServiceOnlineDeviceI9nTest.java
  qa/integration/src/test/java/org/eclipse/kapua/integration/service/jobEngine/stepDefinitions/RunJobEngineServiceKeystoreStepDefinitionsI9nTest.java
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceKeystoreStepDefinitionsI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceOperations.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceProcessorAssetI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceProcessorBundleI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceProcessorCommandI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceProcessorConfigurationI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceProcessorKeystoreI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceProcessorPackagesI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceRestartOfflineDeviceI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceRestartOnlineDeviceI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceRestartOnlineDeviceSecondPartI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceStartOfflineDeviceI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceStartOnlineDeviceI9n.feature
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceStopOnlineDeviceI9n.feature
  qa/integration/src/test/resources/features/jobScheduling/TriggerServiceI9n.feature
  service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/KuraDevice.java
  service/job/test-steps/src/main/java/org/eclipse/kapua/service/job/steps/JobEngineSteps.java
  service/job/test-steps/src/main/java/org/eclipse/kapua/service/job/steps/JobTargetServiceSteps.java
  service/job/test/src/test/resources/features/JobService.feature
  service/job/test/src/test/resources/features/JobStepDefinitionService.feature
  service/job/test/src/test/resources/features/JobStepService.feature
Labels: Enhancement

#4178 :bug: [CI] Fixed Sonar Scan workflow
  .github/workflows/sonarCloud-scan.yaml
Labels: Bug, build

#4163 ✨ [Docs] Various documentation improvements
  README.md
  build-tools/src/main/toolchains/README.md
  build-tools/src/main/toolchains/ubuntu.xml
  docs/developer-guide/en/building.md
  docs/developer-guide/en/running.md
  docs/kuraKapuaDocs.md
Labels: Documentation

#4180 🐛 [Sonar] Disabled Sonar Scan for PR/Branches from forks due to missing SONAR_TOKEN not available for forks
  .github/workflows/sonarCloud-scan.yaml
Labels: Bug

#4181 :sparkles: [Docker] Migrated from rockylinux:8 to rockylinux:8-minimal base image
  assembly/java-base/docker/Dockerfile
  assembly/java-base/pom.xml
Labels: Enhancement

#4182 ✨ [Docker] Migrated from rockylinux:8-minimal to rockylinux:9-minimal base image
  assembly/java-base/pom.xml
Labels: Enhancement

#4183 :sparkles: [Docker] Migrated from java-11-openjdk to java-11-openjdk-headless JVM package
  assembly/java-base/docker/Dockerfile
Labels: Enhancement

#4184 Feat further docker images footprint improvements
  assembly/java-base/docker/Dockerfile
  assembly/jetty-base/docker/Dockerfile
Labels: Enhancement

#4185 :bug: [CI] Fixed permissions assigned to 'License Checking' workflow
  .github/workflows/license-check.yaml
Labels: Bug
