Repository eclipse-kapua/kapua, pull requests merged in 2025-03, with the labels that each got.

#4206 :sparkles: [Device Connection] Allowed user to disconnect a DeviceConnection
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceConnections.java
  service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/connection/internal/DeviceConnectionServiceImpl.java
Labels: Enhancement

#4207 :spakles: [Console GWT] Added Disconnect button on Device Connection view
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/connection/ConnectionGrid.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/connection/toolbar/ConnectionGridToolbar.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/connection/toolbar/DeviceConnectionDisconnectDialog.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/server/GwtDeviceConnectionServiceImpl.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/shared/service/GwtDeviceConnectionService.java
Labels: Enhancement

#4209 ✨ [OpenAPI] Improve OpenAPI Specification for New Authorization Endpoint
  rest-api/resources/src/main/resources/openapi/authorization/authorization-scopeId.yaml
  rest-api/resources/src/main/resources/openapi/authorization/authorization.yaml
Labels: Enhancement, Documentation

#4210 :bug: [Test] Fix user coupling test
  qa/integration/src/test/resources/features/connection/UserCouplingI9n.feature
  service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/BrokerSteps.java
  service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
  service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/KuraDevice.java
Labels: Bug, Test

#4212 :bug: [Job] Fixed JobStepDefinitionProperties description for complex object to state that also JSON is allowed
  service/device/management/asset/job/src/main/java/org/eclipse/kapua/service/device/management/asset/job/definition/DeviceAssetWriteJobStepDefinition.java
  service/device/management/command/job/src/main/java/org/eclipse/kapua/service/device/management/command/job/definition/DeviceCommandExecJobStepDefinition.java
  service/device/management/packages/job/src/main/java/org/eclipse/kapua/service/device/management/packages/job/definition/DevicePackageDownloadJobStepDefinition.java
  service/device/management/packages/job/src/main/java/org/eclipse/kapua/service/device/management/packages/job/definition/DevicePackageUninstallJobStepDefinition.java
Labels: Bug

#4213 :bug: [Open API] Updated POST /{scopeId}/streams/messages description
  rest-api/resources/src/main/resources/openapi/stream/stream-scopeId.yaml
Labels: Bug

#4211 🐛 [Job] Device target status incorrect when re-executing a failed step.
  job-engine/jbatch/src/main/java/org/eclipse/kapua/job/engine/jbatch/listener/KapuaJobListener.java
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceOperations.feature
Labels: Enhancement

#4215 🐛 [Device Management] - Command execution with env variables with 'POST /{scopeId}/devices/{deviceId}/commands/_execute' API does not work
  rest-api/resources/src/main/resources/openapi/deviceCommand/deviceCommand.yaml
  service/device/management/command/api/src/main/java/org/eclipse/kapua/service/device/management/command/DeviceCommandInput.java
  service/device/management/command/internal/src/main/java/org/eclipse/kapua/service/device/management/command/internal/DeviceCommandInputImpl.java
  service/device/management/command/internal/src/main/java/org/eclipse/kapua/service/device/management/command/internal/DeviceCommandManagementServiceImpl.java
  translator/kapua/kura/src/main/java/org/eclipse/kapua/translator/kapua/kura/TranslatorAppCommandKapuaKura.java
Labels: Bug

#4216 :bug: [Serialization] Fixed JAXBContext configuration for applications
  console/web/src/main/java/org/eclipse/kapua/app/console/ConsoleJAXBContextProvider.java
  consumer/lifecycle-app/src/main/java/org/eclipse/kapua/consumer/lifecycle/LifecycleJAXBContextProvider.java
  job-engine/app/web/src/main/java/org/eclipse/kapua/job/engine/app/web/jaxb/JobEngineJAXBContextProvider.java
  rest-api/web/src/main/java/org/eclipse/kapua/app/api/web/RestApiJAXBContextProvider.java
  service/authentication-app/src/main/java/org/eclipse/kapua/service/authentication/AuthenticationJAXBContextProvider.java
Labels: Bug

#4218 :bug: [SSO] Fixed handling of external username claim not present in userInfo
  service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/realm/JwtAuthenticatingRealm.java
Labels: Bug

#4219 🐛 [Job Engine] Job start on precise targets
  job-engine/app/resources/src/main/java/org/eclipse/kapua/job/engine/app/resources/JobEngineResource.java
  job-engine/client/src/main/java/org/eclipse/kapua/job/engine/client/JobEngineServiceClient.java
  qa/common/src/main/java/org/eclipse/kapua/qa/common/TestJAXBContextProvider.java
  qa/integration/src/test/resources/features/jobEngine/JobEngineServiceOperations.feature
  rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/JobEngine.java
  service/job/test-steps/src/main/java/org/eclipse/kapua/service/job/steps/JobEngineSteps.java
  service/job/test-steps/src/main/java/org/eclipse/kapua/service/job/steps/JobTargetServiceSteps.java
Labels: Bug

#4220 :bug: [SSO] Added missing information loggin when SSO provider request fails
  plug-ins/sso/openid-connect/provider/src/main/java/org/eclipse/kapua/plugin/sso/openid/provider/AbstractOpenIDService.java
Labels: Bug

#4222 🐛 [GWT Console] Fix "Fill with example values" Button Visibility for Batch Job Steps
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/client/steps/JobStepAddDialog.java
  console/module/job/src/main/java/org/eclipse/kapua/app/console/module/job/client/steps/JobStepEditDialog.java
Labels: Bug, Console GWT

#4221 :sparkles: [GWT Console] Added Device disconnect button in Device view
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/DeviceDisconnectDialog.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/DeviceGrid.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/client/device/DeviceGridToolbar.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/shared/model/GwtDevice.java
  console/module/device/src/main/java/org/eclipse/kapua/app/console/module/device/shared/util/KapuaGwtDeviceModelConverter.java
Labels: Enhancement, Console GWT

#4223 :bug: [Broker] Datastore improve message store granularity
  consumer/telemetry-app/src/main/resources/camel/camel.xml
  consumer/telemetry-app/src/main/resources/spring/applicationContext.xml
  consumer/telemetry/src/main/java/org/eclipse/kapua/consumer/telemetry/listener/DataStorageMessageProcessor.java
Labels: Bug
